// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function normalizeCharacter(character) {
  switch (character) {
    case "\r" :
    case "\t" :
    case "\u00a0" :
    case "\u2007" :
    case "\u202f" :
      return " ";
    case "`" :
    case "´" :
    case "‘" :
    case "’" :
    case "′" :
    case "‵" :
      return "'";
    case "–" :
    case "—" :
    case "−" :
      return "-";
    case "（" :
      return "(";
    case "）" :
      return ")";
    case "，" :
      return ",";
    case "：" :
      return ":";
    case "＜" :
      return "<";
    case "＞" :
      return ">";
    case "［" :
      return "[";
    case "］" :
      return "]";
    case "｛" :
      return "{";
    case "｝" :
      return "}";
    default:
      return character;
  }
}

function normalize(input) {
  let output = Stdlib_Array.make(input.length, "");
  for (let index = 0, index_finish = input.length; index < index_finish; ++index) {
    output[index] = normalizeCharacter(String(input[index]));
  }
  return output.join("");
}

export {
  normalizeCharacter,
  normalize,
}
/* No side effect */
