// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "./MoveParser.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let ExpansionFailure = /* @__PURE__ */Primitive_exceptions.create("MoveExecutor.ExpansionFailure");

function faceToSticker(size, face, row, col) {
  let last = size - 1 | 0;
  switch (face) {
    case "U" :
      return {
        position: {
          x: col,
          y: last,
          z: row
        },
        normal: {
          x: 0,
          y: 1,
          z: 0
        }
      };
    case "L" :
      return {
        position: {
          x: 0,
          y: last - row | 0,
          z: col
        },
        normal: {
          x: -1,
          y: 0,
          z: 0
        }
      };
    case "F" :
      return {
        position: {
          x: col,
          y: last - row | 0,
          z: last
        },
        normal: {
          x: 0,
          y: 0,
          z: 1
        }
      };
    case "R" :
      return {
        position: {
          x: last,
          y: last - row | 0,
          z: last - col | 0
        },
        normal: {
          x: 1,
          y: 0,
          z: 0
        }
      };
    case "B" :
      return {
        position: {
          x: last - col | 0,
          y: last - row | 0,
          z: 0
        },
        normal: {
          x: 0,
          y: 0,
          z: -1
        }
      };
    case "D" :
      return {
        position: {
          x: col,
          y: 0,
          z: last - row | 0
        },
        normal: {
          x: 0,
          y: -1,
          z: 0
        }
      };
  }
}

function stickerToFacelet(size, sticker) {
  let last = size - 1 | 0;
  let normal = sticker.normal;
  let match = sticker.position;
  let z = match.z;
  let x = match.x;
  if (normal.y === 1) {
    return [
      "U",
      z,
      x
    ];
  }
  if (normal.y === -1) {
    return [
      "D",
      last - z | 0,
      x
    ];
  }
  let y = match.y;
  if (normal.z === 1) {
    return [
      "F",
      last - y | 0,
      x
    ];
  } else if (normal.z === -1) {
    return [
      "B",
      last - y | 0,
      last - x | 0
    ];
  } else if (normal.x === 1) {
    return [
      "R",
      last - y | 0,
      last - z | 0
    ];
  } else {
    return [
      "L",
      last - y | 0,
      z
    ];
  }
}

function rotateVector(last, vector, axis, direction, coordinate) {
  let invert = value => {
    if (coordinate) {
      return last - value | 0;
    } else {
      return -value | 0;
    }
  };
  switch (axis) {
    case "X" :
      if (direction !== 1) {
        return {
          x: vector.x,
          y: vector.z,
          z: invert(vector.y)
        };
      } else {
        return {
          x: vector.x,
          y: invert(vector.z),
          z: vector.y
        };
      }
    case "Y" :
      if (direction !== 1) {
        return {
          x: invert(vector.z),
          y: vector.y,
          z: vector.x
        };
      } else {
        return {
          x: vector.z,
          y: vector.y,
          z: invert(vector.x)
        };
      }
    case "Z" :
      if (direction !== 1) {
        return {
          x: vector.y,
          y: invert(vector.x),
          z: vector.z
        };
      } else {
        return {
          x: invert(vector.y),
          y: vector.x,
          z: vector.z
        };
      }
  }
}

function rotateSticker(size, sticker, axis, direction) {
  let last = size - 1 | 0;
  return {
    position: rotateVector(last, sticker.position, axis, direction, true),
    normal: rotateVector(last, sticker.normal, axis, direction, false)
  };
}

function axisAndDirection(move) {
  switch (move.TAG) {
    case "FaceTurn" :
      switch (move._0) {
        case "U" :
          return [
            "Y",
            -1
          ];
        case "L" :
          return [
            "X",
            1
          ];
        case "F" :
          return [
            "Z",
            -1
          ];
        case "R" :
          return [
            "X",
            -1
          ];
        case "B" :
          return [
            "Z",
            1
          ];
        case "D" :
          return [
            "Y",
            1
          ];
      }
    case "SliceTurn" :
      switch (move._0) {
        case "M" :
          return [
            "X",
            1
          ];
        case "E" :
          return [
            "Y",
            1
          ];
        case "S" :
          return [
            "Z",
            -1
          ];
      }
    case "Rotation" :
      switch (move._0) {
        case "X" :
          return [
            "X",
            -1
          ];
        case "Y" :
          return [
            "Y",
            -1
          ];
        case "Z" :
          return [
            "Z",
            -1
          ];
      }
  }
}

function depthFromFace(size, face, position) {
  switch (face) {
    case "U" :
      return size - position.y | 0;
    case "L" :
      return position.x + 1 | 0;
    case "F" :
      return size - position.z | 0;
    case "R" :
      return size - position.x | 0;
    case "B" :
      return position.z + 1 | 0;
    case "D" :
      return position.y + 1 | 0;
  }
}

function affectsSticker(size, move, sticker) {
  switch (move.TAG) {
    case "FaceTurn" :
      let range = move._1;
      let depth = depthFromFace(size, move._0, sticker.position);
      if (depth >= range.from_) {
        return depth <= range.to_;
      } else {
        return false;
      }
    case "SliceTurn" :
      let middle = size / 2 | 0;
      switch (move._0) {
        case "M" :
          return sticker.position.x === middle;
        case "E" :
          return sticker.position.y === middle;
        case "S" :
          return sticker.position.z === middle;
      }
    case "Rotation" :
      return true;
  }
}

function copyState(state) {
  return {
    size: state.size,
    facelets: state.facelets.map(facelets => facelets.map(value => value))
  };
}

function applyQuarter(state, move, direction) {
  let output = copyState(state);
  let match = axisAndDirection(move);
  let axis = match[0];
  let rotationDirection = match[1] * direction | 0;
  let size = state.size;
  for (let faceIndex = 0; faceIndex <= 5; ++faceIndex) {
    let face = StateTypes.storageOrder[faceIndex];
    let sourceFacelets = state.facelets[faceIndex];
    for (let row = 0; row < size; ++row) {
      for (let col = 0; col < size; ++col) {
        let sourceIndex = (row * size | 0) + col | 0;
        let sticker = faceToSticker(size, face, row, col);
        if (affectsSticker(size, move, sticker)) {
          let target = rotateSticker(size, sticker, axis, rotationDirection);
          let match$1 = stickerToFacelet(size, target);
          let targetFacelets = output.facelets[StateTypes.storageIndex(match$1[0])];
          targetFacelets[(match$1[1] * size | 0) + match$1[2] | 0] = sourceFacelets[sourceIndex];
        }
      }
    }
  }
  return output;
}

function normalizeTurns(turns) {
  let normalized = turns % 4;
  if (normalized < 0) {
    return normalized + 4 | 0;
  } else {
    return normalized;
  }
}

function applyStep(state, step) {
  let result = state;
  let quarters = normalizeTurns(step.turns);
  for (let _for = 1; _for <= quarters; ++_for) {
    result = applyQuarter(result, step.move, 1);
  }
  return result;
}

function pushStep(steps, move, turns, groupId) {
  if (normalizeTurns(turns) === 0) {
    return;
  }
  if (steps.length >= 100000) {
    throw {
      RE_EXN_ID: ExpansionFailure,
      _1: {
        TAG: "ExpansionLimitExceeded",
        _0: 100000
      },
      Error: new Error()
    };
  }
  steps.push({
    step: {
      move: move,
      turns: turns
    },
    pause: false,
    durationMs: undefined,
    comment: undefined,
    groupId: groupId
  });
}

function pushPause(steps, durationMs, groupId) {
  if (steps.length >= 100000) {
    throw {
      RE_EXN_ID: ExpansionFailure,
      _1: {
        TAG: "ExpansionLimitExceeded",
        _0: 100000
      },
      Error: new Error()
    };
  }
  steps.push({
    step: undefined,
    pause: true,
    durationMs: durationMs,
    comment: undefined,
    groupId: groupId
  });
}

function pushComment(steps, text, groupId) {
  if (steps.length >= 100000) {
    throw {
      RE_EXN_ID: ExpansionFailure,
      _1: {
        TAG: "ExpansionLimitExceeded",
        _0: 100000
      },
      Error: new Error()
    };
  }
  steps.push({
    step: undefined,
    pause: false,
    durationMs: undefined,
    comment: text,
    groupId: groupId
  });
}

function expandSequence(steps, units, groupId, nextGroupId, direction) {
  for (let offset = 0, offset_finish = units.length; offset < offset_finish; ++offset) {
    let index = direction === 1 ? offset : (units.length - 1 | 0) - offset | 0;
    expandUnit(steps, units[index], groupId, nextGroupId, direction);
  }
}

function expandRepeated(steps, units, repeat, nextGroupId, direction) {
  let repetitions = repeat < 0 ? -repeat | 0 : repeat;
  let nestedDirection = direction * (
    repeat < 0 ? -1 : 1
  ) | 0;
  for (let _for = 1; _for <= repetitions; ++_for) {
    nextGroupId.contents = nextGroupId.contents + 1 | 0;
    expandSequence(steps, units, nextGroupId.contents, nextGroupId, nestedDirection);
  }
}

function expandCommutator(steps, left, right, groupId, nextGroupId, direction) {
  if (direction === 1) {
    expandSequence(steps, left, groupId, nextGroupId, 1);
    expandSequence(steps, right, groupId, nextGroupId, 1);
    expandSequence(steps, left, groupId, nextGroupId, -1);
    return expandSequence(steps, right, groupId, nextGroupId, -1);
  } else {
    expandSequence(steps, right, groupId, nextGroupId, 1);
    expandSequence(steps, left, groupId, nextGroupId, 1);
    expandSequence(steps, right, groupId, nextGroupId, -1);
    return expandSequence(steps, left, groupId, nextGroupId, -1);
  }
}

function expandConjugate(steps, left, right, groupId, nextGroupId, direction) {
  expandSequence(steps, left, groupId, nextGroupId, 1);
  expandSequence(steps, right, groupId, nextGroupId, direction);
  expandSequence(steps, left, groupId, nextGroupId, -1);
}

function expandUnit(steps, unit, groupId, nextGroupId, direction) {
  let seconds = unit.desc;
  if (typeof seconds !== "object") {
    return pushPause(steps, undefined, groupId);
  }
  switch (seconds.TAG) {
    case "Move" :
      return pushStep(steps, seconds._0, seconds._1 * direction | 0, groupId);
    case "TimedPause" :
      return pushPause(steps, Math.round(seconds._0 * 1000.0) | 0, groupId);
    case "BlockComment" :
      return pushComment(steps, seconds._0, groupId);
    case "Group" :
      return expandRepeated(steps, seconds._0, seconds._1, nextGroupId, direction);
    case "Commutator" :
      let repeat = seconds._2;
      let right = seconds._1;
      let left = seconds._0;
      let repetitions = repeat < 0 ? -repeat | 0 : repeat;
      let nestedDirection = direction * (
        repeat < 0 ? -1 : 1
      ) | 0;
      for (let _for = 1; _for <= repetitions; ++_for) {
        expandCommutator(steps, left, right, groupId, nextGroupId, nestedDirection);
      }
      return;
    case "Conjugate" :
      let repeat$1 = seconds._2;
      let right$1 = seconds._1;
      let left$1 = seconds._0;
      let repetitions$1 = repeat$1 < 0 ? -repeat$1 | 0 : repeat$1;
      let nestedDirection$1 = direction * (
        repeat$1 < 0 ? -1 : 1
      ) | 0;
      for (let _for$1 = 1; _for$1 <= repetitions$1; ++_for$1) {
        expandConjugate(steps, left$1, right$1, groupId, nextGroupId, nestedDirection$1);
      }
      return;
  }
}

function expandTimeline(alg) {
  try {
    let steps = [];
    let nextGroupId = {
      contents: 0
    };
    expandSequence(steps, alg, undefined, nextGroupId, 1);
    return {
      TAG: "Ok",
      _0: steps
    };
  } catch (raw_error) {
    let error = Primitive_exceptions.internalToException(raw_error);
    if (error.RE_EXN_ID === ExpansionFailure) {
      return {
        TAG: "Error",
        _0: error._1
      };
    }
    throw error;
  }
}

function expand(alg) {
  let error = expandTimeline(alg);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let steps = [];
  error._0.forEach(entry => {
    let step = entry.step;
    if (step !== undefined) {
      steps.push(step);
      return;
    }
  });
  return {
    TAG: "Ok",
    _0: steps
  };
}

function validateState(state) {
  if (!StateTypes.isSupportedSize(state.size)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidState",
        _0: "Cube size must be between 2 and 5."
      }
    };
  }
  if (state.facelets.length !== 6) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidState",
        _0: "A cube state must contain six faces."
      }
    };
  }
  let expected = state.size * state.size | 0;
  let valid = state.facelets.every(facelets => facelets.length === expected);
  if (valid) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidState",
        _0: "Every face must contain size² stickers."
      }
    };
  }
}

function applyAlg(state, alg) {
  let reason = validateState(state);
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let reason$1 = expand(alg);
  if (reason$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: Stdlib_Array.reduce(reason$1._0, state, applyStep)
    };
  } else {
    return {
      TAG: "Error",
      _0: reason$1._0
    };
  }
}

function parseAndApplyWithOptions(size, lowercaseMode, notationDialect, input) {
  let error = MoveParser.parseWithOptions(size, lowercaseMode, notationDialect, input);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0.message
    };
  }
  let state = StateTypes.solved(size);
  if (state.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: "Cube size must be between 2 and 5."
    };
  }
  let result = applyAlg(state._0, error._0);
  if (result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: result._0
    };
  }
  let message = result._0;
  if (message.TAG === "InvalidState") {
    return {
      TAG: "Error",
      _0: message._0
    };
  } else {
    return {
      TAG: "Error",
      _0: `Expanded algorithms may not exceed ` + message._0.toString() + ` moves.`
    };
  }
}

function parseAndApplyWithLowercaseMode(size, lowercaseMode, input) {
  return parseAndApplyWithOptions(size, lowercaseMode, "Modern", input);
}

function parseAndApply(size, input) {
  return parseAndApplyWithLowercaseMode(size, "Wide", input);
}

let maxExpandedMoves = 100000;

export {
  ExpansionFailure,
  maxExpandedMoves,
  faceToSticker,
  stickerToFacelet,
  rotateVector,
  rotateSticker,
  axisAndDirection,
  depthFromFace,
  affectsSticker,
  copyState,
  applyQuarter,
  normalizeTurns,
  applyStep,
  pushStep,
  pushPause,
  pushComment,
  expandSequence,
  expandRepeated,
  expandCommutator,
  expandConjugate,
  expandUnit,
  expandTimeline,
  expand,
  validateState,
  applyAlg,
  parseAndApplyWithOptions,
  parseAndApplyWithLowercaseMode,
  parseAndApply,
}
/* No side effect */
