// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateTypes from "../State/StateTypes.res.mjs";
import * as Stdlib_Math from "@rescript/runtime/lib/es6/Stdlib_Math.js";
import * as MoveExecutor from "./MoveExecutor.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let generatedLoc = {
  start: 0,
  end_: 0
};

function located(desc) {
  return {
    desc: desc,
    loc: generatedLoc
  };
}

function faceName(face) {
  switch (face) {
    case "U" :
      return "U";
    case "L" :
      return "L";
    case "F" :
      return "F";
    case "R" :
      return "R";
    case "B" :
      return "B";
    case "D" :
      return "D";
  }
}

function sliceName(slice) {
  switch (slice) {
    case "M" :
      return "M";
    case "E" :
      return "E";
    case "S" :
      return "S";
  }
}

function axisName(axis) {
  switch (axis) {
    case "X" :
      return "x";
    case "Y" :
      return "y";
    case "Z" :
      return "z";
  }
}

function suffix(turns) {
  if (turns === 1) {
    return "";
  } else if (turns === -1) {
    return "'";
  } else if (turns < 0) {
    return (-turns | 0).toString() + "'";
  } else {
    return turns.toString();
  }
}

function serializeMove(move, turns) {
  let family;
  switch (move.TAG) {
    case "FaceTurn" :
      let range = move._1;
      let name = faceName(move._0);
      family = range.from_ === 1 && range.to_ === 1 ? name : (
          range.from_ === 1 && range.to_ === 2 ? name + "w" : (
              range.from_ === 1 ? range.to_.toString() + name + "w" : (
                  range.from_ === range.to_ ? range.from_.toString() + name : range.from_.toString() + "-" + range.to_.toString() + name + "w"
                )
            )
        );
      break;
    case "SliceTurn" :
      family = sliceName(move._0);
      break;
    case "Rotation" :
      family = axisName(move._0);
      break;
  }
  return family + suffix(turns);
}

function serializeUnit(unit) {
  let text = unit.desc;
  if (typeof text !== "object") {
    return ".";
  }
  switch (text.TAG) {
    case "Move" :
      return serializeMove(text._0, text._1);
    case "BlockComment" :
      return "/*" + text._0 + "*/";
    case "Group" :
      return "(" + serialize(text._0) + ")" + suffix(text._1);
    case "Commutator" :
      return "[" + serialize(text._0) + ", " + serialize(text._1) + "]" + suffix(text._2);
    case "Conjugate" :
      return "[" + serialize(text._0) + ": " + serialize(text._1) + "]" + suffix(text._2);
  }
}

function serialize(alg) {
  return alg.map(serializeUnit).join(" ");
}

function invertUnit(unit) {
  let text = unit.desc;
  let tmp;
  if (typeof text !== "object") {
    tmp = "Pause";
  } else {
    switch (text.TAG) {
      case "Move" :
        tmp = {
          TAG: "Move",
          _0: text._0,
          _1: -text._1 | 0
        };
        break;
      case "BlockComment" :
        tmp = {
          TAG: "BlockComment",
          _0: text._0
        };
        break;
      case "Group" :
        tmp = {
          TAG: "Group",
          _0: text._0,
          _1: -text._1 | 0
        };
        break;
      case "Commutator" :
        tmp = {
          TAG: "Commutator",
          _0: text._0,
          _1: text._1,
          _2: -text._2 | 0
        };
        break;
      case "Conjugate" :
        tmp = {
          TAG: "Conjugate",
          _0: text._0,
          _1: text._1,
          _2: -text._2 | 0
        };
        break;
    }
  }
  return {
    desc: tmp,
    loc: generatedLoc
  };
}

function invert(alg) {
  let output = [];
  for (let offset = 0, offset_finish = alg.length; offset < offset_finish; ++offset) {
    output.push(invertUnit(alg[(alg.length - 1 | 0) - offset | 0]));
  }
  return output;
}

function moveAxis(move) {
  switch (move.TAG) {
    case "FaceTurn" :
      switch (move._0) {
        case "L" :
        case "R" :
          return "X";
        case "F" :
        case "B" :
          return "Z";
        case "U" :
        case "D" :
          return "Y";
      }
    case "SliceTurn" :
      switch (move._0) {
        case "M" :
          return "X";
        case "E" :
          return "Y";
        case "S" :
          return "Z";
      }
    case "Rotation" :
      return move._0;
  }
}

function canonicalTurns(turns) {
  let normalized = (turns % 4 + 4 | 0) % 4;
  if (normalized > 2 || normalized < 0) {
    return -1;
  } else {
    return normalized;
  }
}

function flushRun(output, run) {
  run.forEach(step => {
    let turns = canonicalTurns(step.turns);
    if (turns !== 0) {
      output.push({
        desc: {
          TAG: "Move",
          _0: step.move,
          _1: turns
        },
        loc: generatedLoc
      });
      return;
    }
  });
  run.splice(0, run.length);
}

function addToRun(run, step) {
  let index = run.findIndex(existing => Primitive_object.equal(existing.move, step.move));
  if (index === -1) {
    run.push(step);
    return;
  }
  let existing = run[index];
  run[index] = {
    move: existing.move,
    turns: existing.turns + step.turns | 0
  };
}

function simplify(alg) {
  let error = MoveExecutor.expandTimeline(alg);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let output = [];
  let run = [];
  let runAxis = {
    contents: undefined
  };
  error._0.forEach(entry => {
    let match = entry.step;
    let match$1 = entry.pause;
    let match$2 = entry.comment;
    if (match === undefined) {
      if (match$1) {
        flushRun(output, run);
        runAxis.contents = undefined;
        output.push({
          desc: "Pause",
          loc: generatedLoc
        });
        return;
      } else if (match$2 !== undefined) {
        flushRun(output, run);
        runAxis.contents = undefined;
        output.push({
          desc: {
            TAG: "BlockComment",
            _0: match$2
          },
          loc: generatedLoc
        });
        return;
      } else {
        return;
      }
    }
    let axis = moveAxis(match.move);
    if (Primitive_object.notequal(runAxis.contents, axis)) {
      flushRun(output, run);
      runAxis.contents = axis;
    }
    addToRun(run, match);
  });
  flushRun(output, run);
  return {
    TAG: "Ok",
    _0: output
  };
}

function mirrorFace(plane, face) {
  switch (plane) {
    case "LR" :
      switch (face) {
        case "L" :
          return "R";
        case "R" :
          return "L";
        default:
          return face;
      }
    case "FB" :
      switch (face) {
        case "F" :
          return "B";
        case "B" :
          return "F";
        default:
          return face;
      }
    case "UD" :
      switch (face) {
        case "U" :
          return "D";
        case "D" :
          return "U";
        default:
          return face;
      }
  }
}

function mirrorAxisFactor(plane, axis) {
  switch (plane) {
    case "LR" :
      switch (axis) {
        case "X" :
          return 1;
        case "Y" :
        case "Z" :
          return -1;
      }
    case "FB" :
      switch (axis) {
        case "X" :
        case "Y" :
          return -1;
        case "Z" :
          return 1;
      }
    case "UD" :
      switch (axis) {
        case "Y" :
          return 1;
        case "X" :
        case "Z" :
          return -1;
      }
  }
}

function mirrorUnit(unit, plane) {
  let text = unit.desc;
  let tmp;
  if (typeof text !== "object") {
    tmp = "Pause";
  } else {
    switch (text.TAG) {
      case "Move" :
        let slice = text._0;
        switch (slice.TAG) {
          case "FaceTurn" :
            tmp = {
              TAG: "Move",
              _0: {
                TAG: "FaceTurn",
                _0: mirrorFace(plane, slice._0),
                _1: slice._1
              },
              _1: -text._1 | 0
            };
            break;
          case "SliceTurn" :
            let slice$1 = slice._0;
            let axis = moveAxis({
              TAG: "SliceTurn",
              _0: slice$1
            });
            tmp = {
              TAG: "Move",
              _0: {
                TAG: "SliceTurn",
                _0: slice$1
              },
              _1: text._1 * mirrorAxisFactor(plane, axis) | 0
            };
            break;
          case "Rotation" :
            let axis$1 = slice._0;
            tmp = {
              TAG: "Move",
              _0: {
                TAG: "Rotation",
                _0: axis$1
              },
              _1: text._1 * mirrorAxisFactor(plane, axis$1) | 0
            };
            break;
        }
        break;
      case "BlockComment" :
        tmp = {
          TAG: "BlockComment",
          _0: text._0
        };
        break;
      case "Group" :
        tmp = {
          TAG: "Group",
          _0: mirror(text._0, plane),
          _1: text._1
        };
        break;
      case "Commutator" :
        tmp = {
          TAG: "Commutator",
          _0: mirror(text._0, plane),
          _1: mirror(text._1, plane),
          _2: text._2
        };
        break;
      case "Conjugate" :
        tmp = {
          TAG: "Conjugate",
          _0: mirror(text._0, plane),
          _1: mirror(text._1, plane),
          _2: text._2
        };
        break;
    }
  }
  return {
    desc: tmp,
    loc: generatedLoc
  };
}

function mirror(alg, plane) {
  return alg.map(unit => mirrorUnit(unit, plane));
}

function rotateAxisOnce(by, axis) {
  switch (by) {
    case "X" :
      switch (axis) {
        case "X" :
          return [
            "X",
            1
          ];
        case "Y" :
          return [
            "Z",
            -1
          ];
        case "Z" :
          return [
            "Y",
            1
          ];
      }
    case "Y" :
      switch (axis) {
        case "X" :
          return [
            "Z",
            1
          ];
        case "Y" :
          return [
            "Y",
            1
          ];
        case "Z" :
          return [
            "X",
            -1
          ];
      }
    case "Z" :
      switch (axis) {
        case "X" :
          return [
            "Y",
            -1
          ];
        case "Y" :
          return [
            "X",
            1
          ];
        case "Z" :
          return [
            "Z",
            1
          ];
      }
  }
}

function rotateFaceOnce(by, face) {
  switch (by) {
    case "X" :
      switch (face) {
        case "U" :
          return "B";
        case "F" :
          return "U";
        case "L" :
        case "R" :
          return face;
        case "B" :
          return "D";
        case "D" :
          return "F";
      }
    case "Y" :
      switch (face) {
        case "L" :
          return "B";
        case "F" :
          return "L";
        case "R" :
          return "F";
        case "B" :
          return "R";
        case "U" :
        case "D" :
          return face;
      }
    case "Z" :
      switch (face) {
        case "U" :
          return "R";
        case "L" :
          return "U";
        case "R" :
          return "D";
        case "F" :
        case "B" :
          return face;
        case "D" :
          return "L";
      }
  }
}

function sliceForAxis(axis) {
  switch (axis) {
    case "X" :
      return [
        "M",
        1
      ];
    case "Y" :
      return [
        "E",
        1
      ];
    case "Z" :
      return [
        "S",
        -1
      ];
  }
}

function rotationBaseDirection(_axis) {
  return -1;
}

function rotateBaseMoveOnce(move, turns, by) {
  switch (move.TAG) {
    case "FaceTurn" :
      return [
        {
          TAG: "FaceTurn",
          _0: rotateFaceOnce(by, move._0),
          _1: move._1
        },
        turns
      ];
    case "SliceTurn" :
      let sourceAxis = moveAxis(move);
      let sourceDirection;
      switch (move._0) {
        case "M" :
        case "E" :
          sourceDirection = 1;
          break;
        case "S" :
          sourceDirection = -1;
          break;
      }
      let match = rotateAxisOnce(by, sourceAxis);
      let match$1 = sliceForAxis(match[0]);
      return [
        {
          TAG: "SliceTurn",
          _0: match$1[0]
        },
        ((turns * sourceDirection | 0) * match[1] | 0) * match$1[1] | 0
      ];
    case "Rotation" :
      let match$2 = rotateAxisOnce(by, move._0);
      return [
        {
          TAG: "Rotation",
          _0: match$2[0]
        },
        ((turns * -1 | 0) * match$2[1] | 0) * -1 | 0
      ];
  }
}

function rotateUnitOnce(unit, by) {
  let text = unit.desc;
  let tmp;
  if (typeof text !== "object") {
    tmp = "Pause";
  } else {
    switch (text.TAG) {
      case "Move" :
        let match = rotateBaseMoveOnce(text._0, text._1, by);
        tmp = {
          TAG: "Move",
          _0: match[0],
          _1: match[1]
        };
        break;
      case "BlockComment" :
        tmp = {
          TAG: "BlockComment",
          _0: text._0
        };
        break;
      case "Group" :
        tmp = {
          TAG: "Group",
          _0: rotateOnce(text._0, by),
          _1: text._1
        };
        break;
      case "Commutator" :
        tmp = {
          TAG: "Commutator",
          _0: rotateOnce(text._0, by),
          _1: rotateOnce(text._1, by),
          _2: text._2
        };
        break;
      case "Conjugate" :
        tmp = {
          TAG: "Conjugate",
          _0: rotateOnce(text._0, by),
          _1: rotateOnce(text._1, by),
          _2: text._2
        };
        break;
    }
  }
  return {
    desc: tmp,
    loc: generatedLoc
  };
}

function rotateOnce(alg, by) {
  return alg.map(unit => rotateUnitOnce(unit, by));
}

function rotate(alg, axis, turns) {
  let output = alg;
  let repetitions = (turns % 4 + 4 | 0) % 4;
  for (let _for = 1; _for <= repetitions; ++_for) {
    output = rotateOnce(output, axis);
  }
  return output;
}

function practiceLength(size) {
  switch (size) {
    case 2 :
      return 11;
    case 3 :
      return 25;
    case 4 :
      return 45;
    case 5 :
      return 60;
    default:
      return 0;
  }
}

function practiceFamilies(size) {
  let outer = [
    [
      "U",
      "Y"
    ],
    [
      "R",
      "X"
    ],
    [
      "F",
      "Z"
    ],
    [
      "D",
      "Y"
    ],
    [
      "L",
      "X"
    ],
    [
      "B",
      "Z"
    ]
  ];
  if (size === 2) {
    return [
      [
        "U",
        "Y"
      ],
      [
        "R",
        "X"
      ],
      [
        "F",
        "Z"
      ]
    ];
  } else if (size === 3) {
    return outer;
  } else if (size === 4) {
    return outer.concat([
      [
        "Uw",
        "Y"
      ],
      [
        "Rw",
        "X"
      ],
      [
        "Fw",
        "Z"
      ]
    ]);
  } else {
    return outer.concat([
      [
        "Uw",
        "Y"
      ],
      [
        "Rw",
        "X"
      ],
      [
        "Fw",
        "Z"
      ],
      [
        "3Uw",
        "Y"
      ],
      [
        "3Rw",
        "X"
      ],
      [
        "3Fw",
        "Z"
      ]
    ]);
  }
}

function randomIndex(random, length) {
  let value = random();
  let bounded = value < 0.0 ? 0.0 : (
      value >= 1.0 ? 0.999999999999 : value
    );
  return Stdlib_Math.Int.floor(bounded * length);
}

function practiceScrambleWithRandom(size, random) {
  if (!StateTypes.isSupportedSize(size)) {
    return {
      TAG: "Error",
      _0: "Cube size must be between 2 and 5."
    };
  }
  let families = practiceFamilies(size);
  let suffixes = [
    "",
    "'",
    "2"
  ];
  let moves = [];
  let previousAxis = {
    contents: undefined
  };
  while (moves.length < practiceLength(size)) {
    let eligible = families.filter(param => Primitive_object.notequal(previousAxis.contents, param[1]));
    let match = eligible[randomIndex(random, eligible.length)];
    let turnSuffix = suffixes[randomIndex(random, suffixes.length)];
    moves.push(match[0] + turnSuffix);
    previousAxis.contents = match[1];
  };
  return {
    TAG: "Ok",
    _0: moves.join(" ")
  };
}

function practiceScramble(size) {
  return practiceScrambleWithRandom(size, () => Math.random());
}

export {
  generatedLoc,
  located,
  faceName,
  sliceName,
  axisName,
  suffix,
  serializeMove,
  serializeUnit,
  serialize,
  invertUnit,
  invert,
  moveAxis,
  canonicalTurns,
  flushRun,
  addToRun,
  simplify,
  mirrorFace,
  mirrorAxisFactor,
  mirrorUnit,
  mirror,
  rotateAxisOnce,
  rotateFaceOnce,
  sliceForAxis,
  rotationBaseDirection,
  rotateBaseMoveOnce,
  rotateUnitOnce,
  rotateOnce,
  rotate,
  practiceLength,
  practiceFamilies,
  randomIndex,
  practiceScrambleWithRandom,
  practiceScramble,
}
/* No side effect */
