// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function canonicalMove(token) {
  let trimmed = token.trim();
  let match = trimmed.length > 0 ? trimmed.charAt(0) : undefined;
  let face;
  if (match !== undefined) {
    switch (match) {
      case "B" :
      case "b" :
        face = "B";
        break;
      case "D" :
      case "d" :
        face = "D";
        break;
      case "F" :
      case "f" :
        face = "F";
        break;
      case "L" :
      case "l" :
        face = "L";
        break;
      case "R" :
      case "r" :
        face = "R";
        break;
      case "U" :
      case "u" :
        face = "U";
        break;
      default:
        face = undefined;
    }
  } else {
    face = undefined;
  }
  let match$1 = trimmed.length;
  if (face === undefined) {
    return trimmed;
  }
  if (match$1 === 1) {
    return face;
  }
  if (match$1 !== 2) {
    return trimmed;
  }
  let match$2 = trimmed.charAt(1);
  switch (match$2) {
    case "'" :
      return face + "'";
    case "2" :
      return face + "2";
    default:
      return trimmed;
  }
}

function isFaceLetter(character) {
  switch (character) {
    case "B" :
    case "D" :
    case "F" :
    case "L" :
    case "R" :
    case "U" :
      return true;
    default:
      return false;
  }
}

function parsedFaceTurn(token) {
  let move = canonicalMove(token);
  let face = move.length > 0 ? move.charAt(0) : "";
  if (!isFaceLetter(face)) {
    return;
  }
  let match = move.length;
  if (match === 1) {
    return [
      face,
      1
    ];
  }
  if (match !== 2) {
    return;
  }
  let match$1 = move.charAt(1);
  switch (match$1) {
    case "'" :
      return [
        face,
        3
      ];
    case "2" :
      return [
        face,
        2
      ];
    default:
      return;
  }
}

function renderedFaceTurn(face, turns) {
  let normalized = (turns % 4 + 4 | 0) % 4;
  if (normalized !== 2) {
    if (normalized !== 3) {
      return face;
    } else {
      return face + "'";
    }
  } else {
    return face + "2";
  }
}

function inverseSmartCubeMove(token) {
  let match = parsedFaceTurn(token);
  if (match !== undefined) {
    return renderedFaceTurn(match[0], (4 - match[1] | 0) % 4);
  }
}

function quarterTurnsCancel(left, right) {
  let first = canonicalMove(left);
  let second = canonicalMove(right);
  if (Primitive_object.equal(inverseSmartCubeMove(first), second)) {
    return !first.endsWith("2");
  } else {
    return false;
  }
}

function normalizeSmartCubeMoves(tokens) {
  let result = [];
  tokens.forEach(token => {
    let match = parsedFaceTurn(token);
    if (match === undefined) {
      return;
    }
    let turns = match[1];
    let face = match[0];
    let match$1 = Belt_Array.get(result, result.length - 1 | 0);
    if (match$1 !== undefined) {
      if (match$1[0] === face) {
        result.pop();
        let combined = (match$1[1] + turns | 0) % 4;
        if (combined !== 0) {
          result.push([
            face,
            combined
          ]);
          return;
        } else {
          return;
        }
      }
      result.push([
        face,
        turns
      ]);
      return;
    }
    result.push([
      face,
      turns
    ]);
  });
  return result.map(param => renderedFaceTurn(param[0], param[1]));
}

function smartCubeRecoveryMatchesExpected(state) {
  let expected = normalizeSmartCubeMoves([state.expected.token]);
  if (expected.length !== state.deviations.length) {
    return false;
  }
  let matches = true;
  for (let index = 0, index_finish = expected.length; index < index_finish; ++index) {
    if (expected[index] !== state.deviations[index]) {
      matches = false;
    }
  }
  return matches;
}

function undoSequence(deviations) {
  let result = [];
  for (let index = deviations.length - 1 | 0; index >= 0; --index) {
    let move = inverseSmartCubeMove(deviations[index]);
    if (move !== undefined) {
      result.push(move);
    }
  }
  return result;
}

function recoveryCost(deviations) {
  return Stdlib_Array.reduce(deviations, 0, (total, move) => total + (
    move.endsWith("2") ? 2 : 1
  ) | 0);
}

function beginSmartCubeRecovery(expected, received) {
  let actual = canonicalMove(received);
  let match = inverseSmartCubeMove(actual);
  if (match === undefined) {
    return;
  }
  let deviations = normalizeSmartCubeMoves([actual]);
  return {
    expected: expected,
    undoMoves: undoSequence(deviations),
    deviations: deviations
  };
}

function assessSmartCubeRecovery(state, received) {
  let actual = canonicalMove(received);
  let match = inverseSmartCubeMove(actual);
  if (match === undefined) {
    return {
      TAG: "Unsupported",
      received: actual,
      state: state
    };
  }
  let deviations = normalizeSmartCubeMoves(state.deviations.concat([actual]));
  if (deviations.length === 0) {
    return {
      TAG: "Realigned",
      received: actual
    };
  }
  let nextState_expected = state.expected;
  let nextState_undoMoves = undoSequence(deviations);
  let nextState = {
    expected: nextState_expected,
    undoMoves: nextState_undoMoves,
    deviations: deviations
  };
  if (recoveryCost(deviations) < recoveryCost(state.deviations)) {
    return {
      TAG: "Recovering",
      received: actual,
      state: nextState
    };
  } else {
    return {
      TAG: "Extended",
      received: actual,
      state: nextState
    };
  }
}

function smartCubeRecoveryPrompt(state) {
  let next = Belt_Option.getWithDefault(Belt_Array.get(state.undoMoves, 0), "");
  let later = state.undoMoves.length > 1 ? Belt_Array.sliceToEnd(state.undoMoves, 1) : [];
  let suffix = later.length !== 0 ? `, then ` + later.join(" ") : "";
  return `Slip detected: turn ` + next + suffix + ` to realign, then ` + state.expected.token + `.`;
}

export {
  canonicalMove,
  isFaceLetter,
  parsedFaceTurn,
  renderedFaceTurn,
  inverseSmartCubeMove,
  quarterTurnsCancel,
  normalizeSmartCubeMoves,
  smartCubeRecoveryMatchesExpected,
  undoSequence,
  recoveryCost,
  beginSmartCubeRecovery,
  assessSmartCubeRecovery,
  smartCubeRecoveryPrompt,
}
/* No side effect */
