// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateTypes from "../State/StateTypes.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

let body = {
  r: 0.13,
  g: 0.14,
  b: 0.17,
  a: 1.0
};

function vec(x, y, z) {
  return {
    x: x,
    y: y,
    z: z
  };
}

function add(a, b) {
  return {
    x: a.x + b.x,
    y: a.y + b.y,
    z: a.z + b.z
  };
}

function sub(a, b) {
  return {
    x: a.x - b.x,
    y: a.y - b.y,
    z: a.z - b.z
  };
}

function scale(value, amount) {
  return {
    x: value.x * amount,
    y: value.y * amount,
    z: value.z * amount
  };
}

function dot(a, b) {
  return a.x * b.x + a.y * b.y + a.z * b.z;
}

function cross(a, b) {
  return {
    x: a.y * b.z - a.z * b.y,
    y: a.z * b.x - a.x * b.z,
    z: a.x * b.y - a.y * b.x
  };
}

function normalize(value) {
  let length = Math.sqrt(dot(value, value));
  if (length < 0.000000001) {
    return {
      x: 0.0,
      y: 0.0,
      z: 0.0
    };
  } else {
    return scale(value, 1.0 / length);
  }
}

function faceNormal(face) {
  switch (face) {
    case "U" :
      return {
        x: 0.0,
        y: 1.0,
        z: 0.0
      };
    case "L" :
      return {
        x: -1.0,
        y: 0.0,
        z: 0.0
      };
    case "F" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "R" :
      return {
        x: 1.0,
        y: 0.0,
        z: 0.0
      };
    case "B" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    case "D" :
      return {
        x: 0.0,
        y: -1.0,
        z: 0.0
      };
  }
}

function rowAxis(face) {
  switch (face) {
    case "U" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "D" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    default:
      return {
        x: 0.0,
        y: -1.0,
        z: 0.0
      };
  }
}

function colAxis(face) {
  switch (face) {
    case "L" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "R" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    case "B" :
      return {
        x: -1.0,
        y: 0.0,
        z: 0.0
      };
    default:
      return {
        x: 1.0,
        y: 0.0,
        z: 0.0
      };
  }
}

function westernColour(face) {
  switch (face) {
    case "U" :
      return {
        r: 0.95,
        g: 0.95,
        b: 0.95,
        a: 1.0
      };
    case "L" :
      return {
        r: 0.94,
        g: 0.47,
        b: 0.13,
        a: 1.0
      };
    case "F" :
      return {
        r: 0.13,
        g: 0.55,
        b: 0.29,
        a: 1.0
      };
    case "R" :
      return {
        r: 0.77,
        g: 0.21,
        b: 0.18,
        a: 1.0
      };
    case "B" :
      return {
        r: 0.16,
        g: 0.35,
        b: 0.66,
        a: 1.0
      };
    case "D" :
      return {
        r: 0.96,
        g: 0.80,
        b: 0.20,
        a: 1.0
      };
  }
}

function speedColour(face) {
  switch (face) {
    case "U" :
      return {
        r: 0.96,
        g: 0.96,
        b: 0.95,
        a: 1.0
      };
    case "L" :
      return {
        r: 0.96,
        g: 0.55,
        b: 0.15,
        a: 1.0
      };
    case "F" :
      return {
        r: 0.40,
        g: 0.80,
        b: 0.34,
        a: 1.0
      };
    case "R" :
      return {
        r: 0.92,
        g: 0.30,
        b: 0.29,
        a: 1.0
      };
    case "B" :
      return {
        r: 0.28,
        g: 0.62,
        b: 0.94,
        a: 1.0
      };
    case "D" :
      return {
        r: 0.98,
        g: 0.80,
        b: 0.18,
        a: 1.0
      };
  }
}

function colourOf(style, palette, face) {
  let mapped;
  if (palette === "Western") {
    mapped = face;
  } else {
    switch (face) {
      case "F" :
        mapped = "B";
        break;
      case "B" :
        mapped = "F";
        break;
      default:
        mapped = face;
    }
  }
  if (style === "Standard") {
    return westernColour(mapped);
  } else {
    return speedColour(mapped);
  }
}

function pushVertex(emitter, position, normal, colour, sheen) {
  emitter.data.push(position.x);
  emitter.data.push(position.y);
  emitter.data.push(position.z);
  emitter.data.push(normal.x);
  emitter.data.push(normal.y);
  emitter.data.push(normal.z);
  emitter.data.push(colour.r);
  emitter.data.push(colour.g);
  emitter.data.push(colour.b);
  emitter.data.push(colour.a);
  emitter.data.push(emitter.cubie.x);
  emitter.data.push(emitter.cubie.y);
  emitter.data.push(emitter.cubie.z);
  emitter.data.push(sheen);
}

function emitTriangle(emitter, a, b, c, na, nb, nc, colour, wanted, sheenOpt) {
  let sheen = sheenOpt !== undefined ? sheenOpt : 0.0;
  let facing = cross(sub(b, a), sub(c, a));
  if (dot(facing, wanted) >= 0.0) {
    pushVertex(emitter, a, na, colour, sheen);
    pushVertex(emitter, b, nb, colour, sheen);
    return pushVertex(emitter, c, nc, colour, sheen);
  } else {
    pushVertex(emitter, a, na, colour, sheen);
    pushVertex(emitter, c, nc, colour, sheen);
    return pushVertex(emitter, b, nb, colour, sheen);
  }
}

function emitQuad(emitter, a, b, c, d, na, nb, nc, nd, colour, wanted, sheenOpt) {
  let sheen = sheenOpt !== undefined ? sheenOpt : 0.0;
  emitTriangle(emitter, a, b, c, na, nb, nc, colour, wanted, sheen);
  emitTriangle(emitter, a, c, d, na, nc, nd, colour, wanted, sheen);
}

function faceCentre(centre, face, out) {
  return add(centre, scale(faceNormal(face), out));
}

function emitFace(emitter, centre, face, out, side, colour) {
  let half = side / 2.0;
  let normal = faceNormal(face);
  let row = scale(rowAxis(face), half);
  let col = scale(colAxis(face), half);
  let middle = faceCentre(centre, face, out);
  let a = sub(sub(middle, row), col);
  let b = sub(add(middle, row), col);
  let c = add(add(middle, row), col);
  let d = add(sub(middle, row), col);
  emitQuad(emitter, a, b, c, d, normal, normal, normal, normal, colour, normal, undefined);
}

let edges = [
  [
    "U",
    "R"
  ],
  [
    "U",
    "F"
  ],
  [
    "U",
    "L"
  ],
  [
    "U",
    "B"
  ],
  [
    "D",
    "R"
  ],
  [
    "D",
    "F"
  ],
  [
    "D",
    "L"
  ],
  [
    "D",
    "B"
  ],
  [
    "R",
    "F"
  ],
  [
    "F",
    "L"
  ],
  [
    "L",
    "B"
  ],
  [
    "B",
    "R"
  ]
];

let corners = [
  [
    "U",
    "R",
    "F"
  ],
  [
    "U",
    "F",
    "L"
  ],
  [
    "U",
    "L",
    "B"
  ],
  [
    "U",
    "B",
    "R"
  ],
  [
    "D",
    "F",
    "R"
  ],
  [
    "D",
    "L",
    "F"
  ],
  [
    "D",
    "B",
    "L"
  ],
  [
    "D",
    "R",
    "B"
  ]
];

function isExposed(last, gx, gy, gz, face) {
  switch (face) {
    case "U" :
      return gy === last;
    case "L" :
      return gx === 0;
    case "F" :
      return gz === last;
    case "R" :
      return gx === last;
    case "B" :
      return gz === 0;
    case "D" :
      return gy === 0;
  }
}

function faceletAt(state, gx, gy, gz, face) {
  let last = state.size - 1 | 0;
  let match;
  switch (face) {
    case "U" :
      match = [
        gz,
        gx
      ];
      break;
    case "L" :
      match = [
        last - gy | 0,
        gz
      ];
      break;
    case "F" :
      match = [
        last - gy | 0,
        gx
      ];
      break;
    case "R" :
      match = [
        last - gy | 0,
        last - gz | 0
      ];
      break;
    case "B" :
      match = [
        last - gy | 0,
        last - gx | 0
      ];
      break;
    case "D" :
      match = [
        last - gz | 0,
        gx
      ];
      break;
  }
  let values = state.facelets[StateTypes.storageIndex(face)];
  return values[(match[0] * state.size | 0) + match[1] | 0];
}

function cubieCentre(size, gx, gy, gz) {
  let cell = 2.0 * 1.5 / size;
  let offset = (size - 1 | 0) / 2.0;
  return {
    x: (gx - offset) * cell,
    y: (gy - offset) * cell,
    z: (gz - offset) * cell
  };
}

function emitFlatBevels(emitter, centre, half, flat, colour) {
  for (let index = 0, index_finish = edges.length; index < index_finish; ++index) {
    let match = edges[index];
    let na = faceNormal(match[0]);
    let nb = faceNormal(match[1]);
    let along = cross(nb, na);
    let onA = add(scale(na, half), scale(nb, flat));
    let onB = add(scale(nb, half), scale(na, flat));
    let a = add(centre, add(onA, scale(along, - flat)));
    let b = add(centre, add(onA, scale(along, flat)));
    let c = add(centre, add(onB, scale(along, flat)));
    let d = add(centre, add(onB, scale(along, - flat)));
    let wanted = normalize(add(na, nb));
    emitQuad(emitter, a, b, c, d, na, na, nb, nb, colour, wanted, undefined);
  }
}

function emitFlatCorners(emitter, centre, half, flat, colour) {
  for (let index = 0, index_finish = corners.length; index < index_finish; ++index) {
    let match = corners[index];
    let na = faceNormal(match[0]);
    let nb = faceNormal(match[1]);
    let nc = faceNormal(match[2]);
    let a = add(centre, add(scale(na, half), add(scale(nb, flat), scale(nc, flat))));
    let b = add(centre, add(scale(nb, half), add(scale(nc, flat), scale(na, flat))));
    let c = add(centre, add(scale(nc, half), add(scale(na, flat), scale(nb, flat))));
    emitTriangle(emitter, a, b, c, na, nb, nc, colour, normalize(add(na, add(nb, nc))), undefined);
  }
}

function paintFor(state, style, palette, last, gx, gy, gz, face) {
  if (isExposed(last, gx, gy, gz, face)) {
    return colourOf(style, palette, faceletAt(state, gx, gy, gz, face));
  } else {
    return body;
  }
}

function roundedRim(half, radius, steps) {
  let points = [];
  let flat = half - radius;
  for (let quarter = 0; quarter <= 3; ++quarter) {
    let hubU = quarter === 0 || quarter === 3 ? flat : - flat;
    let hubV = quarter <= 1 ? flat : - flat;
    for (let step = 0; step < steps; ++step) {
      let angle = (quarter + step / steps) * Math.PI / 2.0;
      let nu = Math.cos(angle);
      let nv = Math.sin(angle);
      points.push({
        u: hubU + radius * nu,
        v: hubV + radius * nv,
        nu: nu,
        nv: nv
      });
    }
  }
  return points;
}

function pointOnFace(centre, face, out, point) {
  return add(faceCentre(centre, face, out), add(scale(colAxis(face), point.u), scale(rowAxis(face), point.v)));
}

function emitRoundedFace(emitter, centre, face, out, side, radius, colour) {
  let normal = faceNormal(face);
  let middle = faceCentre(centre, face, out);
  let rim = roundedRim(side / 2.0, radius, 4);
  for (let index = 0, index_finish = rim.length; index < index_finish; ++index) {
    let next = Primitive_int.mod_(index + 1 | 0, rim.length);
    emitTriangle(emitter, middle, pointOnFace(centre, face, out, rim[index]), pointOnFace(centre, face, out, rim[next]), normal, normal, normal, colour, normal, undefined);
  }
}

function faceForNormal(normal) {
  if (normal.y > 0.5) {
    return "U";
  } else if (normal.y < -0.5) {
    return "D";
  } else if (normal.z > 0.5) {
    return "F";
  } else if (normal.z < -0.5) {
    return "B";
  } else if (normal.x > 0.5) {
    return "R";
  } else {
    return "L";
  }
}

function isOuterEdge(last, gx, gy, gz, faceA, faceB) {
  if (isExposed(last, gx, gy, gz, faceA)) {
    return isExposed(last, gx, gy, gz, faceB);
  } else {
    return false;
  }
}

function bevelForEdge(last, gx, gy, gz, cell, faceA, faceB) {
  if (isOuterEdge(last, gx, gy, gz, faceA, faceB)) {
    return 0.065 * cell;
  } else {
    return 0.03 * cell;
  }
}

function emitStandardFace(emitter, centre, face, half, colour, bevelFor) {
  let normal = faceNormal(face);
  let row = rowAxis(face);
  let col = colAxis(face);
  let middle = faceCentre(centre, face, half);
  let fColPlus = faceForNormal(col);
  let fColMinus = faceForNormal(scale(col, -1.0));
  let fRowPlus = faceForNormal(row);
  let fRowMinus = faceForNormal(scale(row, -1.0));
  let flatColPlus = half - bevelFor(face, fColPlus);
  let flatColMinus = half - bevelFor(face, fColMinus);
  let flatRowPlus = half - bevelFor(face, fRowPlus);
  let flatRowMinus = half - bevelFor(face, fRowMinus);
  let a = sub(sub(middle, scale(row, flatRowMinus)), scale(col, flatColMinus));
  let b = sub(add(middle, scale(row, flatRowPlus)), scale(col, flatColMinus));
  let c = add(add(middle, scale(row, flatRowPlus)), scale(col, flatColPlus));
  let d = add(sub(middle, scale(row, flatRowMinus)), scale(col, flatColPlus));
  emitQuad(emitter, a, b, c, d, normal, normal, normal, normal, colour, normal, undefined);
}

function emitStandardBevels(emitter, centre, half, colour, bevelFor) {
  for (let index = 0, index_finish = edges.length; index < index_finish; ++index) {
    let match = edges[index];
    let faceB = match[1];
    let faceA = match[0];
    let na = faceNormal(faceA);
    let nb = faceNormal(faceB);
    let along = cross(nb, na);
    let faceMinus = faceForNormal(scale(along, -1.0));
    let facePlus = faceForNormal(along);
    let bevelAB = bevelFor(faceA, faceB);
    let flatAB = half - bevelAB;
    let flatMinusA = half - bevelFor(faceA, faceMinus);
    let flatPlusA = half - bevelFor(faceA, facePlus);
    let flatMinusB = half - bevelFor(faceB, faceMinus);
    let flatPlusB = half - bevelFor(faceB, facePlus);
    let onA = add(scale(na, half), scale(nb, flatAB));
    let onB = add(scale(nb, half), scale(na, flatAB));
    let a = add(centre, add(onA, scale(along, - flatMinusA)));
    let b = add(centre, add(onA, scale(along, flatPlusA)));
    let c = add(centre, add(onB, scale(along, flatPlusB)));
    let d = add(centre, add(onB, scale(along, - flatMinusB)));
    let wanted = normalize(add(na, nb));
    emitQuad(emitter, a, b, c, d, na, na, nb, nb, colour, wanted, undefined);
  }
}

function emitStandardCorners(emitter, centre, half, colour, bevelFor) {
  for (let index = 0, index_finish = corners.length; index < index_finish; ++index) {
    let match = corners[index];
    let faceC = match[2];
    let faceB = match[1];
    let faceA = match[0];
    let na = faceNormal(faceA);
    let nb = faceNormal(faceB);
    let nc = faceNormal(faceC);
    let flatAB = half - bevelFor(faceA, faceB);
    let flatAC = half - bevelFor(faceA, faceC);
    let flatBC = half - bevelFor(faceB, faceC);
    let a = add(centre, add(scale(na, half), add(scale(nb, flatAB), scale(nc, flatAC))));
    let b = add(centre, add(scale(nb, half), add(scale(nc, flatBC), scale(na, flatAB))));
    let c = add(centre, add(scale(nc, half), add(scale(na, flatAC), scale(nb, flatBC))));
    emitTriangle(emitter, a, b, c, na, nb, nc, colour, normalize(add(na, add(nb, nc))), undefined);
  }
}

function emitStandardCubie(data, state, palette, gx, gy, gz) {
  let size = state.size;
  let last = size - 1 | 0;
  let cell = 2.0 * 1.5 / size;
  let centre = cubieCentre(size, gx, gy, gz);
  let emitter = {
    data: data,
    cubie: centre
  };
  let half = 0.999 * cell / 2.0;
  let bevelFor = (fA, fB) => bevelForEdge(last, gx, gy, gz, cell, fA, fB);
  StateTypes.storageOrder.forEach(face => emitStandardFace(emitter, centre, face, half, body, bevelFor));
  emitStandardBevels(emitter, centre, half, body, bevelFor);
  emitStandardCorners(emitter, centre, half, body, bevelFor);
  StateTypes.storageOrder.forEach(face => {
    if (!isExposed(last, gx, gy, gz, face)) {
      return;
    }
    let colour = colourOf("Standard", palette, faceletAt(state, gx, gy, gz, face));
    let side = 0.84 * cell;
    emitRoundedFace(emitter, centre, face, half + 0.005 * cell, side, 0.08 * side, colour);
  });
}

function emitSpeedCubie(data, state, palette, gx, gy, gz) {
  let size = state.size;
  let last = size - 1 | 0;
  let cell = 2.0 * 1.5 / size;
  let centre = cubieCentre(size, gx, gy, gz);
  let emitter = {
    data: data,
    cubie: centre
  };
  let half = 0.999 * cell / 2.0;
  let bevel = 0.06 * cell;
  let flat = half - bevel;
  StateTypes.storageOrder.forEach(face => {
    let colour = paintFor(state, "Speed", palette, last, gx, gy, gz, face);
    emitFace(emitter, centre, face, half, 2.0 * flat, colour);
  });
  for (let index = 0, index_finish = edges.length; index < index_finish; ++index) {
    let match = edges[index];
    let faceB = match[1];
    let faceA = match[0];
    let na = faceNormal(faceA);
    let nb = faceNormal(faceB);
    let along = cross(nb, na);
    let facing = normalize(add(na, nb));
    let onA = add(scale(na, half), scale(nb, flat));
    let onB = add(scale(nb, half), scale(na, flat));
    let middle = scale(add(onA, onB), 0.5);
    let corner = (way, out) => add(centre, add(scale(along, way * flat), out));
    let colorA = paintFor(state, "Speed", palette, last, gx, gy, gz, faceA);
    let colorB = paintFor(state, "Speed", palette, last, gx, gy, gz, faceB);
    emitQuad(emitter, corner(-1.0, onA), corner(1.0, onA), corner(1.0, middle), corner(-1.0, middle), na, na, facing, facing, colorA, facing, 0.22);
    emitQuad(emitter, corner(-1.0, middle), corner(1.0, middle), corner(1.0, onB), corner(-1.0, onB), facing, facing, nb, nb, colorB, facing, 0.22);
  }
  let between = (p1, p2) => scale(add(p1, p2), 0.5);
  for (let index$1 = 0, index_finish$1 = corners.length; index$1 < index_finish$1; ++index$1) {
    let match$1 = corners[index$1];
    let three = match$1[2];
    let two = match$1[1];
    let one = match$1[0];
    let n1 = faceNormal(one);
    let n2 = faceNormal(two);
    let n3 = faceNormal(three);
    let turned = dot(cross(n1, n2), n3);
    let match$2 = turned > 0.0 ? [
        one,
        two,
        three
      ] : [
        one,
        three,
        two
      ];
    let faceC = match$2[2];
    let faceB$1 = match$2[1];
    let faceA$1 = match$2[0];
    let na$1 = faceNormal(faceA$1);
    let nb$1 = faceNormal(faceB$1);
    let nc = faceNormal(faceC);
    let facing$1 = normalize(add(na$1, add(nb$1, nc)));
    let onCap = (out, first, second) => add(centre, add(scale(out, half), add(scale(first, flat), scale(second, flat))));
    let pa = onCap(na$1, nb$1, nc);
    let pb = onCap(nb$1, nc, na$1);
    let pc = onCap(nc, na$1, nb$1);
    let mid = scale(add(pa, add(pb, pc)), 1.0 / 3.0);
    let colorA$1 = paintFor(state, "Speed", palette, last, gx, gy, gz, faceA$1);
    let colorB$1 = paintFor(state, "Speed", palette, last, gx, gy, gz, faceB$1);
    let colorC = paintFor(state, "Speed", palette, last, gx, gy, gz, faceC);
    emitQuad(emitter, pa, between(pa, pb), mid, between(pc, pa), na$1, normalize(add(na$1, nb$1)), facing$1, normalize(add(nc, na$1)), colorA$1, facing$1, 0.22);
    emitQuad(emitter, pb, between(pb, pc), mid, between(pa, pb), nb$1, normalize(add(nb$1, nc)), facing$1, normalize(add(na$1, nb$1)), colorB$1, facing$1, 0.22);
    emitQuad(emitter, pc, between(pc, pa), mid, between(pb, pc), nc, normalize(add(nc, na$1)), facing$1, normalize(add(nb$1, nc)), colorC, facing$1, 0.22);
  }
}

function validate(state) {
  if (StateTypes.isSupportedSize(state.size)) {
    if (state.facelets.length !== 6) {
      return {
        TAG: "Error",
        _0: "A cube state must contain six faces."
      };
    } else if (state.facelets.some(values => values.length !== (state.size * state.size | 0))) {
      return {
        TAG: "Error",
        _0: "Every face must contain size² stickers."
      };
    } else {
      return {
        TAG: "Ok",
        _0: undefined
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: "Cube size must be between 2 and 5."
    };
  }
}

function generate(state, style, palette) {
  let message = validate(state);
  if (message.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: message._0
    };
  }
  let data = [];
  let last = state.size - 1 | 0;
  for (let gx = 0; gx <= last; ++gx) {
    for (let gy = 0; gy <= last; ++gy) {
      for (let gz = 0; gz <= last; ++gz) {
        if (gx === 0 || gx === last || gy === 0 || gy === last || gz === 0 || gz === last) {
          if (style === "Standard") {
            emitStandardCubie(data, state, palette, gx, gy, gz);
          } else {
            emitSpeedCubie(data, state, palette, gx, gy, gz);
          }
        }
      }
    }
  }
  return {
    TAG: "Ok",
    _0: {
      data: data,
      vertexCount: data.length / 14 | 0,
      stride: 14
    }
  };
}

let stride = 14;

let halfExtent = 1.5;

export {
  stride,
  halfExtent,
  body,
  vec,
  add,
  sub,
  scale,
  dot,
  cross,
  normalize,
  faceNormal,
  rowAxis,
  colAxis,
  westernColour,
  speedColour,
  colourOf,
  pushVertex,
  emitTriangle,
  emitQuad,
  faceCentre,
  emitFace,
  edges,
  corners,
  isExposed,
  faceletAt,
  cubieCentre,
  emitFlatBevels,
  emitFlatCorners,
  paintFor,
  roundedRim,
  pointOnFace,
  emitRoundedFace,
  faceForNormal,
  isOuterEdge,
  bevelForEdge,
  emitStandardFace,
  emitStandardBevels,
  emitStandardCorners,
  emitStandardCubie,
  emitSpeedCubie,
  validate,
  generate,
}
/* No side effect */
