// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateTypes from "../State/StateTypes.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

let body = {
  r: 0.13,
  g: 0.14,
  b: 0.17,
  a: 1.0
};

function vec(x, y, z) {
  return {
    x: x,
    y: y,
    z: z
  };
}

function add(a, b) {
  return {
    x: a.x + b.x,
    y: a.y + b.y,
    z: a.z + b.z
  };
}

function sub(a, b) {
  return {
    x: a.x - b.x,
    y: a.y - b.y,
    z: a.z - b.z
  };
}

function scale(value, amount) {
  return {
    x: value.x * amount,
    y: value.y * amount,
    z: value.z * amount
  };
}

function dot(a, b) {
  return a.x * b.x + a.y * b.y + a.z * b.z;
}

function cross(a, b) {
  return {
    x: a.y * b.z - a.z * b.y,
    y: a.z * b.x - a.x * b.z,
    z: a.x * b.y - a.y * b.x
  };
}

function normalize(value) {
  let length = Math.sqrt(dot(value, value));
  if (length < 0.000000001) {
    return {
      x: 0.0,
      y: 0.0,
      z: 0.0
    };
  } else {
    return scale(value, 1.0 / length);
  }
}

function faceNormal(face) {
  switch (face) {
    case "U" :
      return {
        x: 0.0,
        y: 1.0,
        z: 0.0
      };
    case "L" :
      return {
        x: -1.0,
        y: 0.0,
        z: 0.0
      };
    case "F" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "R" :
      return {
        x: 1.0,
        y: 0.0,
        z: 0.0
      };
    case "B" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    case "D" :
      return {
        x: 0.0,
        y: -1.0,
        z: 0.0
      };
  }
}

function rowAxis(face) {
  switch (face) {
    case "U" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "D" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    default:
      return {
        x: 0.0,
        y: -1.0,
        z: 0.0
      };
  }
}

function colAxis(face) {
  switch (face) {
    case "L" :
      return {
        x: 0.0,
        y: 0.0,
        z: 1.0
      };
    case "R" :
      return {
        x: 0.0,
        y: 0.0,
        z: -1.0
      };
    case "B" :
      return {
        x: -1.0,
        y: 0.0,
        z: 0.0
      };
    default:
      return {
        x: 1.0,
        y: 0.0,
        z: 0.0
      };
  }
}

function westernColour(face) {
  switch (face) {
    case "U" :
      return {
        r: 0.95,
        g: 0.95,
        b: 0.95,
        a: 1.0
      };
    case "L" :
      return {
        r: 0.94,
        g: 0.47,
        b: 0.13,
        a: 1.0
      };
    case "F" :
      return {
        r: 0.13,
        g: 0.55,
        b: 0.29,
        a: 1.0
      };
    case "R" :
      return {
        r: 0.77,
        g: 0.21,
        b: 0.18,
        a: 1.0
      };
    case "B" :
      return {
        r: 0.16,
        g: 0.35,
        b: 0.66,
        a: 1.0
      };
    case "D" :
      return {
        r: 0.96,
        g: 0.80,
        b: 0.20,
        a: 1.0
      };
  }
}

function speedColour(face) {
  switch (face) {
    case "U" :
      return {
        r: 0.96,
        g: 0.96,
        b: 0.95,
        a: 1.0
      };
    case "L" :
      return {
        r: 0.96,
        g: 0.55,
        b: 0.15,
        a: 1.0
      };
    case "F" :
      return {
        r: 0.40,
        g: 0.80,
        b: 0.34,
        a: 1.0
      };
    case "R" :
      return {
        r: 0.92,
        g: 0.30,
        b: 0.29,
        a: 1.0
      };
    case "B" :
      return {
        r: 0.28,
        g: 0.62,
        b: 0.94,
        a: 1.0
      };
    case "D" :
      return {
        r: 0.98,
        g: 0.80,
        b: 0.18,
        a: 1.0
      };
  }
}

function colourOf(style, palette, face) {
  let mapped;
  if (palette === "Western") {
    mapped = face;
  } else {
    switch (face) {
      case "F" :
        mapped = "B";
        break;
      case "B" :
        mapped = "F";
        break;
      default:
        mapped = face;
    }
  }
  if (style === "Standard") {
    return westernColour(mapped);
  } else {
    return speedColour(mapped);
  }
}

function pushVertex(emitter, position, normal, colour, sheen) {
  emitter.data.push(position.x);
  emitter.data.push(position.y);
  emitter.data.push(position.z);
  emitter.data.push(normal.x);
  emitter.data.push(normal.y);
  emitter.data.push(normal.z);
  emitter.data.push(colour.r);
  emitter.data.push(colour.g);
  emitter.data.push(colour.b);
  emitter.data.push(colour.a);
  emitter.data.push(emitter.cubie.x);
  emitter.data.push(emitter.cubie.y);
  emitter.data.push(emitter.cubie.z);
  emitter.data.push(sheen);
}

function emitTriangle(emitter, a, b, c, na, nb, nc, colour, wanted, sheenOpt) {
  let sheen = sheenOpt !== undefined ? sheenOpt : 0.0;
  let facing = cross(sub(b, a), sub(c, a));
  if (dot(facing, wanted) >= 0.0) {
    pushVertex(emitter, a, na, colour, sheen);
    pushVertex(emitter, b, nb, colour, sheen);
    return pushVertex(emitter, c, nc, colour, sheen);
  } else {
    pushVertex(emitter, a, na, colour, sheen);
    pushVertex(emitter, c, nc, colour, sheen);
    return pushVertex(emitter, b, nb, colour, sheen);
  }
}

function emitQuad(emitter, a, b, c, d, na, nb, nc, nd, colour, wanted, sheenOpt) {
  let sheen = sheenOpt !== undefined ? sheenOpt : 0.0;
  emitTriangle(emitter, a, b, c, na, nb, nc, colour, wanted, sheen);
  emitTriangle(emitter, a, c, d, na, nc, nd, colour, wanted, sheen);
}

function faceCentre(centre, face, out) {
  return add(centre, scale(faceNormal(face), out));
}

function emitFace(emitter, centre, face, out, side, colour) {
  let half = side / 2.0;
  let normal = faceNormal(face);
  let row = scale(rowAxis(face), half);
  let col = scale(colAxis(face), half);
  let middle = faceCentre(centre, face, out);
  let a = sub(sub(middle, row), col);
  let b = sub(add(middle, row), col);
  let c = add(add(middle, row), col);
  let d = add(sub(middle, row), col);
  emitQuad(emitter, a, b, c, d, normal, normal, normal, normal, colour, normal, undefined);
}

let edges = [
  [
    "U",
    "R"
  ],
  [
    "U",
    "F"
  ],
  [
    "U",
    "L"
  ],
  [
    "U",
    "B"
  ],
  [
    "D",
    "R"
  ],
  [
    "D",
    "F"
  ],
  [
    "D",
    "L"
  ],
  [
    "D",
    "B"
  ],
  [
    "R",
    "F"
  ],
  [
    "F",
    "L"
  ],
  [
    "L",
    "B"
  ],
  [
    "B",
    "R"
  ]
];

let corners = [
  [
    "U",
    "R",
    "F"
  ],
  [
    "U",
    "F",
    "L"
  ],
  [
    "U",
    "L",
    "B"
  ],
  [
    "U",
    "B",
    "R"
  ],
  [
    "D",
    "F",
    "R"
  ],
  [
    "D",
    "L",
    "F"
  ],
  [
    "D",
    "B",
    "L"
  ],
  [
    "D",
    "R",
    "B"
  ]
];

function isExposed(last, gx, gy, gz, face) {
  switch (face) {
    case "U" :
      return gy === last;
    case "L" :
      return gx === 0;
    case "F" :
      return gz === last;
    case "R" :
      return gx === last;
    case "B" :
      return gz === 0;
    case "D" :
      return gy === 0;
  }
}

function faceletAt(state, gx, gy, gz, face) {
  let last = state.size - 1 | 0;
  let match;
  switch (face) {
    case "U" :
      match = [
        gz,
        gx
      ];
      break;
    case "L" :
      match = [
        last - gy | 0,
        gz
      ];
      break;
    case "F" :
      match = [
        last - gy | 0,
        gx
      ];
      break;
    case "R" :
      match = [
        last - gy | 0,
        last - gz | 0
      ];
      break;
    case "B" :
      match = [
        last - gy | 0,
        last - gx | 0
      ];
      break;
    case "D" :
      match = [
        last - gz | 0,
        gx
      ];
      break;
  }
  let values = state.facelets[StateTypes.storageIndex(face)];
  return values[(match[0] * state.size | 0) + match[1] | 0];
}

function cubieCentre(size, gx, gy, gz) {
  let cell = 2.0 * 1.5 / size;
  let offset = (size - 1 | 0) / 2.0;
  return {
    x: (gx - offset) * cell,
    y: (gy - offset) * cell,
    z: (gz - offset) * cell
  };
}

function emitFlatBevels(emitter, centre, half, flat, colour) {
  for (let index = 0, index_finish = edges.length; index < index_finish; ++index) {
    let match = edges[index];
    let na = faceNormal(match[0]);
    let nb = faceNormal(match[1]);
    let along = cross(nb, na);
    let onA = add(scale(na, half), scale(nb, flat));
    let onB = add(scale(nb, half), scale(na, flat));
    let a = add(centre, add(onA, scale(along, - flat)));
    let b = add(centre, add(onA, scale(along, flat)));
    let c = add(centre, add(onB, scale(along, flat)));
    let d = add(centre, add(onB, scale(along, - flat)));
    let wanted = normalize(add(na, nb));
    emitQuad(emitter, a, b, c, d, na, na, nb, nb, colour, wanted, undefined);
  }
}

function emitFlatCorners(emitter, centre, half, flat, colour) {
  for (let index = 0, index_finish = corners.length; index < index_finish; ++index) {
    let match = corners[index];
    let na = faceNormal(match[0]);
    let nb = faceNormal(match[1]);
    let nc = faceNormal(match[2]);
    let a = add(centre, add(scale(na, half), add(scale(nb, flat), scale(nc, flat))));
    let b = add(centre, add(scale(nb, half), add(scale(nc, flat), scale(na, flat))));
    let c = add(centre, add(scale(nc, half), add(scale(na, flat), scale(nb, flat))));
    emitTriangle(emitter, a, b, c, na, nb, nc, colour, normalize(add(na, add(nb, nc))), undefined);
  }
}

function paintFor(state, style, palette, last, gx, gy, gz, face) {
  if (isExposed(last, gx, gy, gz, face)) {
    return colourOf(style, palette, faceletAt(state, gx, gy, gz, face));
  } else {
    return body;
  }
}

function roundedRim(half, radius, steps) {
  let points = [];
  let flat = half - radius;
  for (let quarter = 0; quarter <= 3; ++quarter) {
    let hubU = quarter === 0 || quarter === 3 ? flat : - flat;
    let hubV = quarter <= 1 ? flat : - flat;
    for (let step = 0; step < steps; ++step) {
      let angle = (quarter + step / steps) * Math.PI / 2.0;
      let nu = Math.cos(angle);
      let nv = Math.sin(angle);
      points.push({
        u: hubU + radius * nu,
        v: hubV + radius * nv,
        nu: nu,
        nv: nv
      });
    }
  }
  return points;
}

function pointOnFace(centre, face, out, point) {
  return add(faceCentre(centre, face, out), add(scale(colAxis(face), point.u), scale(rowAxis(face), point.v)));
}

function emitRoundedFace(emitter, centre, face, out, side, radius, colour) {
  let normal = faceNormal(face);
  let middle = faceCentre(centre, face, out);
  let rim = roundedRim(side / 2.0, radius, 4);
  for (let index = 0, index_finish = rim.length; index < index_finish; ++index) {
    let next = Primitive_int.mod_(index + 1 | 0, rim.length);
    emitTriangle(emitter, middle, pointOnFace(centre, face, out, rim[index]), pointOnFace(centre, face, out, rim[next]), normal, normal, normal, colour, normal, undefined);
  }
}

function emitPillowedFace(emitter, centre, face, half, bevel, radius, colour) {
  let normal = faceNormal(face);
  let innerHalf = half - bevel;
  let rim = roundedRim(innerHalf, Math.min(radius, innerHalf * 0.45), 4);
  let middle = faceCentre(centre, face, half);
  let positionAt = (point, progress) => {
    let largest = Math.max(Math.abs(point.u), Math.abs(point.v));
    let outerScale = largest < 0.000001 ? 1.0 : half / largest;
    let blend = Math.sin(progress * Math.PI / 2.0);
    let expanded = 1.0 + (outerScale - 1.0) * blend;
    let out = half - bevel * (1.0 - Math.cos(progress * Math.PI / 2.0));
    return pointOnFace(centre, face, out, {
      u: point.u * expanded,
      v: point.v * expanded,
      nu: point.nu,
      nv: point.nv
    });
  };
  let normalAt = (point, progress) => {
    let angle = progress * Math.PI / 2.0;
    let outward = add(scale(colAxis(face), point.nu), scale(rowAxis(face), point.nv));
    return normalize(add(scale(normal, Math.cos(angle)), scale(outward, Math.sin(angle))));
  };
  for (let index = 0, index_finish = rim.length; index < index_finish; ++index) {
    let next = Primitive_int.mod_(index + 1 | 0, rim.length);
    let here = rim[index];
    let there = rim[next];
    emitTriangle(emitter, middle, positionAt(here, 0.0), positionAt(there, 0.0), normal, normal, normal, colour, normal, undefined);
  }
  for (let band = 0; band <= 2; ++band) {
    let first = band / 3;
    let second = (band + 1 | 0) / 3;
    let sheen = 0.22 * Math.sin((first + second) / 2.0 * Math.PI);
    for (let index$1 = 0, index_finish$1 = rim.length; index$1 < index_finish$1; ++index$1) {
      let next$1 = Primitive_int.mod_(index$1 + 1 | 0, rim.length);
      let here$1 = rim[index$1];
      let there$1 = rim[next$1];
      emitQuad(emitter, positionAt(here$1, first), positionAt(here$1, second), positionAt(there$1, second), positionAt(there$1, first), normalAt(here$1, first), normalAt(here$1, second), normalAt(there$1, second), normalAt(there$1, first), colour, normalize(add(normalAt(here$1, first), normalAt(there$1, second))), sheen);
    }
  }
}

function emitStandardCubie(data, state, palette, gx, gy, gz) {
  let size = state.size;
  let cell = 2.0 * 1.5 / size;
  let centre = cubieCentre(size, gx, gy, gz);
  let emitter = {
    data: data,
    cubie: centre
  };
  let half = 0.999 * cell / 2.0;
  let bevel = 0.03 * cell;
  let flat = half - bevel;
  StateTypes.storageOrder.forEach(face => emitFace(emitter, centre, face, half, 2.0 * flat, body));
  emitFlatBevels(emitter, centre, half, flat, body);
  emitFlatCorners(emitter, centre, half, flat, body);
  let last = size - 1 | 0;
  StateTypes.storageOrder.forEach(face => {
    if (!isExposed(last, gx, gy, gz, face)) {
      return;
    }
    let colour = colourOf("Standard", palette, faceletAt(state, gx, gy, gz, face));
    let side = 0.84 * cell;
    emitRoundedFace(emitter, centre, face, half + 0.005 * cell, side, 0.05 * side, colour);
  });
}

function emitSpeedCubie(data, state, palette, gx, gy, gz) {
  let size = state.size;
  let last = size - 1 | 0;
  let cell = 2.0 * 1.5 / size;
  let centre = cubieCentre(size, gx, gy, gz);
  let emitter = {
    data: data,
    cubie: centre
  };
  let half = 0.999 * cell / 2.0;
  let bevel = 0.06 * cell;
  let flat = half - bevel;
  StateTypes.storageOrder.forEach(face => emitFace(emitter, centre, face, flat, 2.0 * flat, body));
  StateTypes.storageOrder.forEach(face => {
    if (isExposed(last, gx, gy, gz, face)) {
      return emitPillowedFace(emitter, centre, face, half, bevel, 0.12 * cell, paintFor(state, "Speed", palette, last, gx, gy, gz, face));
    }
  });
}

function validate(state) {
  if (StateTypes.isSupportedSize(state.size)) {
    if (state.facelets.length !== 6) {
      return {
        TAG: "Error",
        _0: "A cube state must contain six faces."
      };
    } else if (state.facelets.some(values => values.length !== (state.size * state.size | 0))) {
      return {
        TAG: "Error",
        _0: "Every face must contain size² stickers."
      };
    } else {
      return {
        TAG: "Ok",
        _0: undefined
      };
    }
  } else {
    return {
      TAG: "Error",
      _0: "Cube size must be between 2 and 5."
    };
  }
}

function generate(state, style, palette) {
  let message = validate(state);
  if (message.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: message._0
    };
  }
  let data = [];
  let last = state.size - 1 | 0;
  for (let gx = 0; gx <= last; ++gx) {
    for (let gy = 0; gy <= last; ++gy) {
      for (let gz = 0; gz <= last; ++gz) {
        if (gx === 0 || gx === last || gy === 0 || gy === last || gz === 0 || gz === last) {
          if (style === "Standard") {
            emitStandardCubie(data, state, palette, gx, gy, gz);
          } else {
            emitSpeedCubie(data, state, palette, gx, gy, gz);
          }
        }
      }
    }
  }
  return {
    TAG: "Ok",
    _0: {
      data: data,
      vertexCount: data.length / 14 | 0,
      stride: 14
    }
  };
}

let stride = 14;

let halfExtent = 1.5;

export {
  stride,
  halfExtent,
  body,
  vec,
  add,
  sub,
  scale,
  dot,
  cross,
  normalize,
  faceNormal,
  rowAxis,
  colAxis,
  westernColour,
  speedColour,
  colourOf,
  pushVertex,
  emitTriangle,
  emitQuad,
  faceCentre,
  emitFace,
  edges,
  corners,
  isExposed,
  faceletAt,
  cubieCentre,
  emitFlatBevels,
  emitFlatCorners,
  paintFor,
  roundedRim,
  pointOnFace,
  emitRoundedFace,
  emitPillowedFace,
  emitStandardCubie,
  emitSpeedCubie,
  validate,
  generate,
}
/* No side effect */
