// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as MoveTransform from "../Move/MoveTransform.res.mjs";
import * as BeginnerSolver from "./BeginnerSolver.res.mjs";

let allCorners = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7
];

let allEdges = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11
];

function shorten(solved, target, currentMoveCount, maxNodesOpt, maxDepthOpt) {
  let maxNodes = maxNodesOpt !== undefined ? maxNodesOpt : 1500000;
  let maxDepth = maxDepthOpt !== undefined ? maxDepthOpt : 10;
  if (currentMoveCount <= 1) {
    return {
      TAG: "Ok",
      _0: "NoShorterFound"
    };
  }
  let error = PieceReducer.reduce(solved);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let actions = BeginnerSolver.atomicActions(solved);
  let match = BeginnerSolver.atomicDistanceTables(allCorners, allEdges, actions);
  let edgeTables = match[1];
  let cornerTables = match[0];
  let solvedKey = BeginnerSolver.fullKey(error._0);
  let searchDepth = (currentMoveCount - 1 | 0) < maxDepth ? currentMoveCount - 1 | 0 : maxDepth;
  if (BeginnerSolver.fullKey(target) === solvedKey) {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Shortened",
        alg: [],
        moveCount: 0
      }
    };
  }
  let nodes = {
    contents: 0
  };
  let exceeded = {
    contents: false
  };
  let dfs = (current, remaining, previousFace, previousAxis, path, seen) => {
    if (exceeded.contents) {
      return;
    }
    nodes.contents = nodes.contents + 1 | 0;
    if (nodes.contents > maxNodes) {
      exceeded.contents = true;
      return;
    }
    if (BeginnerSolver.atomicDistanceLowerBound(current, cornerTables, edgeTables) > remaining) {
      return;
    }
    if (remaining === 0) {
      if (BeginnerSolver.fullKey(current) === solvedKey) {
        return path.map(value => value);
      } else {
        return;
      }
    }
    let key = BeginnerSolver.fullKey(current) + "|" + previousFace.toString() + ":" + previousAxis.toString();
    let depth = seen[key];
    let alreadySeen = depth !== undefined ? depth >= remaining : false;
    if (alreadySeen) {
      return;
    }
    seen[key] = remaining;
    let found;
    for (let index = 0, index_finish = actions.length; index < index_finish; ++index) {
      let action = actions[index];
      let sameFace = action.faceIndex === previousFace;
      let reorderedOpposite = action.axisIndex === previousAxis && action.faceIndex < previousFace;
      if (found === undefined && !sameFace && !reorderedOpposite) {
        path.push(action);
        found = dfs(BeginnerSolver.applyCubie(current, action.transition), remaining - 1 | 0, action.faceIndex, action.axisIndex, path, seen);
        path.pop();
      }
    }
    return found;
  };
  let found;
  let depth = 1;
  while (found === undefined && depth <= searchDepth && !exceeded.contents) {
    found = dfs(target, depth, -1, -1, [], {});
    depth = depth + 1 | 0;
  };
  let path = found;
  if (path === undefined) {
    return {
      TAG: "Ok",
      _0: exceeded.contents ? "SearchTooExpensive" : "NoShorterFound"
    };
  }
  let alg = [];
  for (let index = path.length - 1 | 0; index >= 0; --index) {
    let action = path[index];
    alg = alg.concat(MoveTransform.invert(action.alg));
  }
  return {
    TAG: "Ok",
    _0: {
      TAG: "Shortened",
      alg: alg,
      moveCount: path.length
    }
  };
}

let defaultMaxNodes = 1500000;

let defaultMaxDepth = 10;

export {
  allCorners,
  allEdges,
  defaultMaxNodes,
  defaultMaxDepth,
  shorten,
}
/* No side effect */
