// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as MoveTransform from "../Move/MoveTransform.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let atomicHeuristicCache = {};

let BuildFailure = /* @__PURE__ */Primitive_exceptions.create("BeginnerSolver.BuildFailure");

let generatedLoc = {
  start: 0,
  end_: 0
};

function located(desc) {
  return {
    desc: desc,
    loc: generatedLoc
  };
}

let outerRange = {
  from_: 1,
  to_: 1
};

function describeError(error) {
  if (typeof error !== "object") {
    return "The generated tutorial failed exact facelet replay verification. The input state was left unchanged.";
  }
  switch (error.TAG) {
    case "UnsupportedSize" :
      let size = error._0;
      return `The beginner tutorial solver supports 3×3×3, not ` + size.toString() + `×` + size.toString() + `×` + size.toString() + `.`;
    case "InvalidState" :
      return PieceReducer.describeError(error._0);
    case "SearchFailed" :
      return `The bounded beginner-method search could not complete ` + error._0 + `. The input state was left unchanged.`;
    case "ExpansionFailed" :
      let message = error._0;
      if (message.TAG === "InvalidState") {
        return message._0;
      } else {
        return `The generated tutorial exceeded the ` + message._0.toString() + `-move safety limit.`;
      }
  }
}

function concatAlg(left, right) {
  return left.concat(right);
}

function groupedSequence(alg) {
  if (alg.length === 0) {
    return [];
  } else {
    return [
      {
        desc: {
          TAG: "Group",
          _0: alg,
          _1: 1
        },
        loc: generatedLoc
      },
      {
        desc: {
          TAG: "TimedPause",
          _0: 0.5
        },
        loc: generatedLoc
      }
    ];
  }
}

function faceIndex(face) {
  switch (face) {
    case "U" :
      return 0;
    case "L" :
      return 3;
    case "F" :
      return 4;
    case "R" :
      return 2;
    case "B" :
      return 5;
    case "D" :
      return 1;
  }
}

function axisIndex(face) {
  switch (face) {
    case "L" :
    case "R" :
      return 1;
    case "F" :
    case "B" :
      return 2;
    case "U" :
    case "D" :
      return 0;
  }
}

function applyCubie(state, transition) {
  let cp = Stdlib_Array.make(8, 0);
  let co = Stdlib_Array.make(8, 0);
  let ep = Stdlib_Array.make(12, 0);
  let eo = Stdlib_Array.make(12, 0);
  for (let target = 0; target <= 7; ++target) {
    let source = transition.cp[target];
    cp[target] = state.cp[source];
    co[target] = (state.co[source] + transition.co[target] | 0) % 3;
  }
  for (let target$1 = 0; target$1 <= 11; ++target$1) {
    let source$1 = transition.ep[target$1];
    ep[target$1] = state.ep[source$1];
    eo[target$1] = (state.eo[source$1] + transition.eo[target$1] | 0) % 2;
  }
  return {
    size: 3,
    cp: cp,
    co: co,
    ep: ep,
    eo: eo
  };
}

function transitionForAlg(solved, alg) {
  let error = MoveExecutor.applyAlg(solved, alg);
  if (error.TAG === "Ok") {
    let error$1 = PieceReducer.reduce(error._0);
    if (error$1.TAG === "Ok") {
      return error$1._0;
    }
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "InvalidState",
        _0: error$1._0
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: BuildFailure,
    _1: {
      TAG: "ExpansionFailed",
      _0: error._0
    },
    Error: new Error()
  };
}

function atomicActions(solved) {
  let actions = [];
  let faces = [
    "U",
    "D",
    "R",
    "L",
    "F",
    "B"
  ];
  let turns = [
    1,
    2,
    -1
  ];
  faces.forEach(face => {
    turns.forEach(turn => {
      let alg = [{
          desc: {
            TAG: "Move",
            _0: {
              TAG: "FaceTurn",
              _0: face,
              _1: outerRange
            },
            _1: turn
          },
          loc: generatedLoc
        }];
      actions.push({
        alg: alg,
        transition: transitionForAlg(solved, alg),
        faceIndex: faceIndex(face),
        axisIndex: axisIndex(face)
      });
    });
  });
  return actions;
}

function isSolvedCorner(state, piece) {
  if (state.cp[piece] === piece) {
    return state.co[piece] === 0;
  } else {
    return false;
  }
}

function isSolvedEdge(state, piece) {
  if (state.ep[piece] === piece) {
    return state.eo[piece] === 0;
  } else {
    return false;
  }
}

function lockedGoal(state, corners, edges) {
  if (corners.every(piece => isSolvedCorner(state, piece))) {
    return edges.every(piece => isSolvedEdge(state, piece));
  } else {
    return false;
  }
}

function findPiece(permutation, piece) {
  let slot = permutation.findIndex(candidate => candidate === piece);
  if (slot === -1) {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "SearchFailed",
        _0: "piece identification"
      },
      Error: new Error()
    };
  }
  return slot;
}

function projectionKey(state, corners, edges) {
  let cornerKey = corners.map(piece => {
    let slot = findPiece(state.cp, piece);
    return ((slot * 3 | 0) + state.co[slot] | 0).toString();
  }).join(",");
  let edgeKey = edges.map(piece => {
    let slot = findPiece(state.ep, piece);
    return ((slot << 1) + state.eo[slot] | 0).toString();
  }).join(",");
  return cornerKey + "|" + edgeKey;
}

function nextCornerCoordinate(coordinate, transition) {
  let oldSlot = coordinate / 3 | 0;
  let orientation = coordinate % 3;
  let newSlot = transition.cp.findIndex(source => source === oldSlot);
  return (newSlot * 3 | 0) + (orientation + transition.co[newSlot] | 0) % 3 | 0;
}

function nextEdgeCoordinate(coordinate, transition) {
  let oldSlot = coordinate / 2 | 0;
  let orientation = coordinate % 2;
  let newSlot = transition.ep.findIndex(source => source === oldSlot);
  return (newSlot << 1) + (orientation + transition.eo[newSlot] | 0) % 2 | 0;
}

function coordinateDistances(goal, coordinateCount, actions, nextCoordinate) {
  let distances = Stdlib_Array.make(coordinateCount, 99);
  let queue = [goal];
  let head = 0;
  distances[goal] = 0;
  while (head < queue.length) {
    let coordinate = queue[head];
    head = head + 1 | 0;
    let distance = distances[coordinate];
    actions.forEach(action => {
      let next = nextCoordinate(coordinate, action.transition);
      if (distances[next] === 99) {
        distances[next] = distance + 1 | 0;
        queue.push(next);
        return;
      }
    });
  };
  return distances;
}

function atomicDistanceTables(corners, edges, actions) {
  let cornerTables = corners.map(piece => ({
    piece: piece,
    distances: coordinateDistances(piece * 3 | 0, 24, actions, nextCornerCoordinate)
  }));
  let edgeTables = edges.map(piece => ({
    piece: piece,
    distances: coordinateDistances((piece << 1), 24, actions, nextEdgeCoordinate)
  }));
  return [
    cornerTables,
    edgeTables
  ];
}

function atomicCoordinateTargets(corners, edges) {
  return corners.map(piece => ({
    piece: piece,
    kind: "CornerCoordinate",
    goal: piece * 3 | 0
  })).concat(edges.map(piece => ({
    piece: piece,
    kind: "EdgeCoordinate",
    goal: (piece << 1)
  })));
}

function nextTargetCoordinate(coordinate, target, transition) {
  let match = target.kind;
  if (match === "CornerCoordinate") {
    return nextCornerCoordinate(coordinate, transition);
  } else {
    return nextEdgeCoordinate(coordinate, transition);
  }
}

function atomicJointDistanceTables(targets, actions) {
  let tables = [];
  if (targets.length >= 2) {
    for (let leftIndex = 0, leftIndex_finish = targets.length - 2 | 0; leftIndex <= leftIndex_finish; ++leftIndex) {
      for (let rightIndex = leftIndex + 1 | 0, rightIndex_finish = targets.length; rightIndex < rightIndex_finish; ++rightIndex) {
        let left = targets[leftIndex];
        let right = targets[rightIndex];
        let distances = coordinateDistances((left.goal * 24 | 0) + right.goal | 0, 576, actions, (coordinate, transition) => {
          let leftCoordinate = coordinate / 24 | 0;
          let rightCoordinate = coordinate % 24;
          return (nextTargetCoordinate(leftCoordinate, left, transition) * 24 | 0) + nextTargetCoordinate(rightCoordinate, right, transition) | 0;
        });
        tables.push({
          leftIndex: leftIndex,
          rightIndex: rightIndex,
          distances: distances
        });
      }
    }
  }
  return tables;
}

function atomicHeuristicKey(corners, edges, actions) {
  return corners.map(value => value.toString()).join(",") + "|" + edges.map(value => value.toString()).join(",") + "|" + actions.map(action => MoveTransform.serialize(action.alg)).join(";");
}

function atomicHeuristicTables(corners, edges, actions) {
  let key = atomicHeuristicKey(corners, edges, actions);
  let tables = atomicHeuristicCache[key];
  if (tables !== undefined) {
    return tables;
  }
  let match = atomicDistanceTables(corners, edges, actions);
  let targets = atomicCoordinateTargets(corners, edges);
  let tables_cornerTables = match[0];
  let tables_edgeTables = match[1];
  let tables_jointTables = targets.length <= 4 ? atomicJointDistanceTables(targets, actions) : [];
  let tables$1 = {
    cornerTables: tables_cornerTables,
    edgeTables: tables_edgeTables,
    jointTables: tables_jointTables
  };
  atomicHeuristicCache[key] = tables$1;
  return tables$1;
}

function atomicDistanceLowerBound(state, cornerTables, edgeTables) {
  let lowerBound = {
    contents: 0
  };
  cornerTables.forEach(table => {
    let slot = findPiece(state.cp, table.piece);
    let coordinate = (slot * 3 | 0) + state.co[slot] | 0;
    let distance = table.distances[coordinate];
    if (distance > lowerBound.contents) {
      lowerBound.contents = distance;
      return;
    }
  });
  edgeTables.forEach(table => {
    let slot = findPiece(state.ep, table.piece);
    let coordinate = (slot << 1) + state.eo[slot] | 0;
    let distance = table.distances[coordinate];
    if (distance > lowerBound.contents) {
      lowerBound.contents = distance;
      return;
    }
  });
  return lowerBound.contents;
}

function atomicProjection(state, cornerTables, edgeTables, jointTables) {
  let lowerBound = {
    contents: 0
  };
  let key = {
    contents: ""
  };
  let coordinates = [];
  cornerTables.forEach(table => {
    let slot = findPiece(state.cp, table.piece);
    let coordinate = (slot * 3 | 0) + state.co[slot] | 0;
    let distance = table.distances[coordinate];
    if (distance > lowerBound.contents) {
      lowerBound.contents = distance;
    }
    coordinates.push(coordinate);
    key.contents = key.contents + String.fromCharCode(coordinate + 65 | 0);
  });
  key.contents = key.contents + "|";
  edgeTables.forEach(table => {
    let slot = findPiece(state.ep, table.piece);
    let coordinate = (slot << 1) + state.eo[slot] | 0;
    let distance = table.distances[coordinate];
    if (distance > lowerBound.contents) {
      lowerBound.contents = distance;
    }
    coordinates.push(coordinate);
    key.contents = key.contents + String.fromCharCode(coordinate + 65 | 0);
  });
  jointTables.forEach(table => {
    let coordinate = (coordinates[table.leftIndex] * 24 | 0) + coordinates[table.rightIndex] | 0;
    let distance = table.distances[coordinate];
    if (distance > lowerBound.contents) {
      lowerBound.contents = distance;
      return;
    }
  });
  return [
    lowerBound.contents,
    key.contents
  ];
}

function searchAtomicWithLimit(state, corners, edges, actions, maxDepth, maxNodes) {
  if (lockedGoal(state, corners, edges)) {
    return [];
  }
  let tables = atomicHeuristicTables(corners, edges, actions);
  let dfs = (current, remaining, previousFace, previousAxis, path, seen, nodes) => {
    nodes.contents = nodes.contents + 1 | 0;
    if (nodes.contents > maxNodes) {
      return;
    }
    let match = atomicProjection(current, tables.cornerTables, tables.edgeTables, tables.jointTables);
    if (match[0] > remaining) {
      return;
    }
    if (remaining === 0) {
      if (lockedGoal(current, corners, edges)) {
        return path.map(value => value);
      } else {
        return;
      }
    }
    let key = match[1] + "|" + previousFace.toString() + ":" + previousAxis.toString();
    let depth = seen[key];
    let alreadySeen = depth !== undefined ? depth >= remaining : false;
    if (alreadySeen) {
      return;
    }
    seen[key] = remaining;
    let found;
    for (let index = 0, index_finish = actions.length; index < index_finish; ++index) {
      let candidate = actions[index];
      let sameFace = candidate.faceIndex === previousFace;
      let reorderedOpposite = candidate.axisIndex === previousAxis && candidate.faceIndex < previousFace;
      if (found === undefined && !sameFace && !reorderedOpposite) {
        path.push(candidate);
        found = dfs(applyCubie(current, candidate.transition), remaining - 1 | 0, candidate.faceIndex, candidate.axisIndex, path, seen, nodes);
        path.pop();
      }
    }
    return found;
  };
  let found;
  for (let depth = 1; depth <= maxDepth; ++depth) {
    if (found === undefined) {
      let seen = {};
      let nodes = {
        contents: 0
      };
      found = dfs(state, depth, -1, -1, [], seen, nodes);
    }
  }
  return found;
}

function searchAtomic(state, corners, edges, actions, maxDepth) {
  return searchAtomicWithLimit(state, corners, edges, actions, maxDepth, 2500000);
}

function flattenActions(actions) {
  return Stdlib_Array.reduce(actions, [], (output, action) => output.concat(action.alg));
}

function groupedActions(actions) {
  return Stdlib_Array.reduce(actions, [], (output, action) => output.concat(groupedSequence(action.alg)));
}

function fullKey(state) {
  return state.cp.map(value => value.toString()).join("") + state.co.map(value => value.toString()).join("") + state.ep.map(value => String.fromCharCode(value + 65 | 0)).join("") + state.eo.map(value => value.toString()).join("");
}

function parseInternal(input) {
  let alg = MoveParser.parse(3, input);
  if (alg.TAG === "Ok") {
    return alg._0;
  }
  throw {
    RE_EXN_ID: BuildFailure,
    _1: {
      TAG: "SearchFailed",
      _0: "an internal beginner algorithm"
    },
    Error: new Error()
  };
}

function macroAction(solved, alg) {
  return {
    alg: alg,
    transition: transitionForAlg(solved, alg),
    faceIndex: -1,
    axisIndex: -1
  };
}

function downLayerVariant(alg, yTurns) {
  return MoveTransform.rotate(MoveTransform.rotate(alg, "Y", yTurns), "X", 2);
}

function downLayerRegrip(alg, yTurns) {
  let humanSequence = [];
  if (yTurns !== 0) {
    humanSequence.push({
      desc: {
        TAG: "Move",
        _0: {
          TAG: "Rotation",
          _0: "Y"
        },
        _1: -yTurns | 0
      },
      loc: generatedLoc
    });
  }
  alg.forEach(unit => {
    humanSequence.push(unit);
  });
  if (yTurns !== 0) {
    humanSequence.push({
      desc: {
        TAG: "Move",
        _0: {
          TAG: "Rotation",
          _0: "Y"
        },
        _1: yTurns
      },
      loc: generatedLoc
    });
  }
  return MoveTransform.rotate(humanSequence, "X", 2);
}

function macroVariant(solved, base, yTurns) {
  let regripped = downLayerRegrip(base, yTurns);
  let expected = downLayerVariant(base, yTurns);
  let regrippedTransition = transitionForAlg(solved, regripped);
  let expectedTransition = transitionForAlg(solved, expected);
  if (fullKey(regrippedTransition) !== fullKey(expectedTransition)) {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: "VerificationFailed",
      Error: new Error()
    };
  }
  return {
    alg: regripped,
    transition: regrippedTransition,
    faceIndex: -1,
    axisIndex: -1
  };
}

function macroVariants(solved, source) {
  let base = parseInternal(source);
  return [
    0,
    1,
    2,
    3
  ].map(yTurns => macroVariant(solved, base, yTurns));
}

function downTurns(solved) {
  return [
    1,
    2,
    -1
  ].map(turn => {
    let alg = [{
        desc: {
          TAG: "Move",
          _0: {
            TAG: "FaceTurn",
            _0: "D",
            _1: outerRange
          },
          _1: turn
        },
        loc: generatedLoc
      }];
    return macroAction(solved, alg);
  });
}

function searchMacros(state, actions, isGoal, projectionOpt, maxDepth) {
  let projection = projectionOpt !== undefined ? projectionOpt : fullKey;
  if (isGoal(state)) {
    return [];
  }
  let frontier = [{
      state: state,
      path: []
    }];
  let seen = {};
  let found = {
    contents: undefined
  };
  for (let _depth = 1; _depth <= maxDepth; ++_depth) {
    if (found.contents === undefined) {
      let next = [];
      frontier.forEach(node => {
        let key = projection(node.state);
        if (found.contents === undefined && seen[key] === undefined) {
          seen[key] = true;
          actions.forEach(action => {
            if (found.contents !== undefined) {
              return;
            }
            let candidateState = applyCubie(node.state, action.transition);
            let candidatePath = node.path.concat([action]);
            if (isGoal(candidateState)) {
              found.contents = candidatePath;
            } else {
              next.push({
                state: candidateState,
                path: candidatePath
              });
            }
          });
          return;
        }
      });
      frontier = next;
    }
  }
  return found.contents;
}

function firstLayerGoal(state) {
  return lockedGoal(state, [
    0,
    1,
    2,
    3
  ], [
    0,
    1,
    2,
    3
  ]);
}

function firstTwoLayersGoal(state) {
  if (firstLayerGoal(state)) {
    return [
      8,
      9,
      10,
      11
    ].every(piece => isSolvedEdge(state, piece));
  } else {
    return false;
  }
}

function orientedLastEdgesGoal(state) {
  if (firstTwoLayersGoal(state)) {
    return [
      4,
      5,
      6,
      7
    ].every(slot => state.eo[slot] === 0);
  } else {
    return false;
  }
}

function orientedLastCornersGoal(state) {
  if (orientedLastEdgesGoal(state)) {
    return [
      4,
      5,
      6,
      7
    ].every(slot => state.co[slot] === 0);
  } else {
    return false;
  }
}

function positionedLastCornersGoal(state) {
  if (orientedLastCornersGoal(state)) {
    return [
      4,
      5,
      6,
      7
    ].every(piece => isSolvedCorner(state, piece));
  } else {
    return false;
  }
}

function solvedCubiesGoal(state) {
  if ([
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ].every(piece => isSolvedCorner(state, piece))) {
    return [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ].every(piece => isSolvedEdge(state, piece));
  } else {
    return false;
  }
}

function statesEqual(left, right) {
  if (left.size === right.size) {
    return left.facelets.every((facelets, faceIndex) => {
      let other = right.facelets[faceIndex];
      return facelets.every((facelet, index) => facelet === other[index]);
    });
  } else {
    return false;
  }
}

function centresCanonical(state) {
  return StateTypes.storageOrder.every(face => {
    let facelets = state.facelets[StateTypes.storageIndex(face)];
    return facelets[4] === face;
  });
}

function rotateState(state, axis, turns) {
  let result = state;
  for (let _for = 1; _for <= turns; ++_for) {
    result = MoveExecutor.applyStep(result, {
      move: {
        TAG: "Rotation",
        _0: axis
      },
      turns: 1
    });
  }
  return result;
}

function orientFrame(state) {
  let found;
  for (let xTurns = 0; xTurns <= 3; ++xTurns) {
    let afterX = rotateState(state, "X", xTurns);
    for (let yTurns = 0; yTurns <= 3; ++yTurns) {
      let afterY = rotateState(afterX, "Y", yTurns);
      for (let zTurns = 0; zTurns <= 3; ++zTurns) {
        let candidate = rotateState(afterY, "Z", zTurns);
        if (found === undefined && centresCanonical(candidate)) {
          let alg = [];
          if (xTurns !== 0) {
            alg.push({
              desc: {
                TAG: "Move",
                _0: {
                  TAG: "Rotation",
                  _0: "X"
                },
                _1: xTurns
              },
              loc: generatedLoc
            });
          }
          if (yTurns !== 0) {
            alg.push({
              desc: {
                TAG: "Move",
                _0: {
                  TAG: "Rotation",
                  _0: "Y"
                },
                _1: yTurns
              },
              loc: generatedLoc
            });
          }
          if (zTurns !== 0) {
            alg.push({
              desc: {
                TAG: "Move",
                _0: {
                  TAG: "Rotation",
                  _0: "Z"
                },
                _1: zTurns
              },
              loc: generatedLoc
            });
          }
          found = [
            candidate,
            alg
          ];
        }
      }
    }
  }
  return found;
}

function phase(number, title, instruction, alg) {
  return {
    number: number,
    title: title,
    instruction: instruction,
    alg: alg
  };
}

function commentForPhase(phase) {
  return {
    desc: {
      TAG: "BlockComment",
      _0: ` STEP ` + phase.number.toString() + `: ` + phase.title + ` — ` + phase.instruction + ` `
    },
    loc: generatedLoc
  };
}

function solve(input) {
  try {
    if (input.size !== 3) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: input.size
        },
        Error: new Error()
      };
    }
    let error = PieceReducer.reduce(input);
    if (error.TAG !== "Ok") {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: error._0
        },
        Error: new Error()
      };
    }
    let value = orientFrame(input);
    let match;
    if (value !== undefined) {
      match = value;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "centre-frame normalization"
        },
        Error: new Error()
      };
    }
    let state = StateTypes.solved(3);
    let solved;
    if (state.TAG === "Ok") {
      solved = state._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: 3
        },
        Error: new Error()
      };
    }
    let pieces = PieceReducer.reduce(match[0]);
    let start;
    if (pieces.TAG === "Ok") {
      start = pieces._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: pieces._0
        },
        Error: new Error()
      };
    }
    let atomics = atomicActions(solved);
    let current = {
      contents: start
    };
    let crossAlg = [];
    for (let piece = 0; piece <= 3; ++piece) {
      let targets = Belt_Array.makeBy(piece + 1 | 0, index => index);
      let path = searchAtomic(current.contents, [], targets, atomics, 9);
      let path$1;
      if (path !== undefined) {
        path$1 = path;
      } else {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: {
            TAG: "SearchFailed",
            _0: "the white cross"
          },
          Error: new Error()
        };
      }
      path$1.forEach(action => {
        current.contents = applyCubie(current.contents, action.transition);
      });
      crossAlg = crossAlg.concat(groupedSequence(flattenActions(path$1)));
    }
    let cornerAlg = [];
    for (let piece$1 = 0; piece$1 <= 3; ++piece$1) {
      let targets$1 = Belt_Array.makeBy(piece$1 + 1 | 0, index => index);
      let path$2 = searchAtomic(current.contents, targets$1, [
        0,
        1,
        2,
        3
      ], atomics, 10);
      let path$3;
      if (path$2 !== undefined) {
        path$3 = path$2;
      } else {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: {
            TAG: "SearchFailed",
            _0: "the first-layer corners"
          },
          Error: new Error()
        };
      }
      path$3.forEach(action => {
        current.contents = applyCubie(current.contents, action.transition);
      });
      cornerAlg = cornerAlg.concat(groupedSequence(flattenActions(path$3)));
    }
    let middleActions = downTurns(solved).concat(macroVariants(solved, "U R U' R' U' F' U F")).concat(macroVariants(solved, "U' L' U L U F U' F'"));
    let middleAlg = [];
    for (let offset = 0; offset <= 3; ++offset) {
      let targets$2 = Belt_Array.makeBy(offset + 1 | 0, index => 8 + index | 0);
      let projection = state => projectionKey(state, [], targets$2);
      let goal = state => {
        if (firstLayerGoal(state)) {
          return targets$2.every(piece => isSolvedEdge(state, piece));
        } else {
          return false;
        }
      };
      let path$4 = searchMacros(current.contents, middleActions, goal, projection, 5);
      let path$5;
      if (path$4 !== undefined) {
        path$5 = path$4;
      } else {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: {
            TAG: "SearchFailed",
            _0: "the middle-layer edges"
          },
          Error: new Error()
        };
      }
      path$5.forEach(action => {
        current.contents = applyCubie(current.contents, action.transition);
      });
      middleAlg = middleAlg.concat(groupedActions(path$5));
    }
    let lastEdgeActions = downTurns(solved).concat(macroVariants(solved, "F R U R' U' F'"));
    let path$6 = searchMacros(current.contents, lastEdgeActions, orientedLastEdgesGoal, undefined, 4);
    let lastEdgePath;
    if (path$6 !== undefined) {
      lastEdgePath = path$6;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "the yellow cross"
        },
        Error: new Error()
      };
    }
    lastEdgePath.forEach(action => {
      current.contents = applyCubie(current.contents, action.transition);
    });
    let lastCornerActions = downTurns(solved).concat(macroVariants(solved, "R U R' U R U2 R'")).concat(macroVariants(solved, "R U2 R' U' R U' R'"));
    let path$7 = searchMacros(current.contents, lastCornerActions, orientedLastCornersGoal, undefined, 5);
    let lastCornerPath;
    if (path$7 !== undefined) {
      lastCornerPath = path$7;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "yellow-corner orientation"
        },
        Error: new Error()
      };
    }
    lastCornerPath.forEach(action => {
      current.contents = applyCubie(current.contents, action.transition);
    });
    let cornerPermutationActions = downTurns(solved).concat(macroVariants(solved, "R' F R' B2 R F' R' B2 R2"));
    let path$8 = searchMacros(current.contents, cornerPermutationActions, positionedLastCornersGoal, undefined, 5);
    let cornerPermutationPath;
    if (path$8 !== undefined) {
      cornerPermutationPath = path$8;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "last-layer corner positioning"
        },
        Error: new Error()
      };
    }
    cornerPermutationPath.forEach(action => {
      current.contents = applyCubie(current.contents, action.transition);
    });
    let ua = parseInternal("R U' R U R U R U' R' U' R2");
    let ub = MoveTransform.invert(ua);
    let edgePermutationActions = downTurns(solved).concat([
      0,
      1,
      2,
      3
    ].map(y => macroVariant(solved, ua, y))).concat([
      0,
      1,
      2,
      3
    ].map(y => macroVariant(solved, ub, y)));
    let path$9 = searchMacros(current.contents, edgePermutationActions, solvedCubiesGoal, undefined, 5);
    let edgePermutationPath;
    if (path$9 !== undefined) {
      edgePermutationPath = path$9;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "last-layer edge positioning"
        },
        Error: new Error()
      };
    }
    let corePhases = [
      phase(1, "White Cross", "Keep white on top and align the four white edges with their side centres.", crossAlg),
      phase(2, "First-Layer Corners", "Keep white on top and insert the four white corners while preserving the cross.", cornerAlg),
      phase(3, "Middle Layer", "Turn yellow to the top, then insert the four non-yellow edges with beginner left/right insertions.", middleAlg),
      phase(4, "Yellow Cross", "Orient the four yellow edges into a cross.", groupedActions(lastEdgePath)),
      phase(5, "Orient Yellow Corners", "Use Sune and anti-Sune cases until the yellow face is oriented.", groupedActions(lastCornerPath)),
      phase(6, "Position Yellow Corners", "Place the oriented corners over their matching side colours.", groupedActions(cornerPermutationPath)),
      phase(7, "Position Yellow Edges", "Cycle the final edges to finish the cube.", groupedActions(edgePermutationPath))
    ];
    let phases = corePhases.map((item, index) => ({
      number: item.number,
      title: item.title,
      instruction: item.instruction,
      alg: index < 2 ? item.alg : MoveTransform.rotate(item.alg, "X", 2)
    }));
    let coreHasMoves = corePhases.some(item => item.alg.length !== 0);
    let yellowUp = coreHasMoves ? [{
          desc: {
            TAG: "Move",
            _0: {
              TAG: "Rotation",
              _0: "X"
            },
            _1: 2
          },
          loc: generatedLoc
        }] : [];
    let init = phases[0];
    phases[0] = {
      number: init.number,
      title: init.title,
      instruction: init.instruction,
      alg: groupedSequence(match[1]).concat(phases[0].alg)
    };
    let init$1 = phases[2];
    phases[2] = {
      number: init$1.number,
      title: init$1.title,
      instruction: init$1.instruction,
      alg: groupedSequence(yellowUp).concat(phases[2].alg)
    };
    let init$2 = phases[6];
    phases[6] = {
      number: init$2.number,
      title: init$2.title,
      instruction: init$2.instruction,
      alg: phases[6].alg.concat(groupedSequence(yellowUp))
    };
    for (let index = 0, index_finish = phases.length - 2 | 0; index <= index_finish; ++index) {
      let currentPhase = phases[index];
      let phaseAlg = currentPhase.alg.map(unit => unit);
      if (phaseAlg.length !== 0) {
        let last = phaseAlg[phaseAlg.length - 1 | 0];
        let seconds = last.desc;
        if (typeof seconds === "object" && seconds.TAG === "TimedPause") {
          if (seconds._0 === 0.5) {
            phaseAlg.pop();
          }
        }
      }
      phases[index] = {
        number: currentPhase.number,
        title: currentPhase.title,
        instruction: currentPhase.instruction,
        alg: phaseAlg.concat([{
            desc: {
              TAG: "TimedPause",
              _0: 1.2
            },
            loc: generatedLoc
          }])
      };
    }
    let annotated = Stdlib_Array.reduce(phases, [], (output, item) => output.concat([commentForPhase(item)]).concat(item.alg));
    let error$1 = MoveExecutor.expand(annotated);
    let moveCount;
    if (error$1.TAG === "Ok") {
      moveCount = error$1._0.filter(step => {
        let match = step.move;
        switch (match.TAG) {
          case "FaceTurn" :
          case "SliceTurn" :
            return true;
          case "Rotation" :
            return false;
        }
      }).length;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$1._0
        },
        Error: new Error()
      };
    }
    let error$2 = MoveExecutor.applyAlg(input, annotated);
    let result;
    if (error$2.TAG === "Ok") {
      result = error$2._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$2._0
        },
        Error: new Error()
      };
    }
    if (!statesEqual(result, solved)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    return {
      TAG: "Ok",
      _0: {
        phases: phases,
        alg: annotated,
        moveCount: moveCount
      }
    };
  } catch (raw_error) {
    let error$3 = Primitive_exceptions.internalToException(raw_error);
    if (error$3.RE_EXN_ID === BuildFailure) {
      return {
        TAG: "Error",
        _0: error$3._1
      };
    }
    throw error$3;
  }
}

let maxAtomicNodes = 2500000;

export {
  atomicHeuristicCache,
  BuildFailure,
  generatedLoc,
  located,
  outerRange,
  maxAtomicNodes,
  describeError,
  concatAlg,
  groupedSequence,
  faceIndex,
  axisIndex,
  applyCubie,
  transitionForAlg,
  atomicActions,
  isSolvedCorner,
  isSolvedEdge,
  lockedGoal,
  findPiece,
  projectionKey,
  nextCornerCoordinate,
  nextEdgeCoordinate,
  coordinateDistances,
  atomicDistanceTables,
  atomicCoordinateTargets,
  nextTargetCoordinate,
  atomicJointDistanceTables,
  atomicHeuristicKey,
  atomicHeuristicTables,
  atomicDistanceLowerBound,
  atomicProjection,
  searchAtomicWithLimit,
  searchAtomic,
  flattenActions,
  groupedActions,
  fullKey,
  parseInternal,
  macroAction,
  downLayerVariant,
  downLayerRegrip,
  macroVariant,
  macroVariants,
  downTurns,
  searchMacros,
  firstLayerGoal,
  firstTwoLayersGoal,
  orientedLastEdgesGoal,
  orientedLastCornersGoal,
  positionedLastCornersGoal,
  solvedCubiesGoal,
  statesEqual,
  centresCanonical,
  rotateState,
  orientFrame,
  phase,
  commentForPhase,
  solve,
}
/* No side effect */
