// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Optimal2x2Table from "./Optimal2x2Table.res.mjs";

let moveTokens = [
  "U",
  "U2",
  "U'",
  "D",
  "D2",
  "D'",
  "R",
  "R2",
  "R'",
  "L",
  "L2",
  "L'",
  "F",
  "F2",
  "F'",
  "B",
  "B2",
  "B'"
];

function identity() {
  return {
    cp: [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    co: [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  };
}

let stateKey = ((state) => state.cp.join(',') + '/' + state.co.join(','));

function applyTransform(state, transform) {
  let len = transform.cp.length;
  let cp = Stdlib_Array.fromInitializer(len, i => {
    let source = Stdlib_Option.getOr(transform.cp[i], 0);
    return Stdlib_Option.getOr(state.cp[source], 0);
  });
  let co = Stdlib_Array.fromInitializer(len, i => {
    let source = Stdlib_Option.getOr(transform.cp[i], 0);
    let sCo = Stdlib_Option.getOr(state.co[source], 0);
    let tCo = Stdlib_Option.getOr(transform.co[i], 0);
    return (sCo + tCo | 0) % 3;
  });
  return {
    cp: cp,
    co: co
  };
}

function compose(left, right) {
  return applyTransform(right, left);
}

function transformFor(token) {
  let match = MoveParser.parse(2, token);
  let match$1 = StateTypes.solved(2);
  if (match.TAG !== "Ok") {
    return Pervasives.failwith("Could not prepare " + token + ".");
  }
  if (match$1.TAG !== "Ok") {
    return Pervasives.failwith("Could not prepare " + token + ".");
  }
  let moved = MoveExecutor.applyAlg(match$1._0, match._0);
  if (moved.TAG !== "Ok") {
    return Pervasives.failwith("Could not apply " + token + ".");
  }
  let reduced = PieceReducer.reduce(moved._0);
  if (reduced.TAG !== "Ok") {
    return Pervasives.failwith("Could not reduce " + token + ".");
  }
  let reduced$1 = reduced._0;
  return {
    cp: reduced$1.cp,
    co: reduced$1.co
  };
}

let moveTransforms = moveTokens.map(transformFor);

let wholeRotationTokens = [
  "x",
  "x'",
  "y",
  "y'",
  "z",
  "z'"
];

let wholeRotationTransforms = wholeRotationTokens.map(transformFor);

let generators = [
  transformFor("x"),
  transformFor("y"),
  transformFor("z")
];

let values = [identity()];

let seen = new Set([stateKey(Stdlib_Option.getOr(values[0], identity()))]);

let index = 0;

while (index < values.length) {
  let current = Stdlib_Option.getOr(values[index], identity());
  index = index + 1 | 0;
  for (let gIdx = 0, gIdx_finish = generators.length; gIdx < gIdx_finish; ++gIdx) {
    let generator = Stdlib_Option.getOr(generators[gIdx], identity());
    let next = applyTransform(current, generator);
    let key = stateKey(next);
    if (!seen.has(key)) {
      seen.add(key);
      values.push(next);
    }
  }
};

if (values.length !== 24) {
  Pervasives.failwith("Could not generate the 24 cube orientations.");
}

let lookup = Stdlib_Array.fromInitializer(24, param => -1);

values.forEach((rotation, index) => {
  let cp0 = Stdlib_Option.getOr(rotation.cp[0], 0);
  let co0 = Stdlib_Option.getOr(rotation.co[0], 0);
  let pos = (cp0 * 3 | 0) + (3 - co0 | 0) % 3 | 0;
  lookup[pos] = index;
});

if (lookup.some(value => value < 0)) {
  Pervasives.failwith("Could not anchor 2×2 orientations.");
}

function rank(values) {
  let output = 0;
  let len = values.length;
  for (let left = 0, left_finish = len - 2 | 0; left <= left_finish; ++left) {
    let smaller = 0;
    let valLeft = Stdlib_Option.getOr(values[left], 0);
    for (let right = left + 1 | 0; right < len; ++right) {
      if (Stdlib_Option.getOr(values[right], 0) < valLeft) {
        smaller = smaller + 1 | 0;
      }
    }
    output = (output * (len - left | 0) | 0) + smaller | 0;
  }
  return output;
}

function unrank(coordinate) {
  let available = [
    1,
    2,
    3,
    4,
    5,
    6,
    7
  ];
  let output = [0];
  let remaining = coordinate;
  for (let slot = 0; slot <= 6; ++slot) {
    let factorial = 1;
    for (let i = 2, i_finish = 7 - slot | 0; i < i_finish; ++i) {
      factorial = factorial * i | 0;
    }
    let fact = factorial;
    let selected = fact === 0 ? 0 : Primitive_int.div(remaining, fact);
    let spliceHelper = ((arr, idx) => arr.splice(idx, 1)[0]);
    let removed = spliceHelper(available, selected);
    output.push(removed);
    remaining = fact === 0 ? 0 : Primitive_int.mod_(remaining, fact);
  }
  return output;
}

function orientationRank(co) {
  let rankVal = 0;
  for (let slot = 1; slot <= 6; ++slot) {
    rankVal = (rankVal * 3 | 0) + Stdlib_Option.getOr(co[slot], 0) | 0;
  }
  return rankVal;
}

function orientationUnrank(coordinate) {
  let co = Stdlib_Array.fromInitializer(8, param => 0);
  let remaining = coordinate;
  let sum = 0;
  let slot = 6;
  while (slot >= 1) {
    let digit = remaining % 3;
    co[slot] = digit;
    sum = sum + digit | 0;
    remaining = remaining / 3 | 0;
    slot = slot - 1 | 0;
  };
  co[7] = (3 - sum % 3 | 0) % 3;
  return co;
}

function canonical(state) {
  let slot = state.cp.indexOf(0);
  if (slot < 0) {
    Pervasives.failwith("The 2×2 corner permutation is invalid.");
  }
  let coSlot = Stdlib_Option.getOr(state.co[slot], 0);
  let anchorIdx = Stdlib_Option.getOr(lookup[(slot * 3 | 0) + coSlot | 0], 0);
  let rot = Stdlib_Option.getOr(values[anchorIdx], identity());
  return applyTransform(state, rot);
}

function coordinateForCubies(state) {
  let value = canonical(state);
  let perm = value.cp.slice(1).map(piece => piece - 1 | 0);
  let coordinate = (rank(perm) * 729 | 0) + orientationRank(value.co) | 0;
  if (coordinate < 0 || coordinate >= Optimal2x2Table.optimal_2X2_STATES) {
    Pervasives.failwith("The canonical 2×2 coordinate is invalid.");
  }
  return coordinate;
}

function cubiesForCoordinate(coordinate) {
  return {
    cp: unrank(coordinate / 729 | 0),
    co: orientationUnrank(coordinate % 729)
  };
}

function transitionCoordinate(coordinate, move) {
  let moveTrans = Stdlib_Option.getOr(moveTransforms[move], identity());
  return coordinateForCubies(applyTransform(cubiesForCoordinate(coordinate), moveTrans));
}

function transformations() {
  return moveTransforms;
}

function rotationTokensToIdentity(state) {
  let idKey = stateKey(identity());
  let initialKey = stateKey(state);
  let queue = [{
      state: state,
      tokens: []
    }];
  let seen = new Set([initialKey]);
  let index = 0;
  let foundTokens;
  while (index < queue.length && Stdlib_Option.isNone(foundTokens)) {
    let candidate = Stdlib_Option.getOr(queue[index], {
      state: identity(),
      tokens: []
    });
    index = index + 1 | 0;
    if (stateKey(candidate.state) === idKey) {
      foundTokens = candidate.tokens;
    } else {
      wholeRotationTransforms.forEach((transform, transformIndex) => {
        let next = applyTransform(candidate.state, transform);
        let nextKey = stateKey(next);
        if (seen.has(nextKey)) {
          return;
        }
        seen.add(nextKey);
        let token = Stdlib_Option.getOr(wholeRotationTokens[transformIndex], "");
        let nextTokens = candidate.tokens.concat([token]);
        queue.push({
          state: next,
          tokens: nextTokens
        });
      });
    }
  };
  let tokens = foundTokens;
  if (tokens !== undefined) {
    return tokens;
  } else {
    return Pervasives.failwith("The solved-equivalent 2×2 orientation could not be restored.");
  }
}

let rotations = values;

let anchor = lookup;

export {
  moveTokens,
  identity,
  stateKey,
  applyTransform,
  compose,
  transformFor,
  moveTransforms,
  wholeRotationTokens,
  wholeRotationTransforms,
  rotations,
  anchor,
  rank,
  unrank,
  orientationRank,
  orientationUnrank,
  canonical,
  coordinateForCubies,
  cubiesForCoordinate,
  transitionCoordinate,
  transformations,
  rotationTokensToIdentity,
}
/* moveTransforms Not a pure module */
