// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CfopCases from "./CfopCases.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as MoveTransform from "../Move/MoveTransform.res.mjs";
import * as BeginnerSolver from "./BeginnerSolver.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let BuildFailure = /* @__PURE__ */Primitive_exceptions.create("CfopSolver.BuildFailure");

let generatedLoc = {
  start: 0,
  end_: 0
};

function located(desc) {
  return {
    desc: desc,
    loc: generatedLoc
  };
}

function phase(number, title, instruction, alg, sequences) {
  return {
    number: number,
    title: title,
    instruction: instruction,
    alg: alg,
    sequences: sequences
  };
}

function commentForPhase(phase) {
  return {
    desc: {
      TAG: "BlockComment",
      _0: ` CFOP ` + phase.number.toString() + `: ` + phase.title + ` — ` + phase.instruction + ` `
    },
    loc: generatedLoc
  };
}

let grouped = BeginnerSolver.groupedSequence;

function withPhasePause(alg) {
  let output = alg.map(unit => unit);
  if (output.length !== 0) {
    let lastIndex = output.length - 1 | 0;
    let match = output[lastIndex].desc;
    if (typeof match === "object" && match.TAG === "TimedPause") {
      output[lastIndex] = {
        desc: {
          TAG: "TimedPause",
          _0: 1.2
        },
        loc: generatedLoc
      };
    }
  }
  return output;
}

function applyPath(state, path) {
  return Stdlib_Array.reduce(path, state, (current, action) => BeginnerSolver.applyCubie(current, action.transition));
}

function physicalCost(alg) {
  let steps = MoveExecutor.expand(alg);
  if (steps.TAG !== "Ok") {
    return {
      total: 1000000,
      physicalMoves: 0,
      rotations: 0,
      estimatedRegrips: 0,
      ergonomicPenalty: 0
    };
  }
  let physicalMoves = {
    contents: 0
  };
  let halfTurns = {
    contents: 0
  };
  let rotations = {
    contents: 0
  };
  let estimatedRegrips = {
    contents: 0
  };
  let ergonomicPenalty = {
    contents: 0
  };
  steps._0.forEach(step => {
    if (step.turns % 2 === 0) {
      halfTurns.contents = halfTurns.contents + 1 | 0;
    }
    let match = step.move;
    switch (match.TAG) {
      case "FaceTurn" :
        switch (match._0) {
          case "L" :
            physicalMoves.contents = physicalMoves.contents + 1 | 0;
            ergonomicPenalty.contents = ergonomicPenalty.contents + 5 | 0;
            return;
          case "B" :
            physicalMoves.contents = physicalMoves.contents + 1 | 0;
            estimatedRegrips.contents = estimatedRegrips.contents + 1 | 0;
            ergonomicPenalty.contents = ergonomicPenalty.contents + 12 | 0;
            return;
          default:
            physicalMoves.contents = physicalMoves.contents + 1 | 0;
            return;
        }
      case "SliceTurn" :
        physicalMoves.contents = physicalMoves.contents + 1 | 0;
        ergonomicPenalty.contents = ergonomicPenalty.contents + 8 | 0;
        return;
      case "Rotation" :
        rotations.contents = rotations.contents + 1 | 0;
        estimatedRegrips.contents = estimatedRegrips.contents + 1 | 0;
        return;
    }
  });
  return {
    total: ((((physicalMoves.contents * 100 | 0) + (halfTurns.contents * 25 | 0) | 0) + (rotations.contents * 35 | 0) | 0) + (estimatedRegrips.contents * 18 | 0) | 0) + ergonomicPenalty.contents | 0,
    physicalMoves: physicalMoves.contents,
    rotations: rotations.contents,
    estimatedRegrips: estimatedRegrips.contents,
    ergonomicPenalty: ergonomicPenalty.contents
  };
}

function physicalScore(alg) {
  return physicalCost(alg).total;
}

function rankedActions(actions) {
  let ranked = actions.map(action => {
    let alg = MoveTransform.rotate(action.alg, "X", 2);
    return [
      action,
      physicalCost(alg).total
    ];
  });
  ranked.sort((left, right) => left[1] - right[1] | 0);
  return ranked.map(param => param[0]);
}

function biasedActions(actions, preferredFace) {
  let ranked = actions.map(action => action);
  ranked.sort((left, right) => {
    let leftBias = left.faceIndex === preferredFace ? 0 : 1;
    let rightBias = right.faceIndex === preferredFace ? 0 : 1;
    let biasDifference = leftBias - rightBias | 0;
    if (biasDifference !== 0) {
      return biasDifference;
    }
    let alg = MoveTransform.rotate(left.alg, "X", 2);
    let leftScore = physicalCost(alg).total;
    let alg$1 = MoveTransform.rotate(right.alg, "X", 2);
    let rightScore = physicalCost(alg$1).total;
    return leftScore - rightScore | 0;
  });
  return ranked;
}

function crossPathKey(path) {
  return MoveTransform.serialize(BeginnerSolver.flattenActions(path));
}

function crossCandidateScore(state, path) {
  let after = applyPath(state, path);
  let solvedPairs = [
    0,
    1,
    2,
    3
  ].filter(pair => {
    if (BeginnerSolver.isSolvedCorner(after, pair)) {
      return BeginnerSolver.isSolvedEdge(after, 8 + pair | 0);
    } else {
      return false;
    }
  });
  let humanAlg = MoveTransform.rotate(BeginnerSolver.flattenActions(path), "X", 2);
  return physicalCost(humanAlg).total - (solvedPairs.length * 90 | 0) | 0;
}

function selectCross(state, atomics) {
  let paths = [];
  let seen = {};
  let collect = candidate => {
    if (candidate === undefined) {
      return;
    }
    let key = MoveTransform.serialize(BeginnerSolver.flattenActions(candidate));
    if (seen[key] === undefined) {
      seen[key] = true;
      paths.push(candidate);
      return;
    }
  };
  collect(BeginnerSolver.searchAtomic(state, [], [
    0,
    1,
    2,
    3
  ], rankedActions(atomics), 8));
  [2].forEach(preferredFace => collect(BeginnerSolver.searchAtomicWithLimit(state, [], [
    0,
    1,
    2,
    3
  ], biasedActions(atomics, preferredFace), 8, 100000)));
  if (paths.length === 0) {
    return;
  }
  let best = paths[0];
  let bestScore = crossCandidateScore(state, best);
  for (let index = 1, index_finish = paths.length; index < index_finish; ++index) {
    let candidate = paths[index];
    let score = crossCandidateScore(state, candidate);
    if (score < bestScore) {
      best = candidate;
      bestScore = score;
    }
  }
  return {
    path: best,
    candidates: paths.length
  };
}

function actionIsAlignment(action) {
  let match = action.alg;
  if (match.length !== 1) {
    return false;
  }
  let match$1 = match[0];
  let match$2 = match$1.desc;
  if (typeof match$2 !== "object") {
    return false;
  }
  if (match$2.TAG !== "Move") {
    return false;
  }
  let match$3 = match$2._0;
  switch (match$3.TAG) {
    case "FaceTurn" :
      return match$3._0 === "D";
    case "SliceTurn" :
    case "Rotation" :
      return false;
  }
}

let pairNames = [
  "white–green–red",
  "white–green–orange",
  "white–blue–orange",
  "white–blue–red"
];

let cornerSlots = [
  "UFR",
  "UFL",
  "UBL",
  "UBR",
  "DFR",
  "DLF",
  "DBL",
  "DRB"
];

let edgeSlots = [
  "UR",
  "UF",
  "UL",
  "UB",
  "DR",
  "DF",
  "DL",
  "DB",
  "FR",
  "FL",
  "BL",
  "BR"
];

function physicalPosition(position) {
  return position.split("").map(face => {
    switch (face) {
      case "B" :
        return "F";
      case "D" :
        return "U";
      case "F" :
        return "B";
      case "U" :
        return "D";
      default:
        return face;
    }
  }).join("");
}

function describePairCase(state, pair) {
  let cornerSlot = BeginnerSolver.findPiece(state.cp, pair);
  let edgeSlot = BeginnerSolver.findPiece(state.ep, 8 + pair | 0);
  let cornerPosition = physicalPosition(cornerSlots[cornerSlot]);
  let edgePosition = physicalPosition(edgeSlots[edgeSlot]);
  let connected = edgePosition.split("").every(face => cornerPosition.includes(face));
  let situation = connected && cornerSlot >= 4 && edgeSlot >= 4 && edgeSlot <= 7 ? "connected pair in the top layer" : (
      connected ? "connected pair outside its target slot" : (
          cornerSlot >= 4 && edgeSlot >= 4 && edgeSlot <= 7 ? "both pieces separated in the top layer" : (
              cornerSlot >= 4 && edgeSlot >= 8 ? "corner on top; edge trapped in an F2L slot" : (
                  cornerSlot < 4 ? "corner trapped in the first layer" : "separated corner-edge pair"
                )
            )
        )
    );
  let whiteFace = cornerPosition.split("")[state.co[cornerSlot]];
  let whiteOrientation;
  switch (whiteFace) {
    case "D" :
      whiteOrientation = "white sticker faces down";
      break;
    case "U" :
      whiteOrientation = "white sticker faces up";
      break;
    default:
      whiteOrientation = `white sticker faces ` + whiteFace;
  }
  let edgeOrientation = state.eo[edgeSlot] === 0 ? "edge oriented" : "edge flipped";
  return `Solve the ` + pairNames[pair] + ` pair — ` + situation + `; ` + whiteOrientation + `; ` + edgeOrientation + ` (corner ` + cornerPosition + `, edge ` + edgePosition + `).`;
}

function addPositionFaces(faces, position) {
  position.split("").forEach(face => {
    let index;
    switch (face) {
      case "B" :
        index = 5;
        break;
      case "F" :
        index = 4;
        break;
      case "L" :
        index = 3;
        break;
      case "R" :
        index = 2;
        break;
      default:
        index = -1;
    }
    if (index !== -1 && !faces.some(candidate => candidate === index)) {
      faces.push(index);
      return;
    }
  });
}

function f2lFaces(state, pair, allSides) {
  if (allSides) {
    return [
      1,
      2,
      3,
      4,
      5
    ];
  }
  let faces = [1];
  addPositionFaces(faces, cornerSlots[pair]);
  addPositionFaces(faces, edgeSlots[8 + pair | 0]);
  addPositionFaces(faces, cornerSlots[BeginnerSolver.findPiece(state.cp, pair)]);
  addPositionFaces(faces, edgeSlots[BeginnerSolver.findPiece(state.ep, 8 + pair | 0)]);
  return faces;
}

function findPairCandidate(state, completed, pair, atomics, maxDepth, maxNodes, allSides) {
  let targets = completed.concat([pair]);
  let edges = [
    0,
    1,
    2,
    3
  ].concat(targets.map(value => 8 + value | 0));
  let faces = f2lFaces(state, pair, allSides);
  let actions = atomics.filter(action => faces.some(face => face === action.faceIndex));
  let path = BeginnerSolver.searchAtomicWithLimit(state, targets, edges, actions, maxDepth, maxNodes);
  if (path === undefined) {
    return;
  }
  let alg = BeginnerSolver.flattenActions(path);
  let humanAlg = MoveTransform.rotate(alg, "X", 2);
  return {
    pair: pair,
    path: path,
    score: physicalCost(humanAlg).total,
    label: describePairCase(state, pair)
  };
}

function comparePairs(left, right) {
  let scoreDifference = left.score - right.score | 0;
  if (scoreDifference !== 0) {
    return scoreDifference;
  } else {
    return left.path.length - right.path.length | 0;
  }
}

function f2lPlanScore(plan) {
  return Stdlib_Array.reduce(plan, 0, (total, candidate) => total + candidate.score | 0);
}

function f2lPlanKey(state, completed) {
  return BeginnerSolver.fullKey(state) + "|" + [
    0,
    1,
    2,
    3
  ].map(pair => {
    if (completed.some(value => value === pair)) {
      return "1";
    } else {
      return "0";
    }
  }).join("");
}

function planF2l(state, completed, atomics, maxDepth, maxNodes, allSides, rootCandidates, failed) {
  if (completed.length === 4) {
    return [];
  }
  let key = f2lPlanKey(state, completed);
  let match = failed[key];
  if (match !== undefined) {
    return;
  }
  let candidates = [];
  for (let pair = 0; pair <= 3; ++pair) {
    if (!completed.some(value => value === pair)) {
      let candidate = findPairCandidate(state, completed, pair, atomics, maxDepth, maxNodes, allSides);
      if (candidate !== undefined) {
        candidates.push(candidate);
      }
    }
  }
  candidates.sort(comparePairs);
  let result;
  let bestScore = 100000000;
  let candidateLimit = candidates.length < rootCandidates ? candidates.length : rootCandidates;
  for (let index = 0; index < candidateLimit; ++index) {
    let candidate$1 = candidates[index];
    let nextState = applyPath(state, candidate$1.path);
    let nextCompleted = completed.concat([candidate$1.pair]);
    let rest = planF2l(nextState, nextCompleted, atomics, maxDepth, maxNodes, allSides, rootCandidates, failed);
    if (rest !== undefined) {
      let plan = [candidate$1].concat(rest);
      let score = f2lPlanScore(plan);
      if (score < bestScore) {
        bestScore = score;
        result = plan;
      }
    }
  }
  if (result === undefined) {
    failed[key] = true;
  }
  return result;
}

let lastLayerSlots = [
  4,
  5,
  6,
  7
];

function orientationKey(state) {
  return lastLayerSlots.map(slot => state.co[slot].toString()).join("") + "|" + lastLayerSlots.map(slot => state.eo[slot].toString()).join("");
}

function permutationKey(state) {
  return lastLayerSlots.map(slot => state.cp[slot].toString()).join("") + "|" + lastLayerSlots.map(slot => state.ep[slot].toString()).join("");
}

function downAction(solved, turns) {
  let normalized = (turns % 4 + 4 | 0) % 4;
  if (normalized === 0) {
    return;
  }
  let canonical = normalized === 3 ? -1 : normalized;
  return BeginnerSolver.downTurns(solved).find(action => {
    let match = action.alg;
    if (match.length !== 1) {
      return false;
    }
    let match$1 = match[0];
    let match$2 = match$1.desc;
    if (typeof match$2 !== "object") {
      return false;
    }
    if (match$2.TAG !== "Move") {
      return false;
    }
    let match$3 = match$2._0;
    switch (match$3.TAG) {
      case "FaceTurn" :
        if (match$3._0 === "D") {
          return match$2._1 === canonical;
        } else {
          return false;
        }
      case "SliceTurn" :
      case "Rotation" :
        return false;
    }
  });
}

function applyDown(state, solved, turns) {
  let action = downAction(solved, turns);
  if (action !== undefined) {
    return BeginnerSolver.applyCubie(state, action.transition);
  } else {
    return state;
  }
}

function normalizedLastLayerKey(state, solved, key) {
  let best = key(state);
  for (let turns = 1; turns <= 3; ++turns) {
    let candidate = key(applyDown(state, solved, turns));
    if (Primitive_object.lessthan(candidate, best)) {
      best = candidate;
    }
  }
  return best;
}

function caseAction(solved, algorithm) {
  return BeginnerSolver.macroVariant(solved, BeginnerSolver.parseInternal(algorithm), 0);
}

function inverseSetup(solved, action) {
  return BeginnerSolver.transitionForAlg(solved, MoveTransform.invert(action.alg));
}

function appendActionGroup(output, action) {
  output.push({
    desc: {
      TAG: "Group",
      _0: action.alg,
      _1: 1
    },
    loc: generatedLoc
  });
  output.push({
    desc: {
      TAG: "TimedPause",
      _0: 0.5
    },
    loc: generatedLoc
  });
}

function validateCaseLibraries(solved) {
  if (CfopCases.oll.length !== 57 || CfopCases.pll.length !== 21) {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: "VerificationFailed",
      Error: new Error()
    };
  }
  let ollSignatures = {};
  CfopCases.oll.forEach(entry => {
    let action = caseAction(solved, entry.algorithm);
    let setup = inverseSetup(solved, action);
    if (!BeginnerSolver.firstTwoLayersGoal(setup)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let replay = BeginnerSolver.applyCubie(setup, action.transition);
    if (!BeginnerSolver.solvedCubiesGoal(replay)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let signature = normalizedLastLayerKey(setup, solved, orientationKey);
    if (ollSignatures[signature] !== undefined) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    ollSignatures[signature] = entry.id;
  });
  let pllSignatures = {};
  CfopCases.pll.forEach(entry => {
    let action = caseAction(solved, entry.algorithm);
    let setup = inverseSetup(solved, action);
    if (!BeginnerSolver.orientedLastCornersGoal(setup)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let replay = BeginnerSolver.applyCubie(setup, action.transition);
    if (!BeginnerSolver.solvedCubiesGoal(replay)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let signature = normalizedLastLayerKey(setup, solved, permutationKey);
    if (pllSignatures[signature] !== undefined) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    pllSignatures[signature] = entry.id;
  });
  return [
    ollSignatures,
    pllSignatures
  ];
}

let caseLibraryCache = {
  contents: undefined
};

function cachedCaseLibraries(solved) {
  let libraries = caseLibraryCache.contents;
  if (libraries !== undefined) {
    return libraries;
  }
  let libraries$1 = validateCaseLibraries(solved);
  caseLibraryCache.contents = libraries$1;
  return libraries$1;
}

function selectOll(state, solved, signatures) {
  if (BeginnerSolver.orientedLastCornersGoal(state)) {
    return {
      alg: [],
      labels: ["OLL already oriented."],
      state: state
    };
  }
  let signature = normalizedLastLayerKey(state, solved, orientationKey);
  let caseId = signatures[signature];
  if (caseId === undefined) {
    return;
  }
  let recognized = CfopCases.oll.find(entry => entry.id === caseId);
  if (recognized === undefined) {
    return;
  }
  let action = caseAction(solved, recognized.algorithm);
  let best;
  let bestScore = 1000000;
  for (let turns = 0; turns <= 3; ++turns) {
    let aligned = applyDown(state, solved, turns);
    let after = BeginnerSolver.applyCubie(aligned, action.transition);
    if (BeginnerSolver.orientedLastCornersGoal(after)) {
      let candidateAlg = [];
      let labels = [];
      let auf = downAction(solved, turns);
      if (auf !== undefined) {
        appendActionGroup(candidateAlg, auf);
        labels.push("AUF: align the recognized OLL case.");
      }
      appendActionGroup(candidateAlg, action);
      labels.push(`OLL ` + recognized.id.toString() + ` · ` + recognized.family + ` — one-look orientation.`);
      let alg = MoveTransform.rotate(candidateAlg, "X", 2);
      let score = physicalCost(alg).total;
      if (score < bestScore) {
        bestScore = score;
        best = {
          alg: candidateAlg,
          labels: labels,
          state: after
        };
      }
    }
  }
  return best;
}

function selectPll(state, solved) {
  if (BeginnerSolver.solvedCubiesGoal(state)) {
    return {
      alg: [],
      labels: ["PLL already solved."],
      state: state
    };
  }
  let aufOnly;
  for (let turns = 1; turns <= 3; ++turns) {
    let after = applyDown(state, solved, turns);
    if (aufOnly === undefined && BeginnerSolver.solvedCubiesGoal(after)) {
      let auf = downAction(solved, turns);
      if (auf !== undefined) {
        let alg = [];
        appendActionGroup(alg, auf);
        aufOnly = {
          alg: alg,
          labels: ["Final PLL AUF."],
          state: after
        };
      }
    }
  }
  let selection = aufOnly;
  if (selection !== undefined) {
    return selection;
  }
  let best = {
    contents: undefined
  };
  let bestScore = {
    contents: 1000000
  };
  CfopCases.pll.forEach(entry => {
    let action = caseAction(solved, entry.algorithm);
    for (let preTurns = 0; preTurns <= 3; ++preTurns) {
      let aligned = applyDown(state, solved, preTurns);
      let permuted = BeginnerSolver.applyCubie(aligned, action.transition);
      for (let postTurns = 0; postTurns <= 3; ++postTurns) {
        let after = applyDown(permuted, solved, postTurns);
        if (BeginnerSolver.solvedCubiesGoal(after)) {
          let candidateAlg = [];
          let labels = [];
          let auf = downAction(solved, preTurns);
          if (auf !== undefined) {
            appendActionGroup(candidateAlg, auf);
            labels.push("AUF: align the recognized PLL case.");
          }
          appendActionGroup(candidateAlg, action);
          labels.push(entry.id + `-Perm — one-look permutation.`);
          let auf$1 = downAction(solved, postTurns);
          if (auf$1 !== undefined) {
            appendActionGroup(candidateAlg, auf$1);
            labels.push("Final PLL AUF.");
          }
          let alg = MoveTransform.rotate(candidateAlg, "X", 2);
          let score = physicalCost(alg).total;
          if (score < bestScore.contents) {
            bestScore.contents = score;
            best.contents = {
              alg: candidateAlg,
              labels: labels,
              state: after
            };
          }
        }
      }
    }
  });
  return best.contents;
}

function describeEdgeOrientation(state) {
  let oriented = lastLayerSlots.filter(slot => state.eo[slot] === 0);
  let match = oriented.length;
  switch (match) {
    case 0 :
      return "Orient the OLL dot into a yellow cross.";
    case 2 :
      let delta = oriented[0] - oriented[1] | 0;
      let distance = delta < 0 ? -delta | 0 : delta;
      if (distance === 2) {
        return "Orient the OLL line into a yellow cross.";
      } else {
        return "Orient the OLL L-shape into a yellow cross.";
      }
    default:
      return "Align the yellow-edge OLL case.";
  }
}

function describeCornerOrientation(state) {
  let oriented = lastLayerSlots.filter(slot => state.co[slot] === 0);
  let match = oriented.length;
  switch (match) {
    case 0 :
      return "Orient the four-corner OLL case.";
    case 1 :
      return "Orient the Sune or anti-Sune corner case.";
    case 2 :
      return "Orient the two-corner OLL case.";
    default:
      return "Align the final OLL corner case.";
  }
}

function describeCornerPermutation(state) {
  let positioned = lastLayerSlots.filter(piece => BeginnerSolver.isSolvedCorner(state, piece));
  let match = positioned.length;
  if (match > 0) {
    if (match >= 3) {
      return "Apply the final corner AUF.";
    } else {
      return "Permute three last-layer corners from the headlights case.";
    }
  } else if (match >= 0) {
    return "Permute three last-layer corners from the diagonal/headlights case.";
  } else {
    return "Apply the final corner AUF.";
  }
}

function describeEdgePermutation(state) {
  let positioned = lastLayerSlots.filter(piece => BeginnerSolver.isSolvedEdge(state, piece));
  let match = positioned.length;
  if (match !== 0) {
    if (match !== 1) {
      return "Apply the final PLL AUF.";
    } else {
      return "Solve the Ua/Ub three-edge cycle.";
    }
  } else {
    return "Solve the H/Z four-edge permutation.";
  }
}

function groupedPathWithLabels(state, path, describe) {
  let current = {
    contents: state
  };
  let alg = [];
  let labels = [];
  path.forEach(action => {
    labels.push(actionIsAlignment(action) ? "AUF: align the recognized case." : describe(current.contents));
    appendActionGroup(alg, action);
    current.contents = BeginnerSolver.applyCubie(current.contents, action.transition);
  });
  return [
    alg,
    labels,
    current.contents
  ];
}

function selectBeginnerOll(state, solved) {
  let edgePrimitives = BeginnerSolver.macroVariants(solved, "F R U R' U' F'").concat(BeginnerSolver.macroVariants(solved, "F U R U' R' F'")).concat(BeginnerSolver.macroVariants(solved, "F R U R' U' F' U2 F U R U' R' F'"));
  let edgeActions = rankedActions(BeginnerSolver.downTurns(solved).concat(rankedActions(edgePrimitives)));
  let path = BeginnerSolver.searchMacros(state, edgeActions, BeginnerSolver.orientedLastEdgesGoal, undefined, 2);
  let edgePath;
  if (path !== undefined) {
    edgePath = path;
  } else {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "SearchFailed",
        _0: "two-look OLL edge orientation"
      },
      Error: new Error()
    };
  }
  let match = groupedPathWithLabels(state, edgePath, describeEdgeOrientation);
  let afterEdges = match[2];
  let cornerAlgorithms = [
    "R U R' U R U2 R'",
    "R U2 R' U' R U' R'",
    "R U2 R2 U' R2 U' R2 U2 R",
    "R U R' U R U' R' U R U2 R'",
    "r U R' U' r' F R F'",
    "F' r U R' U' r' F R",
    "R2 D R' U2 R D' R' U2 R'"
  ];
  let cornerPrimitives = Stdlib_Array.reduce(cornerAlgorithms, [], (all, algorithm) => all.concat(BeginnerSolver.macroVariants(solved, algorithm)));
  let cornerActions = rankedActions(BeginnerSolver.downTurns(solved).concat(rankedActions(cornerPrimitives)));
  let path$1 = BeginnerSolver.searchMacros(afterEdges, cornerActions, BeginnerSolver.orientedLastCornersGoal, undefined, 2);
  let cornerPath;
  if (path$1 !== undefined) {
    cornerPath = path$1;
  } else {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "SearchFailed",
        _0: "two-look OLL corner orientation"
      },
      Error: new Error()
    };
  }
  let match$1 = groupedPathWithLabels(afterEdges, cornerPath, describeCornerOrientation);
  return {
    alg: match[0].concat(match$1[0]),
    labels: match[1].concat(match$1[1]),
    state: match$1[2]
  };
}

function selectBeginnerPll(state, solved) {
  let cornerPll = BeginnerSolver.parseInternal("R' F R' B2 R F' R' B2 R2");
  let tPerm = BeginnerSolver.parseInternal("R U R' U' R' F R2 U' R' U' R U R' F'");
  let yPerm = BeginnerSolver.parseInternal("F R U' R' U' R U R' F' R U R' U' R' F R F'");
  let cornerAlgorithms = [
    cornerPll,
    MoveTransform.invert(cornerPll),
    tPerm,
    yPerm
  ];
  let cornerActions = rankedActions(BeginnerSolver.downTurns(solved).concat(Stdlib_Array.reduce(cornerAlgorithms, [], (all, algorithm) => all.concat([
    0,
    1,
    2,
    3
  ].map(y => BeginnerSolver.macroVariant(solved, algorithm, y))))));
  let path = BeginnerSolver.searchMacros(state, cornerActions, BeginnerSolver.positionedLastCornersGoal, undefined, 5);
  let cornerPath;
  if (path !== undefined) {
    cornerPath = path;
  } else {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "SearchFailed",
        _0: "two-look PLL corner permutation"
      },
      Error: new Error()
    };
  }
  let match = groupedPathWithLabels(state, cornerPath, describeCornerPermutation);
  let afterCorners = match[2];
  let ua = BeginnerSolver.parseInternal("R U' R U R U R U' R' U' R2");
  let edgeAlgorithms = [
    ua,
    MoveTransform.invert(ua),
    BeginnerSolver.parseInternal("M2 U M2 U2 M2 U M2"),
    BeginnerSolver.parseInternal("M2 U M2 U M' U2 M2 U2 M' U2")
  ];
  let edgeActions = rankedActions(BeginnerSolver.downTurns(solved).concat(Stdlib_Array.reduce(edgeAlgorithms, [], (all, algorithm) => all.concat([
    0,
    1,
    2,
    3
  ].map(y => BeginnerSolver.macroVariant(solved, algorithm, y))))));
  let path$1 = BeginnerSolver.searchMacros(afterCorners, edgeActions, BeginnerSolver.solvedCubiesGoal, undefined, 4);
  let edgePath;
  if (path$1 !== undefined) {
    edgePath = path$1;
  } else {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: {
        TAG: "SearchFailed",
        _0: "two-look PLL edge permutation"
      },
      Error: new Error()
    };
  }
  let match$1 = groupedPathWithLabels(afterCorners, edgePath, describeEdgePermutation);
  return {
    alg: match[0].concat(match$1[0]),
    labels: match[1].concat(match$1[1]),
    state: match$1[2]
  };
}

function splitSelectionAtGoal(state, solved, selection, isGoal) {
  let cursor = state;
  let splitGroups = {
    contents: isGoal(state) ? 0 : -1
  };
  for (let index = 0, index_finish = selection.labels.length; index < index_finish; ++index) {
    if (splitGroups.contents === -1) {
      let group = [
        selection.alg[(index << 1)],
        selection.alg[(index << 1) + 1 | 0]
      ];
      let transition = BeginnerSolver.transitionForAlg(solved, group);
      cursor = BeginnerSolver.applyCubie(cursor, transition);
      if (isGoal(cursor)) {
        splitGroups.contents = index + 1 | 0;
      }
    }
  }
  if (splitGroups.contents === -1) {
    throw {
      RE_EXN_ID: BuildFailure,
      _1: "VerificationFailed",
      Error: new Error()
    };
  }
  let splitUnits = (splitGroups.contents << 1);
  let firstAlg = [];
  let secondAlg = [];
  selection.alg.forEach((unit, index) => {
    if (index < splitUnits) {
      firstAlg.push(unit);
    } else {
      secondAlg.push(unit);
    }
  });
  let firstLabels = [];
  let secondLabels = [];
  selection.labels.forEach((label, index) => {
    if (index < splitGroups.contents) {
      firstLabels.push(label);
    } else {
      secondLabels.push(label);
    }
  });
  return [
    {
      alg: firstAlg,
      labels: firstLabels,
      state: cursor
    },
    {
      alg: secondAlg,
      labels: secondLabels,
      state: selection.state
    }
  ];
}

function layerPlanKey(state, pieces, completed) {
  return BeginnerSolver.fullKey(state) + "|" + pieces.map(piece => {
    if (completed.some(value => Primitive_object.equal(value, piece))) {
      return "1";
    } else {
      return "0";
    }
  }).join("");
}

function planLayerPiecesFrom(state, pieces, completed, baseCorners, baseEdges, corners, atomics, labels, failed) {
  if (completed.length === pieces.length) {
    return [];
  }
  let key = layerPlanKey(state, pieces, completed);
  if (failed[key] !== undefined) {
    return;
  }
  let candidates = [];
  pieces.forEach((piece, labelIndex) => {
    if (completed.some(value => value === piece)) {
      return;
    }
    let targetCorners = corners ? baseCorners.concat(completed).concat([piece]) : baseCorners;
    let targetEdges = corners ? baseEdges : baseEdges.concat(completed).concat([piece]);
    let path = BeginnerSolver.searchAtomicWithLimit(state, targetCorners, targetEdges, rankedActions(atomics), 12, 600000);
    if (path === undefined) {
      return;
    }
    let alg = MoveTransform.rotate(BeginnerSolver.flattenActions(path), "X", 2);
    let score = physicalCost(alg).total;
    candidates.push({
      pair: piece,
      path: path,
      score: score,
      label: labels[labelIndex]
    });
  });
  candidates.sort(comparePairs);
  let result;
  for (let index = 0, index_finish = candidates.length; index < index_finish; ++index) {
    if (result === undefined) {
      let selected = candidates[index];
      let nextState = applyPath(state, selected.path);
      let rest = planLayerPiecesFrom(nextState, pieces, completed.concat([selected.pair]), baseCorners, baseEdges, corners, atomics, labels, failed);
      if (rest !== undefined) {
        result = [selected].concat(rest);
      }
    }
  }
  if (result === undefined) {
    failed[key] = true;
  }
  return result;
}

function planLayerPieces(state, pieces, baseCorners, baseEdges, corners, atomics, labels) {
  let plan = planLayerPiecesFrom(state, pieces, [], baseCorners, baseEdges, corners, atomics, labels, {});
  if (plan !== undefined) {
    return [
      plan,
      Stdlib_Array.reduce(plan, state, (current, selected) => applyPath(current, selected.path))
    ];
  }
  throw {
    RE_EXN_ID: BuildFailure,
    _1: {
      TAG: "SearchFailed",
      _0: "optimized layer-by-layer insertion"
    },
    Error: new Error()
  };
}

function solveLevel(input, level) {
  try {
    if (input.size !== 3) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: input.size
        },
        Error: new Error()
      };
    }
    let error = PieceReducer.reduce(input);
    if (error.TAG !== "Ok") {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: error._0
        },
        Error: new Error()
      };
    }
    let value = BeginnerSolver.orientFrame(input);
    let match;
    if (value !== undefined) {
      match = value;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "centre-frame normalization"
        },
        Error: new Error()
      };
    }
    let frameAlg = match[1];
    let state = StateTypes.solved(3);
    let solved;
    if (state.TAG === "Ok") {
      solved = state._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: 3
        },
        Error: new Error()
      };
    }
    let pieces = PieceReducer.reduce(match[0]);
    let start;
    if (pieces.TAG === "Ok") {
      start = pieces._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: pieces._0
        },
        Error: new Error()
      };
    }
    let atomics = BeginnerSolver.atomicActions(solved);
    let current = {
      contents: start
    };
    let match$1 = cachedCaseLibraries(solved);
    let crossCandidate;
    let exit = 0;
    switch (level) {
      case "Beginner" :
      case "Full" :
        exit = 1;
        break;
      case "Advanced" :
        crossCandidate = selectCross(current.contents, atomics);
        break;
    }
    if (exit === 1) {
      let path = BeginnerSolver.searchAtomic(current.contents, [], [
        0,
        1,
        2,
        3
      ], rankedActions(atomics), 8);
      crossCandidate = path !== undefined ? ({
          path: path,
          candidates: 1
        }) : undefined;
    }
    let crossSelection;
    if (crossCandidate !== undefined) {
      crossSelection = crossCandidate;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "a move-optimized white cross"
        },
        Error: new Error()
      };
    }
    let crossPath = crossSelection.path;
    current.contents = applyPath(current.contents, crossPath);
    if (!BeginnerSolver.lockedGoal(current.contents, [], [
        0,
        1,
        2,
        3
      ])) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let fastF2lPlan = planF2l(current.contents, [], atomics, 11, 180000, false, level === "Advanced" ? 3 : 1, {});
    let mediumF2lPlan = () => planF2l(current.contents, [], atomics, 12, 300000, true, 2, {});
    let f2lPlan;
    if (fastF2lPlan !== undefined) {
      f2lPlan = fastF2lPlan;
    } else {
      let plan = mediumF2lPlan();
      if (plan !== undefined) {
        f2lPlan = plan;
      } else {
        let plan$1 = planF2l(current.contents, [], atomics, 12, 600000, true, 4, {});
        if (plan$1 !== undefined) {
          f2lPlan = plan$1;
        } else {
          throw {
            RE_EXN_ID: BuildFailure,
            _1: {
              TAG: "SearchFailed",
              _0: "four locked F2L corner-edge pairs"
            },
            Error: new Error()
          };
        }
      }
    }
    let f2lAlg = {
      contents: []
    };
    let f2lLabels = [];
    let completedPairs = [];
    f2lPlan.forEach(selected => {
      current.contents = applyPath(current.contents, selected.path);
      completedPairs.push(selected.pair);
      let lockedEdges = [
        0,
        1,
        2,
        3
      ].concat(completedPairs.map(pair => 8 + pair | 0));
      if (!BeginnerSolver.lockedGoal(current.contents, completedPairs, lockedEdges)) {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: "VerificationFailed",
          Error: new Error()
        };
      }
      f2lAlg.contents = f2lAlg.contents.concat(BeginnerSolver.groupedSequence(BeginnerSolver.flattenActions(selected.path)));
      f2lLabels.push(selected.label);
    });
    if (!BeginnerSolver.firstTwoLayersGoal(current.contents)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let ollSelection;
    let exit$1 = 0;
    switch (level) {
      case "Beginner" :
        ollSelection = selectBeginnerOll(current.contents, solved);
        break;
      case "Full" :
      case "Advanced" :
        exit$1 = 1;
        break;
    }
    if (exit$1 === 1) {
      let selection = selectOll(current.contents, solved, match$1[0]);
      if (selection !== undefined) {
        ollSelection = selection;
      } else {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: {
            TAG: "SearchFailed",
            _0: "one-look OLL recognition"
          },
          Error: new Error()
        };
      }
    }
    current.contents = ollSelection.state;
    if (!BeginnerSolver.orientedLastCornersGoal(current.contents)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let pllSelection;
    let exit$2 = 0;
    switch (level) {
      case "Beginner" :
        pllSelection = selectBeginnerPll(current.contents, solved);
        break;
      case "Full" :
      case "Advanced" :
        exit$2 = 1;
        break;
    }
    if (exit$2 === 1) {
      let selection$1 = selectPll(current.contents, solved);
      if (selection$1 !== undefined) {
        pllSelection = selection$1;
      } else {
        throw {
          RE_EXN_ID: BuildFailure,
          _1: {
            TAG: "SearchFailed",
            _0: "one-look PLL recognition"
          },
          Error: new Error()
        };
      }
    }
    current.contents = pllSelection.state;
    if (!BeginnerSolver.solvedCubiesGoal(current.contents)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let hasPhysicalWork = crossPath.length !== 0 || f2lAlg.contents.length !== 0 || ollSelection.alg.length !== 0 || pllSelection.alg.length !== 0;
    let whiteDown = [{
        desc: {
          TAG: "Move",
          _0: {
            TAG: "Rotation",
            _0: "X"
          },
          _1: 2
        },
        loc: generatedLoc
      }];
    let crossCore = BeginnerSolver.flattenActions(crossPath);
    let crossAlg = BeginnerSolver.groupedSequence(frameAlg);
    let crossLabels = [];
    if (frameAlg.length !== 0) {
      crossLabels.push("Normalize the centre frame before planning the cross.");
    }
    if (hasPhysicalWork) {
      crossAlg = crossAlg.concat(BeginnerSolver.groupedSequence(whiteDown));
      crossLabels.push("Regrip once so white stays on the bottom for CFOP.");
      if (crossCore.length !== 0) {
        crossAlg = crossAlg.concat(BeginnerSolver.groupedSequence(MoveTransform.rotate(crossCore, "X", 2)));
        let planning = level === "Advanced" ? ` after ranking ` + crossSelection.candidates.toString() + ` candidate plans` : "";
        crossLabels.push(`Build the move-optimized white cross in ` + crossPath.length.toString() + ` moves` + planning + `.`);
      }
    }
    let transformedF2l = MoveTransform.rotate(f2lAlg.contents, "X", 2);
    let transformedOll = MoveTransform.rotate(ollSelection.alg, "X", 2);
    let transformedPll = MoveTransform.rotate(pllSelection.alg, "X", 2);
    let pllAlg = hasPhysicalWork ? transformedPll.concat(BeginnerSolver.groupedSequence(whiteDown)) : transformedPll;
    let pllLabels = pllSelection.labels.map(label => label);
    if (hasPhysicalWork) {
      pllLabels.push("Restore the canonical white-up export frame.");
    }
    let ollTitle = level === "Beginner" ? "Two-Look OLL" : "One-Look OLL";
    let ollInstruction = level === "Beginner" ? "Orient last-layer edges first, then recognize and orient the corners." : "Recognize one of all 57 OLL cases and orient the complete last layer in one algorithm.";
    let pllTitle = level === "Beginner" ? "Two-Look PLL" : "One-Look PLL";
    let pllInstruction = level === "Beginner" ? "Permute last-layer corners first, then solve the remaining edge cycle." : "Recognize one of all 21 PLL cases and permute the complete last layer in one algorithm.";
    let phases = [
      phase(1, "Cross", "Plan the complete white-bottom cross before execution and minimize physical turns.", withPhasePause(crossAlg), crossLabels),
      phase(2, "F2L Pairs", "Solve four corner-edge pairs together while preserving the cross and every completed slot.", withPhasePause(transformedF2l), f2lLabels),
      phase(3, ollTitle, ollInstruction, withPhasePause(transformedOll), ollSelection.labels),
      phase(4, pllTitle, pllInstruction, pllAlg, pllLabels)
    ];
    let annotated = Stdlib_Array.reduce(phases, [], (output, item) => output.concat([commentForPhase(item)]).concat(item.alg));
    let error$1 = MoveExecutor.expand(annotated);
    let moveCount;
    if (error$1.TAG === "Ok") {
      moveCount = error$1._0.filter(step => {
        let match = step.move;
        switch (match.TAG) {
          case "FaceTurn" :
          case "SliceTurn" :
            return true;
          case "Rotation" :
            return false;
        }
      }).length;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$1._0
        },
        Error: new Error()
      };
    }
    let error$2 = MoveExecutor.applyAlg(input, annotated);
    let result;
    if (error$2.TAG === "Ok") {
      result = error$2._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$2._0
        },
        Error: new Error()
      };
    }
    if (!BeginnerSolver.statesEqual(result, solved)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    return {
      TAG: "Ok",
      _0: {
        phases: phases,
        alg: annotated,
        moveCount: moveCount
      }
    };
  } catch (raw_error) {
    let error$3 = Primitive_exceptions.internalToException(raw_error);
    if (error$3.RE_EXN_ID === BuildFailure) {
      return {
        TAG: "Error",
        _0: error$3._1
      };
    }
    throw error$3;
  }
}

function solveAdvancedLbl(input) {
  try {
    if (input.size !== 3) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: input.size
        },
        Error: new Error()
      };
    }
    let error = PieceReducer.reduce(input);
    if (error.TAG !== "Ok") {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: error._0
        },
        Error: new Error()
      };
    }
    let value = BeginnerSolver.orientFrame(input);
    let match;
    if (value !== undefined) {
      match = value;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "centre-frame normalization"
        },
        Error: new Error()
      };
    }
    let frameAlg = match[1];
    let state = StateTypes.solved(3);
    let solved;
    if (state.TAG === "Ok") {
      solved = state._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "UnsupportedSize",
          _0: 3
        },
        Error: new Error()
      };
    }
    let pieces = PieceReducer.reduce(match[0]);
    let start;
    if (pieces.TAG === "Ok") {
      start = pieces._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "InvalidState",
          _0: pieces._0
        },
        Error: new Error()
      };
    }
    let atomics = BeginnerSolver.atomicActions(solved);
    let current = start;
    let selection = selectCross(current, atomics);
    let crossSelection;
    if (selection !== undefined) {
      crossSelection = selection;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "SearchFailed",
          _0: "a direct white cross"
        },
        Error: new Error()
      };
    }
    current = applyPath(current, crossSelection.path);
    if (!BeginnerSolver.lockedGoal(current, [], [
        0,
        1,
        2,
        3
      ])) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let cornerNames = [
      "Insert the white–green–red first-layer corner with one optimized trigger.",
      "Insert the white–green–orange first-layer corner with one optimized trigger.",
      "Insert the white–blue–orange first-layer corner with one optimized trigger.",
      "Insert the white–blue–red first-layer corner with one optimized trigger."
    ];
    let match$1 = planLayerPieces(current, [
      0,
      1,
      2,
      3
    ], [], [
      0,
      1,
      2,
      3
    ], true, atomics, cornerNames);
    let cornerPlan = match$1[0];
    current = match$1[1];
    if (!BeginnerSolver.lockedGoal(current, [
        0,
        1,
        2,
        3
      ], [
        0,
        1,
        2,
        3
      ])) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let middleNames = [
      "Insert the green–red middle edge with an optimized left/right trigger.",
      "Insert the green–orange middle edge with an optimized left/right trigger.",
      "Insert the blue–orange middle edge with an optimized left/right trigger.",
      "Insert the blue–red middle edge with an optimized left/right trigger."
    ];
    let match$2 = planLayerPieces(current, [
      8,
      9,
      10,
      11
    ], [
      0,
      1,
      2,
      3
    ], [
      0,
      1,
      2,
      3
    ], false, atomics, middleNames);
    let middlePlan = match$2[0];
    current = match$2[1];
    if (!BeginnerSolver.firstTwoLayersGoal(current)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let combinedOll = selectBeginnerOll(current, solved);
    let match$3 = splitSelectionAtGoal(current, solved, combinedOll, BeginnerSolver.orientedLastEdgesGoal);
    let ollCorners = match$3[1];
    let ollEdges = match$3[0];
    current = combinedOll.state;
    if (!BeginnerSolver.orientedLastCornersGoal(current)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let combinedPll = selectBeginnerPll(current, solved);
    let match$4 = splitSelectionAtGoal(current, solved, combinedPll, BeginnerSolver.positionedLastCornersGoal);
    let pllEdges = match$4[1];
    let pllCorners = match$4[0];
    current = combinedPll.state;
    if (!BeginnerSolver.solvedCubiesGoal(current)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    let cornerAlg = Stdlib_Array.reduce(cornerPlan, [], (output, selected) => output.concat(BeginnerSolver.groupedSequence(BeginnerSolver.flattenActions(selected.path))));
    let middleAlg = Stdlib_Array.reduce(middlePlan, [], (output, selected) => output.concat(BeginnerSolver.groupedSequence(BeginnerSolver.flattenActions(selected.path))));
    let hasPhysicalWork = crossSelection.path.length !== 0 || cornerAlg.length !== 0 || middleAlg.length !== 0 || combinedOll.alg.length !== 0 || combinedPll.alg.length !== 0;
    let whiteDown = [{
        desc: {
          TAG: "Move",
          _0: {
            TAG: "Rotation",
            _0: "X"
          },
          _1: 2
        },
        loc: generatedLoc
      }];
    let crossCore = BeginnerSolver.flattenActions(crossSelection.path);
    let crossAlg = BeginnerSolver.groupedSequence(frameAlg);
    let crossLabels = [];
    if (frameAlg.length !== 0) {
      crossLabels.push("Normalize the centre frame before planning the cross.");
    }
    if (hasPhysicalWork) {
      crossAlg = crossAlg.concat(BeginnerSolver.groupedSequence(whiteDown));
      crossLabels.push("Regrip once so white stays on the bottom.");
      if (crossCore.length !== 0) {
        crossAlg = crossAlg.concat(BeginnerSolver.groupedSequence(MoveTransform.rotate(crossCore, "X", 2)));
        crossLabels.push(`Build the direct white cross in ` + crossSelection.path.length.toString() + ` moves.`);
      }
    }
    let finalEdges = hasPhysicalWork ? MoveTransform.rotate(pllEdges.alg, "X", 2).concat(BeginnerSolver.groupedSequence(whiteDown)) : MoveTransform.rotate(pllEdges.alg, "X", 2);
    let finalLabels = pllEdges.labels.map(label => label);
    if (hasPhysicalWork) {
      finalLabels.push("Restore the canonical white-up export frame.");
    }
    let phases = [
      phase(1, "Direct White Cross", "Build the complete white cross directly on the bottom without making a daisy.", withPhasePause(crossAlg), crossLabels),
      phase(2, "First-Layer Corners", "Insert each white corner once while preserving the direct cross.", withPhasePause(MoveTransform.rotate(cornerAlg, "X", 2)), cornerPlan.map(candidate => candidate.label)),
      phase(3, "Middle-Layer Edges", "Insert each middle edge with an efficient trigger while preserving the first layer.", withPhasePause(MoveTransform.rotate(middleAlg, "X", 2)), middlePlan.map(candidate => candidate.label)),
      phase(4, "Yellow Cross", "Recognize the dot, line, or hook and orient all four last-layer edges.", withPhasePause(MoveTransform.rotate(ollEdges.alg, "X", 2)), ollEdges.labels),
      phase(5, "Orient Yellow Corners", "Recognize the corner case and orient the yellow face without repeated Sune spam.", withPhasePause(MoveTransform.rotate(ollCorners.alg, "X", 2)), ollCorners.labels),
      phase(6, "Permute Yellow Corners", "Recognize headlights or the diagonal case and position all last-layer corners.", withPhasePause(MoveTransform.rotate(pllCorners.alg, "X", 2)), pllCorners.labels),
      phase(7, "Permute Yellow Edges", "Finish with the recognized Ua, Ub, H, or Z edge permutation.", finalEdges, finalLabels)
    ];
    let annotated = Stdlib_Array.reduce(phases, [], (output, item) => output.concat([{
        desc: {
          TAG: "BlockComment",
          _0: ` ADVANCED LBL ` + item.number.toString() + `: ` + item.title + ` — ` + item.instruction + ` `
        },
        loc: generatedLoc
      }]).concat(item.alg));
    let error$1 = MoveExecutor.expand(annotated);
    let moveCount;
    if (error$1.TAG === "Ok") {
      moveCount = error$1._0.filter(step => {
        let match = step.move;
        switch (match.TAG) {
          case "FaceTurn" :
          case "SliceTurn" :
            return true;
          case "Rotation" :
            return false;
        }
      }).length;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$1._0
        },
        Error: new Error()
      };
    }
    let error$2 = MoveExecutor.applyAlg(input, annotated);
    let result;
    if (error$2.TAG === "Ok") {
      result = error$2._0;
    } else {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: {
          TAG: "ExpansionFailed",
          _0: error$2._0
        },
        Error: new Error()
      };
    }
    if (!BeginnerSolver.statesEqual(result, solved)) {
      throw {
        RE_EXN_ID: BuildFailure,
        _1: "VerificationFailed",
        Error: new Error()
      };
    }
    return {
      TAG: "Ok",
      _0: {
        phases: phases,
        alg: annotated,
        moveCount: moveCount
      }
    };
  } catch (raw_error) {
    let error$3 = Primitive_exceptions.internalToException(raw_error);
    if (error$3.RE_EXN_ID === BuildFailure) {
      return {
        TAG: "Error",
        _0: error$3._1
      };
    }
    throw error$3;
  }
}

function solveBeginner(input) {
  return solveLevel(input, "Beginner");
}

function solveFull(input) {
  return solveLevel(input, "Full");
}

function solveAdvanced(input) {
  return solveLevel(input, "Advanced");
}

let describeError = BeginnerSolver.describeError;

let solve = solveAdvanced;

export {
  BuildFailure,
  generatedLoc,
  located,
  describeError,
  phase,
  commentForPhase,
  grouped,
  withPhasePause,
  applyPath,
  physicalCost,
  physicalScore,
  rankedActions,
  biasedActions,
  crossPathKey,
  crossCandidateScore,
  selectCross,
  actionIsAlignment,
  pairNames,
  cornerSlots,
  edgeSlots,
  physicalPosition,
  describePairCase,
  addPositionFaces,
  f2lFaces,
  findPairCandidate,
  comparePairs,
  f2lPlanScore,
  f2lPlanKey,
  planF2l,
  lastLayerSlots,
  orientationKey,
  permutationKey,
  downAction,
  applyDown,
  normalizedLastLayerKey,
  caseAction,
  inverseSetup,
  appendActionGroup,
  validateCaseLibraries,
  caseLibraryCache,
  cachedCaseLibraries,
  selectOll,
  selectPll,
  describeEdgeOrientation,
  describeCornerOrientation,
  describeCornerPermutation,
  describeEdgePermutation,
  groupedPathWithLabels,
  selectBeginnerOll,
  selectBeginnerPll,
  splitSelectionAtGoal,
  layerPlanKey,
  planLayerPiecesFrom,
  planLayerPieces,
  solveLevel,
  solveAdvancedLbl,
  solveBeginner,
  solveFull,
  solveAdvanced,
  solve,
}
/* No side effect */
