// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Canonical2x2 from "./Canonical2x2.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Optimal2x2Table from "./Optimal2x2Table.res.mjs";

let preparedTables = undefined;
let tablesPromise = undefined;
;

let hasPreparedTables = (function() {
  return preparedTables !== undefined;
});

let prepareTables = (function() {
  if (preparedTables) return Promise.resolve(preparedTables);
  if (!tablesPromise) {
    tablesPromise = fetch(Optimal2x2Table.optimal_2X2_TABLE_URL).then(async response => {
      if (!response.ok) throw new Error("The optimal 2×2 solver table could not be downloaded.");
      preparedTables = Optimal2x2Table.decodeOptimal2x2Tables(await response.arrayBuffer());
      return preparedTables;
    }).catch(error => {
      tablesPromise = undefined;
      throw error;
    });
  }
  return tablesPromise;
});

let getCubeStateSize = (state => state && typeof state === 'object' ? state.size : undefined);

function cubies(state) {
  if (getCubeStateSize(state) !== 2) {
    Pervasives.failwith("The optimal solver supports only 2×2 cubes.");
  }
  let reduced = PieceReducer.reduce(state);
  if (reduced.TAG !== "Ok") {
    return Pervasives.failwith(PieceReducer.describeError(reduced._0));
  }
  let reduced$1 = reduced._0;
  return {
    cp: reduced$1.cp,
    co: reduced$1.co
  };
}

function reconstruct(pieces) {
  let pieceState_cp = pieces.cp;
  let pieceState_co = pieces.co;
  let pieceState_ep = [];
  let pieceState_eo = [];
  let pieceState = {
    size: 2,
    cp: pieceState_cp,
    co: pieceState_co,
    ep: pieceState_ep,
    eo: pieceState_eo
  };
  let st = PieceReducer.reconstruct(pieceState);
  if (st.TAG === "Ok") {
    return st._0;
  } else {
    return Pervasives.failwith(PieceReducer.describeError(st._0));
  }
}

function solutionMoves(tables, initial) {
  let current = initial;
  let distance = Optimal2x2Table.packedDistance(tables.distance, Canonical2x2.coordinateForCubies(current));
  let moves = [];
  let transforms = Canonical2x2.transformations();
  while (distance > 0) {
    let found = false;
    let move = 0;
    while (move < 18 && !found) {
      let m = move;
      let trans = Stdlib_Option.getOr(transforms[m], Canonical2x2.identity());
      let next = Canonical2x2.applyTransform(current, trans);
      let nextCoord = Canonical2x2.coordinateForCubies(next);
      if (Optimal2x2Table.packedDistance(tables.distance, nextCoord) === (distance - 1 | 0)) {
        current = next;
        moves.push(m);
        distance = distance - 1 | 0;
        found = true;
      }
      move = move + 1 | 0;
    };
    if (!found) {
      Pervasives.failwith("The exact optimal 2×2 table could not reconstruct a solution.");
    }
  };
  return {
    moves: moves,
    final: current
  };
}

let getExactCoordinates = ((() => {
  const cache = new WeakMap();
  return function(tables) {
    const existing = cache.get(tables);
    if (existing) return existing;
    const indexed = {three: [], four: []};
    for (let coordinate = 0; coordinate < 3674160; coordinate += 1) {
      const distance = Optimal2x2Table.packedDistance(tables.distance, coordinate);
      if (distance === 3) indexed.three.push(coordinate);
      else if (distance === 4) indexed.four.push(coordinate);
    }
    cache.set(tables, indexed);
    return indexed;
  };
})());

let randomCanonicalCoordinate = (function(random) {
  const fn = typeof random === 'function' ? random : Math.random;
  const value = fn();
  const bounded = Number.isFinite(value) ? Math.min(Math.max(value, 0), 0.999999999999) : 0;
  return Math.floor(bounded * 3674160);
});

let randomStateScrambleFromTables = (function(tables, random, difficulty) {
  const rand = typeof random === 'function' ? random : Math.random;
  const diff = typeof difficulty === 'string' ? difficulty : "5+";

  let coordinate;
  if (diff === "any") {
    coordinate = randomCanonicalCoordinate(rand);
  } else if (diff === "3" || diff === "4") {
    const coordinates = getExactCoordinates(tables);
    const list = diff === "3" ? coordinates.three : coordinates.four;
    const value = rand();
    const bounded = Number.isFinite(value) ? Math.min(Math.max(value, 0), 0.999999999999) : 0;
    coordinate = list[Math.floor(bounded * list.length)];
  } else {
    coordinate = randomCanonicalCoordinate(rand);
    while (Optimal2x2Table.packedDistance(tables.distance, coordinate) < 5) {
      coordinate = randomCanonicalCoordinate(rand);
    }
  }

  const pieces = Canonical2x2.cubiesForCoordinate(coordinate);
  const state = reconstruct(pieces);
  const solution = solutionMoves(tables, pieces);
  const solveTokens = [
    ...solution.moves.map(m => Canonical2x2.moveTokens[m]),
    ...Canonical2x2.rotationTokensToIdentity(solution.final)
  ];
  const scrambleTokens = solveTokens.slice().reverse().map(token => {
    if (token.endsWith("2")) return token;
    const base = token.endsWith("'") ? token.slice(0, -1) : token;
    return token.endsWith("'") ? base : base + "'";
  });
  const parsed = MoveParser.parse(2, scrambleTokens.join(" "));
  if (parsed.TAG !== "Ok") throw new Error("The random 2×2 scramble could not be encoded.");
  const replay = MoveExecutor.applyAlg(
    reconstruct({cp: Array.from({length: 8}, (_, index) => index), co: Array(8).fill(0)}),
    parsed._0
  );
  if (replay.TAG !== "Ok" || Canonical2x2.coordinateForCubies(cubies(replay._0)) !== coordinate) {
    throw new Error("The random 2×2 scramble did not replay to the sampled state.");
  }
  return {coordinate, state, scramble: parsed._0, moveCount: solution.moves.length};
});

let randomStateScramble = (async function(random, difficulty) {
  const tables = await prepareTables();
  return randomStateScrambleFromTables(tables, random, difficulty);
});

let solve = (async function(state) {
  const tables = await prepareTables();
  const pieces = cubies(state);
  const solution = solutionMoves(tables, pieces);
  const moves = solution.moves;
  const parsed = MoveParser.parse(2, moves.map(m => Canonical2x2.moveTokens[m]).join(" "));
  if (parsed.TAG !== "Ok") throw new Error("The optimal 2×2 solution could not be encoded.");
  const replay = MoveExecutor.applyAlg(state, parsed._0);
  const final = replay.TAG === "Ok" ? cubies(replay._0) : null;
  if (!final || Canonical2x2.coordinateForCubies(final) !== 0) {
    throw new Error("The optimal 2×2 solution failed verification.");
  }
  return {alg: parsed._0, moveCount: moves.length};
});

let _moveParser = MoveParser.parse;

let _moveExecutor = MoveExecutor.applyAlg;

export {
  _moveParser,
  _moveExecutor,
  hasPreparedTables,
  prepareTables,
  getCubeStateSize,
  cubies,
  reconstruct,
  solutionMoves,
  getExactCoordinates,
  randomCanonicalCoordinate,
  randomStateScrambleFromTables,
  randomStateScramble,
  solve,
}
/*  Not a pure module */
