// Generated by ReScript, PLEASE EDIT WITH CARE


let coll = [
  {
    id: "AS-1",
    family: "Anti-Sune",
    algorithm: "R' U' R U' R' U2 R"
  },
  {
    id: "AS-2",
    family: "Anti-Sune",
    algorithm: "U R' U' R U' R' U R' D' R U R' D R2"
  },
  {
    id: "AS-3",
    family: "Anti-Sune",
    algorithm: "U2 R2 D R' U2 R D' R2 U' R U' R'"
  },
  {
    id: "AS-4",
    family: "Anti-Sune",
    algorithm: "U2 R' U' R U' R2 D' R U2 R' D R2"
  },
  {
    id: "AS-5",
    family: "Anti-Sune",
    algorithm: "U2 r' F R F' r U R'"
  },
  {
    id: "AS-6",
    family: "Anti-Sune",
    algorithm: "R U R' F' R U2 R' U' R U' R' F R U' R'"
  },
  {
    id: "S-1",
    family: "Sune",
    algorithm: "R U R' U R U2 R'"
  },
  {
    id: "S-2",
    family: "Sune",
    algorithm: "U2 R U R' U R2 D R' U2 R D' R2"
  },
  {
    id: "S-3",
    family: "Sune",
    algorithm: "L' R U R' U' L U2 R U2 R'"
  },
  {
    id: "S-4",
    family: "Sune",
    algorithm: "U' R U R' U R U' R D R' U' R D' R2"
  },
  {
    id: "S-5",
    family: "Sune",
    algorithm: "R U' L' U R' U' L"
  },
  {
    id: "S-6",
    family: "Sune",
    algorithm: "U2 R U R' F' R U R' U R U2 R' F R U' R'"
  },
  {
    id: "L-1",
    family: "L",
    algorithm: "U' R U R' U R U' R' U R U' R' U R U2 R'"
  },
  {
    id: "L-2",
    family: "L",
    algorithm: "R' U2 R' D' R U2 R' D R2"
  },
  {
    id: "L-3",
    family: "L",
    algorithm: "U R U2 R D R' U2 R D' R2"
  },
  {
    id: "L-4",
    family: "L",
    algorithm: "U F R' F' r U R U' r'"
  },
  {
    id: "L-5",
    family: "L",
    algorithm: "U2 F' r U R' U' r' F R"
  },
  {
    id: "L-6",
    family: "L",
    algorithm: "U r U2 R2 F R F' R U2 r'"
  },
  {
    id: "U-1",
    family: "U",
    algorithm: "R' U' R U' R' U2 R2 U R' U R U2 R'"
  },
  {
    id: "U-2",
    family: "U",
    algorithm: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R"
  },
  {
    id: "U-3",
    family: "U",
    algorithm: "U2 R2 D R' U2 R D' R' U2 R'"
  },
  {
    id: "U-4",
    family: "U",
    algorithm: "F R U' R' U R U R' U R U' R' F'"
  },
  {
    id: "U-5",
    family: "U",
    algorithm: "R2 D' R U2 R' D R U2 R"
  },
  {
    id: "U-6",
    family: "U",
    algorithm: "R2 D' R U R' D R U R U' R' U' R"
  },
  {
    id: "T-1",
    family: "T",
    algorithm: "R U2 R' U' R U' R2 U2 R U R' U R"
  },
  {
    id: "T-2",
    family: "T",
    algorithm: "R' U R U2 R' L' U R U' L"
  },
  {
    id: "T-3",
    family: "T",
    algorithm: "U R' F' r U R U' r' F"
  },
  {
    id: "T-4",
    family: "T",
    algorithm: "U2 F R U R' U' R U' R' U' R U R' F'"
  },
  {
    id: "T-5",
    family: "T",
    algorithm: "U' r U R' U' r' F R F'"
  },
  {
    id: "T-6",
    family: "T",
    algorithm: "R' U R2 D r' U2 r D' R2 U' R"
  },
  {
    id: "Pi-1",
    family: "Pi",
    algorithm: "R' U2 R2 U R2 U R2 U2 R'"
  },
  {
    id: "Pi-2",
    family: "Pi",
    algorithm: "U F U R U' R' U R U' R2 F' R U R U' R'"
  },
  {
    id: "Pi-3",
    family: "Pi",
    algorithm: "R' U' F' R U R' U' R' F R2 U2 R' U2 R"
  },
  {
    id: "Pi-4",
    family: "Pi",
    algorithm: "R U R' U' R' F R2 U R' U' R U R' U' F'"
  },
  {
    id: "Pi-5",
    family: "Pi",
    algorithm: "U' R U R' U F' R U2 R' U2 R' F R"
  },
  {
    id: "Pi-6",
    family: "Pi",
    algorithm: "U' r U R' U R' F R F' R U' R' U R U2 r'"
  },
  {
    id: "H-1",
    family: "H",
    algorithm: "R U R' U R U' R' U R U2 R'"
  },
  {
    id: "H-2",
    family: "H",
    algorithm: "F R U' R' U R U2 R' U' R U R' U' F'"
  },
  {
    id: "H-3",
    family: "H",
    algorithm: "R U R' U R U L' U R' U' L"
  },
  {
    id: "H-4",
    family: "H",
    algorithm: "U F R U R' U' R U R' U' R U R' U' F'"
  }
];

export {
  coll,
}
/* No side effect */
