// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as FaceletCodec from "../State/FaceletCodec.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as MoveTransform from "../Move/MoveTransform.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let faces = [
  "U",
  "R",
  "F",
  "D",
  "L",
  "B"
];

let centreIndices = [
  5,
  6,
  9,
  10
];

let edgePairs = [
  [
    1,
    2
  ],
  [
    7,
    11
  ],
  [
    13,
    14
  ],
  [
    4,
    8
  ]
];

let edgeNames = [
  "top",
  "right",
  "bottom",
  "left"
];

let reducedFacelets = [
  0,
  1,
  3,
  4,
  5,
  7,
  12,
  13,
  15
];

let dictValues = ((d => Object.values(d)));

let mapValues = ((m => Array.from(m.values())));

function get(arr, i) {
  return arr[i];
}

function set(arr, i, v) {
  arr[i] = v;
}

let isCubeState = (function(value) {
  return typeof value === "object" && value !== null && typeof value.size === "number" && Array.isArray(value.facelets);
});

function compactFacelets(state) {
  if (!isCubeState(state)) {
    return;
  }
  if (state.size !== 4) {
    return;
  }
  let compact = FaceletCodec.render(state);
  if (compact.length === 96) {
    return compact;
  }
}

function parseGuide(notation) {
  let alg = MoveParser.parseWithOptions(4, "Wide", "Modern", notation);
  if (alg.TAG === "Ok") {
    return alg._0;
  }
}

function centreValues(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return;
  }
  let chars = [];
  for (let faceIndex = 0; faceIndex <= 5; ++faceIndex) {
    for (let i = 0; i <= 3; ++i) {
      let idx = (faceIndex << 4) + centreIndices[i] | 0;
      chars.push(compact.slice(idx, idx + 1 | 0));
    }
  }
  return chars.join("");
}

let frames = new Set();

let solved = StateTypes.solved(4);

let centreFrames;

if (solved.TAG === "Ok") {
  let solved$1 = solved._0;
  for (let x = 0; x <= 3; ++x) {
    for (let y = 0; y <= 3; ++y) {
      for (let z = 0; z <= 3; ++z) {
        let xStr = "x ".repeat(x);
        let yStr = "y ".repeat(y);
        let zStr = "z ".repeat(z);
        let rotAlg = parseGuide((xStr + yStr + zStr).trim());
        if (rotAlg !== undefined) {
          let rotated = MoveExecutor.applyAlg(solved$1, rotAlg);
          if (rotated.TAG === "Ok") {
            let frame = centreValues(rotated._0);
            if (frame !== undefined) {
              frames.add(frame);
            }
          }
        }
      }
    }
  }
  centreFrames = frames;
} else {
  centreFrames = frames;
}

function isCentreFrameValid(state) {
  let values = centreValues(state);
  if (values !== undefined) {
    return centreFrames.has(values);
  } else {
    return false;
  }
}

function inspectReduction4x4(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The reduction solver supports only complete 4×4 states."
      }
    };
  }
  let centres = [];
  let wingRows = [];
  for (let faceIndex = 0, faceIndex_finish = faces.length; faceIndex < faceIndex_finish; ++faceIndex) {
    let faceName = faces[faceIndex];
    let face = compact.slice((faceIndex << 4), ((faceIndex + 1 | 0) << 4));
    let c0 = face.slice(centreIndices[0], centreIndices[0] + 1 | 0);
    let c1 = face.slice(centreIndices[1], centreIndices[1] + 1 | 0);
    let c2 = face.slice(centreIndices[2], centreIndices[2] + 1 | 0);
    let c3 = face.slice(centreIndices[3], centreIndices[3] + 1 | 0);
    let centreComplete = c0 === c1 && c1 === c2 && c2 === c3;
    centres.push({
      face: faceName,
      complete: centreComplete
    });
    for (let edgeIndex = 0, edgeIndex_finish = edgePairs.length; edgeIndex < edgeIndex_finish; ++edgeIndex) {
      let match = edgePairs[edgeIndex];
      let p1 = match[1];
      let p0 = match[0];
      let edgeName = edgeNames[edgeIndex];
      let col0 = face.slice(p0, p0 + 1 | 0);
      let col1 = face.slice(p1, p1 + 1 | 0);
      wingRows.push({
        face: faceName,
        edge: edgeName,
        colours: [
          col0,
          col1
        ],
        complete: col0 === col1
      });
    }
  }
  let centreBlocksComplete = centres.filter(m => m.complete).length;
  let wingRowsPaired = wingRows.filter(m => m.complete).length;
  let centreFrameValid = isCentreFrameValid(state);
  let stage = centreBlocksComplete < faces.length || !centreFrameValid ? "centres" : (
      wingRowsPaired < wingRows.length ? "wings" : "reduced"
    );
  let nextGoal = !centreFrameValid && centreBlocksComplete === faces.length ? "Reposition the completed centre blocks into a valid U/R/F colour frame before wing pairing." : (
      stage === "centres" ? `Build centre blocks (` + centreBlocksComplete.toString() + `/6 complete).` : (
          stage === "wings" ? `Pair wing rows (` + wingRowsPaired.toString() + `/24 matched).` : "Reduction complete — ready for the 3×3 finish."
        )
    );
  return {
    TAG: "Ok",
    _0: {
      centres: centres,
      wingRows: wingRows,
      centreBlocksComplete: centreBlocksComplete,
      centreFrameValid: centreFrameValid,
      wingRowsPaired: wingRowsPaired,
      stage: stage,
      nextGoal: nextGoal
    }
  };
}

function centreProgressFor(values) {
  let blocks = 0;
  let score = 0;
  let fixed = 0;
  for (let faceIndex = 0, faceIndex_finish = faces.length; faceIndex < faceIndex_finish; ++faceIndex) {
    let faceName = faces[faceIndex];
    let c = [
      values.slice((faceIndex << 2), (faceIndex << 2) + 1 | 0),
      values.slice((faceIndex << 2) + 1 | 0, (faceIndex << 2) + 2 | 0),
      values.slice((faceIndex << 2) + 2 | 0, (faceIndex << 2) + 3 | 0),
      values.slice((faceIndex << 2) + 3 | 0, (faceIndex << 2) + 4 | 0)
    ];
    let counts = {};
    for (let i = 0; i <= 3; ++i) {
      let col = c[i];
      let n = counts[col];
      let cur = n !== undefined ? n + 1 | 0 : 1;
      counts[col] = cur;
      if (col === faceName) {
        fixed = fixed + 1 | 0;
      }
    }
    let largestGroup = {
      contents: 0
    };
    dictValues(counts).forEach(cnt => {
      if (cnt > largestGroup.contents) {
        largestGroup.contents = cnt;
        return;
      }
    });
    score = score + largestGroup.contents | 0;
    if (largestGroup.contents === 4) {
      blocks = blocks + 1 | 0;
    }
  }
  return {
    blocks: blocks,
    score: score,
    fixed: fixed
  };
}

let arr = [];

faces.forEach(face => {
  arr.push(face);
  arr.push(face + "'");
  arr.push(face + "2");
  arr.push("2" + face);
  arr.push("2" + face + "'");
  arr.push("2" + face + "2");
});

let locations = [];

faces.forEach(face => {
  let tmp;
  switch (face) {
    case "D" :
      tmp = "D";
      break;
    case "F" :
      tmp = "F";
      break;
    case "L" :
      tmp = "L";
      break;
    case "R" :
      tmp = "R";
      break;
    case "U" :
      tmp = "U";
      break;
    default:
      tmp = "B";
  }
  let faceIdx = StateTypes.storageIndex(tmp);
  centreIndices.forEach(idx => {
    locations.push((faceIdx << 4) + idx | 0);
  });
});

let locationToSlot = new Map();

locations.forEach((loc, slot) => {
  locationToSlot.set(loc, slot);
});

let moves = [];

arr.forEach(notation => {
  let alg = parseGuide(notation);
  if (alg === undefined) {
    return;
  }
  let rawReplay = (function(alg, storageOrder, centreIndices, locationToSlot, storageIndex) {
        var marker = {
          size: 4,
          facelets: storageOrder.map(function(_, faceIndex) {
            return Array.from({length: 16}, function(_, index) { return String(faceIndex * 16 + index); });
          })
        };
        var res = MoveExecutor.applyAlg(marker, alg);
        if (res.TAG === "Error") return null;
        var permutation = [];
        var faceNames = ["U", "R", "F", "D", "L", "B"];
        for (var f = 0; f < faceNames.length; f++) {
          var face = faceNames[f];
          var stIdx = storageIndex(face);
          for (var i = 0; i < centreIndices.length; i++) {
            var rawVal = Number(res._0.facelets[stIdx][centreIndices[i]]);
            var slot = locationToSlot.get(rawVal);
            if (slot === undefined) return null;
            permutation.push(slot);
          }
        }
        return permutation;
      })(alg, StateTypes.storageOrder, centreIndices, locationToSlot, StateTypes.storageIndex);
  if (!(rawReplay == null)) {
    moves.push({
      notation: notation,
      alg: alg,
      permutation: rawReplay
    });
    return;
  }
});

function applyCentreMove(values, move) {
  let chars = [];
  for (let i = 0, i_finish = move.permutation.length; i < i_finish; ++i) {
    let source = move.permutation[i];
    chars.push(values.slice(source, source + 1 | 0));
  }
  return chars.join("");
}

function centreSearchScore(progress) {
  return (progress.blocks * 100 | 0) + progress.score | 0;
}

function planNextCentreBlock4x4(state) {
  let start = centreValues(state);
  if (start === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The centre guide supports only complete 4×4 states."
      }
    };
  }
  let initial = centreProgressFor(start);
  let repairFrame = initial.blocks === 6 && !isCentreFrameValid(state);
  if (initial.blocks === 6 && !repairFrame) {
    return {
      TAG: "Error",
      _0: {
        message: "All six centre blocks are complete."
      }
    };
  }
  let frontier = [{
      values: start,
      alg: [],
      lastFace: "",
      score: initial.score,
      blocks: initial.blocks,
      fixed: initial.fixed
    }];
  let best = {
    contents: undefined
  };
  for (let _depth = 0; _depth <= 9; ++_depth) {
    let next = [];
    let seen = new Set();
    frontier.forEach(candidate => {
      moves.forEach(move => {
        let facePrefix = move.notation.slice(0, 1) === "2" ? move.notation.slice(1, 2) : move.notation.slice(0, 1);
        if (facePrefix === candidate.lastFace) {
          return;
        }
        let values = applyCentreMove(candidate.values, move);
        if (seen.has(values)) {
          return;
        }
        seen.add(values);
        let progress = centreProgressFor(values);
        let expanded_alg = candidate.alg.concat(move.alg);
        let expanded_score = progress.score;
        let expanded_blocks = progress.blocks;
        let expanded_fixed = progress.fixed;
        let expanded = {
          values: values,
          alg: expanded_alg,
          lastFace: facePrefix,
          score: expanded_score,
          blocks: expanded_blocks,
          fixed: expanded_fixed
        };
        next.push(expanded);
        let improves = repairFrame ? progress.fixed > initial.fixed : progress.blocks > initial.blocks || progress.blocks === initial.blocks && progress.score > initial.score;
        if (!improves) {
          return;
        }
        let current = best.contents;
        if (current === undefined) {
          best.contents = expanded;
          return;
        }
        let better = repairFrame ? progress.fixed > current.fixed : (
            progress.blocks > current.blocks ? true : progress.blocks === current.blocks && progress.score > current.score
          );
        if (better) {
          best.contents = expanded;
          return;
        }
      });
    });
    let ranked = Belt_SortArray.stableSortBy(next, (left, right) => {
      let scoreDiff = repairFrame ? right.fixed - left.fixed | 0 : centreSearchScore({
          blocks: right.blocks,
          score: right.score,
          fixed: right.fixed
        }) - centreSearchScore({
          blocks: left.blocks,
          score: left.score,
          fixed: left.fixed
        }) | 0;
      if (scoreDiff !== 0) {
        return scoreDiff;
      } else {
        return left.alg.length - right.alg.length | 0;
      }
    });
    frontier = ranked.slice(0, Primitive_int.min(1600, ranked.length));
  }
  let b = best.contents;
  if (b !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        alg: b.alg,
        algorithm: MoveTransform.serialize(b.alg),
        frameRepair: repairFrame,
        beforeBlocks: initial.blocks,
        afterBlocks: b.blocks,
        beforeScore: initial.score,
        afterScore: b.score
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: repairFrame ? "No centre-frame reordering sequence was found in the local search." : "No centre improvement was found in the local search. Make one centre setup move, then request the next guide."
      }
    };
  }
}

let pairingSeedNotations = [
  "2R U R' U' 2R'",
  "2R U R U' 2R'",
  "u' R U R' F R' F' R u"
];

let ollParityNotation = "r U2 x r U2 r U2 r' U2 l U2 r' U2 r U2 r' U2 r'";

let pllParityNotation = "2R2 U2 2R2 u2 2R2 u2";

let outerSetupNotations = [
  "",
  "U",
  "U'",
  "U2",
  "R",
  "R'",
  "R2",
  "F",
  "F'",
  "F2",
  "D",
  "D'",
  "D2",
  "L",
  "L'",
  "L2",
  "B",
  "B'",
  "B2"
];

let secondSetupNotations = [
  "",
  "U",
  "U'",
  "U2",
  "R",
  "R'",
  "R2",
  "F",
  "F'",
  "F2"
];

function edgeFlipSlots(error) {
  return Primitive_option.fromNullable((function(error) {
    if (typeof error !== "object" || error === null) return null;
    if (error.TAG !== "SolvabilityViolation" || typeof error._0 !== "object" || error._0 === null) return null;
    var violation = error._0;
    return violation.TAG === "EdgeFlip" && Array.isArray(violation.affectedSlots)
      ? violation.affectedSlots.filter(function(s) { return typeof s === "number"; })
      : null;
  })(error));
}

function hasPermutationParityMismatch(error) {
  return (function(error) {
    if (typeof error !== "object" || error === null) return false;
    if (error.TAG !== "SolvabilityViolation") return false;
    return error._0 === "PermutationParityMismatch"
      || (typeof error._0 === "object" && error._0 !== null && error._0.TAG === "PermutationParityMismatch");
  })(error);
}

function planNextWingPair4x4(state) {
  let e = inspectReduction4x4(state);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let initial = e._0;
  if (initial.centreBlocksComplete !== 6) {
    return {
      TAG: "Error",
      _0: {
        message: "Complete all six centre blocks before requesting a wing-pair guide."
      }
    };
  }
  if (initial.wingRowsPaired === 24) {
    return {
      TAG: "Error",
      _0: {
        message: "All visible wing rows are already paired."
      }
    };
  }
  let setups = [];
  outerSetupNotations.forEach(notation => {
    let s = parseGuide(notation);
    if (s !== undefined) {
      setups.push(s);
      return;
    }
  });
  let rotatedSeeds = new Map();
  pairingSeedNotations.forEach(notation => {
    let seed = parseGuide(notation);
    if (seed === undefined) {
      return;
    }
    for (let x = 0; x <= 3; ++x) {
      for (let y = 0; y <= 3; ++y) {
        for (let z = 0; z <= 3; ++z) {
          let rotated = MoveTransform.rotate(MoveTransform.rotate(MoveTransform.rotate(seed, "X", x), "Y", y), "Z", z);
          let serialized = MoveTransform.serialize(rotated);
          rotatedSeeds.set(serialized, rotated);
        }
      }
    }
  });
  let best = {
    contents: undefined
  };
  let evaluate = candidateSetups => {
    candidateSetups.forEach(setup => {
      mapValues(rotatedSeeds).forEach(seed => {
        let alg = setup.concat(seed).concat(MoveTransform.invert(setup));
        let replay = MoveExecutor.applyAlg(state, alg);
        if (replay.TAG !== "Ok") {
          return;
        }
        let after = inspectReduction4x4(replay._0);
        if (after.TAG !== "Ok") {
          return;
        }
        let after$1 = after._0;
        if (!(after$1.centreBlocksComplete === 6 && after$1.wingRowsPaired > initial.wingRowsPaired)) {
          return;
        }
        let guide_algorithm = MoveTransform.serialize(alg);
        let guide_before = initial.wingRowsPaired;
        let guide_after = after$1.wingRowsPaired;
        let guide = {
          alg: alg,
          algorithm: guide_algorithm,
          before: guide_before,
          after: guide_after
        };
        let current = best.contents;
        if (current !== undefined && !(guide_after > current.after || guide_after === current.after && guide_algorithm.length < current.algorithm.length)) {
          return;
        } else {
          best.contents = guide;
          return;
        }
      });
    });
  };
  evaluate(setups);
  if (best.contents === undefined) {
    let secondTurns = [];
    secondSetupNotations.forEach(notation => {
      let s = parseGuide(notation);
      if (s !== undefined) {
        secondTurns.push(s);
        return;
      }
    });
    let twoPlySetups = [];
    secondTurns.forEach(first => {
      secondTurns.forEach(second => {
        twoPlySetups.push(first.concat(second));
      });
    });
    evaluate(twoPlySetups);
  }
  if (best.contents === undefined) {
    let firstSteps = [];
    mapValues(rotatedSeeds).forEach(first => {
      let replay = MoveExecutor.applyAlg(state, first);
      if (replay.TAG !== "Ok") {
        return;
      }
      let replay$1 = replay._0;
      let after = inspectReduction4x4(replay$1);
      if (after.TAG !== "Ok") {
        return;
      }
      let after$1 = after._0;
      if (after$1.centreBlocksComplete === 6 && after$1.wingRowsPaired >= (initial.wingRowsPaired - 4 | 0)) {
        firstSteps.push({
          alg: first,
          state: replay$1
        });
        return;
      }
    });
    let secondSteps = new Map();
    setups.forEach(setup => {
      mapValues(rotatedSeeds).forEach(seed => {
        let alg = setup.concat(seed).concat(MoveTransform.invert(setup));
        secondSteps.set(MoveTransform.serialize(alg), alg);
      });
    });
    let finished = false;
    for (let i = 0, i_finish = firstSteps.length; i < i_finish; ++i) {
      if (!finished) {
        let first = firstSteps[i];
        let secVals = mapValues(secondSteps);
        for (let j = 0, j_finish = secVals.length; j < j_finish; ++j) {
          if (!finished) {
            let second = secVals[j];
            let replay = MoveExecutor.applyAlg(first.state, second);
            if (replay.TAG === "Ok") {
              let after = inspectReduction4x4(replay._0);
              if (after.TAG === "Ok") {
                let after$1 = after._0;
                if (after$1.centreBlocksComplete === 6 && after$1.wingRowsPaired > initial.wingRowsPaired) {
                  let alg = first.alg.concat(second);
                  let guide_algorithm = MoveTransform.serialize(alg);
                  let guide_before = initial.wingRowsPaired;
                  let guide_after = after$1.wingRowsPaired;
                  let guide = {
                    alg: alg,
                    algorithm: guide_algorithm,
                    before: guide_before,
                    after: guide_after
                  };
                  let current = best.contents;
                  if (current !== undefined && !(guide_after > current.after || guide_after === current.after && guide_algorithm.length < current.algorithm.length)) {
                    
                  } else {
                    best.contents = guide;
                  }
                  if (guide_after === 24) {
                    finished = true;
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  let g = best.contents;
  if (g !== undefined) {
    return {
      TAG: "Ok",
      _0: g
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "No single improving wing-pair move was found; this position needs a setup or parity step before requesting the next guide."
      }
    };
  }
}

function reduce4x4(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The reduction solver supports only complete 4×4 states."
      }
    };
  }
  let e = inspectReduction4x4(state);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let inspection = e._0;
  if (inspection.stage !== "reduced") {
    return {
      TAG: "Error",
      _0: {
        message: inspection.nextGoal
      }
    };
  }
  let reducedChars = [];
  let earlyError;
  for (let faceIndex = 0, faceIndex_finish = faces.length; faceIndex < faceIndex_finish; ++faceIndex) {
    if (earlyError === undefined) {
      let faceName = faces[faceIndex];
      let face = compact.slice((faceIndex << 4), ((faceIndex + 1 | 0) << 4));
      let c0 = face.slice(centreIndices[0], centreIndices[0] + 1 | 0);
      let c1 = face.slice(centreIndices[1], centreIndices[1] + 1 | 0);
      let c2 = face.slice(centreIndices[2], centreIndices[2] + 1 | 0);
      let c3 = face.slice(centreIndices[3], centreIndices[3] + 1 | 0);
      if (c0 !== c1 || c1 !== c2 || c2 !== c3) {
        earlyError = faceName + ` centres are not reduced yet.`;
      } else {
        for (let edgeIndex = 0, edgeIndex_finish = edgePairs.length; edgeIndex < edgeIndex_finish; ++edgeIndex) {
          let match = edgePairs[edgeIndex];
          let p1 = match[1];
          let p0 = match[0];
          let e0 = face.slice(p0, p0 + 1 | 0);
          let e1 = face.slice(p1, p1 + 1 | 0);
          if (e0 !== e1) {
            earlyError = faceName + ` ` + edgeNames[edgeIndex] + ` wings are not paired yet.`;
          }
        }
        for (let i = 0, i_finish = reducedFacelets.length; i < i_finish; ++i) {
          let idx = reducedFacelets[i];
          reducedChars.push(face.slice(idx, idx + 1 | 0));
        }
      }
    }
  }
  let msg = earlyError;
  if (msg !== undefined) {
    return {
      TAG: "Error",
      _0: {
        message: msg
      }
    };
  }
  let reducedCompact = reducedChars.join("");
  let parsed = FaceletCodec.parse(3, reducedCompact);
  if (parsed.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The reduced 3×3 facelets do not have one of each colour."
      }
    };
  }
  let parsed$1 = parsed._0;
  let piecesErr = PieceReducer.reduce(parsed$1);
  if (piecesErr.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        state: parsed$1,
        compact: reducedCompact
      }
    };
  }
  let piecesErr$1 = piecesErr._0;
  let flipped = edgeFlipSlots(piecesErr$1);
  if (flipped === undefined) {
    if (hasPermutationParityMismatch(piecesErr$1)) {
      return {
        TAG: "Error",
        _0: {
          message: "4×4 PLL parity detected: one dedge pair is swapped in the reduced state. Apply the PLL-parity repair before the 3×3 finish."
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: {
          message: `The reduced 3×3 state is not physically reachable: ` + PieceReducer.describeError(piecesErr$1) + `.`
        }
      };
    }
  }
  let count = flipped.length;
  let verb = count === 1 ? " is" : "s are";
  return {
    TAG: "Error",
    _0: {
      message: `4×4 OLL parity detected: ` + count.toString() + ` reduced dedge orientation` + verb + ` flipped. Apply the OLL-parity repair before the 3×3 finish.`
    }
  };
}

function planOLLParityRepair4x4(state) {
  let e = reduce4x4(state);
  if (e.TAG === "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "No OLL parity repair is needed."
      }
    };
  }
  let e$1 = e._0;
  if (!e$1.message.startsWith("4×4 OLL parity detected:")) {
    return {
      TAG: "Error",
      _0: e$1
    };
  }
  let alg = parseGuide(ollParityNotation);
  if (alg === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The OLL-parity repair could not be parsed."
      }
    };
  }
  let replay = MoveExecutor.applyAlg(state, alg);
  if (replay.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The OLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
  let match = reduce4x4(replay._0);
  if (match.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        alg: alg,
        algorithm: MoveTransform.serialize(alg)
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "The OLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
}

function planPLLParityRepair4x4(state) {
  let e = reduce4x4(state);
  if (e.TAG === "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "No PLL parity repair is needed."
      }
    };
  }
  let e$1 = e._0;
  if (!e$1.message.startsWith("4×4 PLL parity detected:")) {
    return {
      TAG: "Error",
      _0: e$1
    };
  }
  let alg = parseGuide(pllParityNotation);
  if (alg === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The PLL-parity repair could not be parsed."
      }
    };
  }
  let replay = MoveExecutor.applyAlg(state, alg);
  if (replay.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The PLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
  let match = reduce4x4(replay._0);
  if (match.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        alg: alg,
        algorithm: MoveTransform.serialize(alg)
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "The PLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
}

function isMonochromeSolved4x4(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return false;
  }
  let allMono = true;
  for (let faceIndex = 0, faceIndex_finish = faces.length; faceIndex < faceIndex_finish; ++faceIndex) {
    let face = compact.slice((faceIndex << 4), ((faceIndex + 1 | 0) << 4));
    let firstChar = face.slice(0, 1);
    for (let i = 1; i <= 15; ++i) {
      if (face.slice(i, i + 1 | 0) !== firstChar) {
        allMono = false;
      }
    }
  }
  return allMono;
}

let centreMoveNotations = arr;

let centreMoves = moves;

export {
  faces,
  centreIndices,
  edgePairs,
  edgeNames,
  reducedFacelets,
  dictValues,
  mapValues,
  get,
  set,
  isCubeState,
  compactFacelets,
  parseGuide,
  centreValues,
  centreFrames,
  isCentreFrameValid,
  inspectReduction4x4,
  centreProgressFor,
  centreMoveNotations,
  centreMoves,
  applyCentreMove,
  centreSearchScore,
  planNextCentreBlock4x4,
  pairingSeedNotations,
  ollParityNotation,
  pllParityNotation,
  outerSetupNotations,
  secondSetupNotations,
  edgeFlipSlots,
  hasPermutationParityMismatch,
  planNextWingPair4x4,
  reduce4x4,
  planOLLParityRepair4x4,
  planPLLParityRepair4x4,
  isMonochromeSolved4x4,
}
/* frames Not a pure module */
