// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as FaceletCodec from "../State/FaceletCodec.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as PieceReducer from "../State/PieceReducer.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as MoveTransform from "../Move/MoveTransform.res.mjs";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as ThreePhase4x4 from "./ThreePhase4x4.res.mjs";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let xCentres = [
  6,
  8,
  16,
  18
];

let plusCentres = [
  7,
  11,
  13,
  17
];

let wingPairs = [
  [
    1,
    3
  ],
  [
    9,
    19
  ],
  [
    21,
    23
  ],
  [
    5,
    15
  ]
];

let middleEdges = [
  2,
  14,
  22,
  10
];

let reducedIndices = [
  0,
  2,
  4,
  10,
  12,
  14,
  20,
  22,
  24
];

let centreMoves = [
  "2U",
  "2U'",
  "2U2",
  "2R",
  "2R'",
  "2R2",
  "2F",
  "2F'",
  "2F2",
  "2D",
  "2D'",
  "2D2",
  "2L",
  "2L'",
  "2L2",
  "2B",
  "2B'",
  "2B2"
];

let centreSearchMoves = Belt_Array.concatMany([
  [
    "U",
    "U'",
    "U2",
    "R",
    "R'",
    "R2",
    "F",
    "F'",
    "F2",
    "D",
    "D'",
    "D2",
    "L",
    "L'",
    "L2",
    "B",
    "B'",
    "B2"
  ],
  centreMoves
]);

let barCommutators = [
  "Rw U Rw'",
  "Rw U' Rw'",
  "2R U 2R'",
  "2R U' 2R'",
  "Rw U Rw' U'",
  "2R U 2R' U'"
];

let barSetupTurns = [
  "U",
  "U'",
  "U2"
];

let wingCycleNotations = [
  "2R U R' U' 2R'",
  "2R U2 2R'"
];

let ollParityNotation = "2R U2 2L F2 2L' F2 2R2 U2 2R U2 2L' U2 2R' U2 2R2";

let pllParityNotation = "Rw2 F2 U2 2R U2 Rw' U2 2L U2 Rw U2 F2 Rw2";

function charAt(value, index) {
  return value.slice(index, index + 1 | 0);
}

function faceAt(value, index) {
  return value.slice(index * 25 | 0, (index * 25 | 0) + 25 | 0);
}

function compactFacelets(state) {
  let compact = FaceletCodec.render(state);
  if (state.size === 5 && compact.length === 150) {
    return compact;
  }
}

function centreScore(face, indices, core) {
  return Stdlib_Array.reduce(indices, 0, (score, index) => score + (
    charAt(face, index) === core ? 1 : 0
  ) | 0);
}

function centreBarScore(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return;
  }
  let bars = {
    contents: 0
  };
  for (let faceIndex = 0; faceIndex <= 5; ++faceIndex) {
    let face = faceAt(compact, faceIndex);
    let core = charAt(face, 12);
    [
      [
        6,
        7,
        8
      ],
      [
        11,
        12,
        13
      ],
      [
        16,
        17,
        18
      ],
      [
        6,
        11,
        16
      ],
      [
        7,
        12,
        17
      ],
      [
        8,
        13,
        18
      ]
    ].forEach(line => {
      if (line.every(index => charAt(face, index) === core)) {
        bars.contents = bars.contents + 1 | 0;
        return;
      }
    });
  }
  return bars.contents;
}

function progressFor(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return;
  }
  let x = 0;
  let plus = 0;
  let faces = 0;
  let wings = {
    contents: 0
  };
  let score = 0;
  for (let faceIndex = 0; faceIndex <= 5; ++faceIndex) {
    let face = faceAt(compact, faceIndex);
    let core = charAt(face, 12);
    let xScore = centreScore(face, xCentres, core);
    let plusScore = centreScore(face, plusCentres, core);
    if (xScore === 4) {
      x = x + 1 | 0;
    }
    if (plusScore === 4) {
      plus = plus + 1 | 0;
    }
    if ((xScore + plusScore | 0) === 8) {
      faces = faces + 1 | 0;
    }
    score = (score + xScore | 0) + plusScore | 0;
    wingPairs.forEach(param => {
      if (charAt(face, param[0]) === charAt(face, param[1])) {
        wings.contents = wings.contents + 1 | 0;
        return;
      }
    });
  }
  return {
    x: x,
    plus: plus,
    faces: faces,
    wings: wings.contents,
    score: score
  };
}

function inspectReduction5x5(state) {
  let progress = progressFor(state);
  if (progress === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 Academy requires a complete 5×5 state."
      }
    };
  }
  let stage = progress.faces < 6 ? "centres" : (
      progress.wings < 24 ? "wings" : "handoff"
    );
  let nextGoal = stage === "centres" ? `Build the 3×3 centres around their fixed cores (` + progress.faces.toString() + `/6 complete).` : (
      stage === "wings" ? `Pair both wings around each fixed middle edge (` + progress.wings.toString() + `/24 matched).` : "Centre and wing milestones are complete. A 5×5 reduced-state finisher is the next Academy increment."
    );
  return {
    TAG: "Ok",
    _0: {
      xCentresComplete: progress.x,
      plusCentresComplete: progress.plus,
      centreFacesComplete: progress.faces,
      wingPairsMatched: progress.wings,
      stage: stage,
      nextGoal: nextGoal
    }
  };
}

function parse(notation) {
  let alg = MoveParser.parseWithOptions(5, "Wide", "Modern", notation);
  if (alg.TAG === "Ok") {
    return alg._0;
  }
}

function edgeFlipSlots(error) {
  return Primitive_option.fromNullable((function(error) {
    if (typeof error !== "object" || error === null) return null;
    if (error.TAG !== "SolvabilityViolation" || typeof error._0 !== "object" || error._0 === null) return null;
    var violation = error._0;
    return violation.TAG === "EdgeFlip" && Array.isArray(violation.affectedSlots)
      ? violation.affectedSlots.filter(function(slot) { return typeof slot === "number"; })
      : null;
  })(error));
}

function hasPermutationParityMismatch(error) {
  return (function(error) {
    if (typeof error !== "object" || error === null || error.TAG !== "SolvabilityViolation") return false;
    return error._0 === "PermutationParityMismatch"
      || (typeof error._0 === "object" && error._0 !== null && error._0.TAG === "PermutationParityMismatch");
  })(error);
}

function planOneByThreeBar(state, initial) {
  let value = centreBarScore(state);
  let beforeBars = value !== undefined ? value : 0;
  let best = {
    contents: undefined
  };
  barCommutators.forEach(notation => {
    let seed = parse(notation);
    if (seed === undefined) {
      return;
    }
    for (let xTurns = 0; xTurns <= 3; ++xTurns) {
      for (let yTurns = 0; yTurns <= 3; ++yTurns) {
        for (let zTurns = 0; zTurns <= 3; ++zTurns) {
          let rotated = MoveTransform.rotate(MoveTransform.rotate(MoveTransform.rotate(seed, "X", xTurns), "Y", yTurns), "Z", zTurns);
          [
            rotated,
            MoveTransform.invert(rotated)
          ].forEach(alg => {
            let replay = MoveExecutor.applyAlg(state, alg);
            if (replay.TAG !== "Ok") {
              return;
            }
            let replay$1 = replay._0;
            let match = progressFor(replay$1);
            let match$1 = centreBarScore(replay$1);
            if (match === undefined) {
              return;
            }
            if (match$1 === undefined) {
              return;
            }
            if (match$1 <= beforeBars) {
              return;
            }
            let guide_algorithm = MoveTransform.serialize(alg);
            let guide_before = initial.score;
            let guide_after = match.score;
            let guide_completedBefore = initial.x + initial.plus | 0;
            let guide_completedAfter = match.x + match.plus | 0;
            let guide = {
              alg: alg,
              algorithm: guide_algorithm,
              before: guide_before,
              after: guide_after,
              kind: "bar",
              barsBefore: beforeBars,
              barsAfter: match$1,
              completedBefore: guide_completedBefore,
              completedAfter: guide_completedAfter
            };
            let current = best.contents;
            if (current !== undefined && !(match$1 > current.barsAfter || match$1 === current.barsAfter && guide_after > current.after)) {
              return;
            } else {
              best.contents = guide;
              return;
            }
          });
        }
      }
    }
  });
  return best.contents;
}

function planBoundedBarSetup(state, initial) {
  let value = centreBarScore(state);
  let beforeBars = value !== undefined ? value : 0;
  let best = {
    contents: undefined
  };
  let frontier = [{
      state: state,
      alg: [],
      lastFace: "",
      score: initial.score + (beforeBars << 1) | 0
    }];
  for (let _for = 0; _for <= 3; ++_for) {
    let next = {
      contents: []
    };
    frontier.forEach(candidate => {
      centreSearchMoves.forEach(notation => {
        let face = notation.slice(0, 1) === "2" ? notation.slice(1, 2) : notation.slice(0, 1);
        if (face === candidate.lastFace) {
          return;
        }
        let move = parse(notation);
        if (move === undefined) {
          return;
        }
        let nextState = MoveExecutor.applyAlg(candidate.state, move);
        if (nextState.TAG !== "Ok") {
          return;
        }
        let nextState$1 = nextState._0;
        let match = progressFor(nextState$1);
        let match$1 = centreBarScore(nextState$1);
        if (match === undefined) {
          return;
        }
        if (match$1 === undefined) {
          return;
        }
        let expanded_alg = candidate.alg.concat(move);
        let expanded_score = match.score + (match$1 << 1) | 0;
        let expanded = {
          state: nextState$1,
          alg: expanded_alg,
          lastFace: face,
          score: expanded_score
        };
        next.contents.push(expanded);
        if (!(match$1 > beforeBars && match.score >= (initial.score - 3 | 0))) {
          return;
        }
        let guide_alg = expanded_alg;
        let guide_algorithm = MoveTransform.serialize(expanded_alg);
        let guide_before = initial.score;
        let guide_after = match.score;
        let guide_completedBefore = initial.x + initial.plus | 0;
        let guide_completedAfter = match.x + match.plus | 0;
        let guide = {
          alg: guide_alg,
          algorithm: guide_algorithm,
          before: guide_before,
          after: guide_after,
          kind: "bar",
          barsBefore: beforeBars,
          barsAfter: match$1,
          completedBefore: guide_completedBefore,
          completedAfter: guide_completedAfter
        };
        let current = best.contents;
        if (current !== undefined && !(match$1 > current.barsAfter || match$1 === current.barsAfter && guide_after > current.after)) {
          return;
        } else {
          best.contents = guide;
          return;
        }
      });
    });
    let ranked = Belt_SortArray.stableSortBy(next.contents, (left, right) => right.score - left.score | 0);
    frontier = ranked.slice(0, Primitive_int.min(10000, ranked.length));
  }
  return best.contents;
}

function findOneByThreeBar5x5(state) {
  let initial = progressFor(state);
  if (initial === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 1×3 bar planner requires a complete 5×5 state."
      }
    };
  }
  let guide = planOneByThreeBar(state, initial);
  if (guide !== undefined) {
    return {
      TAG: "Ok",
      _0: guide
    };
  }
  let guide$1 = planBoundedBarSetup(state, initial);
  if (guide$1 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$1
    };
  }
  let value = centreBarScore(state);
  let beforeBars = value !== undefined ? value : 0;
  let best = {
    contents: undefined
  };
  barCommutators.forEach(notation => {
    let seed = parse(notation);
    if (seed !== undefined) {
      barSetupTurns.forEach(setupNotation => {
        let setup = parse(setupNotation);
        if (setup === undefined) {
          return;
        }
        for (let xTurns = 0; xTurns <= 3; ++xTurns) {
          for (let yTurns = 0; yTurns <= 3; ++yTurns) {
            for (let zTurns = 0; zTurns <= 3; ++zTurns) {
              let rotatedSetup = MoveTransform.rotate(MoveTransform.rotate(MoveTransform.rotate(setup, "X", xTurns), "Y", yTurns), "Z", zTurns);
              let rotatedSeed = MoveTransform.rotate(MoveTransform.rotate(MoveTransform.rotate(seed, "X", xTurns), "Y", yTurns), "Z", zTurns);
              let alg = rotatedSetup.concat(rotatedSeed).concat(MoveTransform.invert(rotatedSetup));
              let replay = MoveExecutor.applyAlg(state, alg);
              if (replay.TAG === "Ok") {
                let replay$1 = replay._0;
                let match = progressFor(replay$1);
                let match$1 = centreBarScore(replay$1);
                if (match !== undefined && match$1 !== undefined && match$1 > beforeBars && match.score >= (initial.score - 3 | 0)) {
                  let guide_algorithm = MoveTransform.serialize(alg);
                  let guide_before = initial.score;
                  let guide_after = match.score;
                  let guide_completedBefore = initial.x + initial.plus | 0;
                  let guide_completedAfter = match.x + match.plus | 0;
                  let guide = {
                    alg: alg,
                    algorithm: guide_algorithm,
                    before: guide_before,
                    after: guide_after,
                    kind: "bar",
                    barsBefore: beforeBars,
                    barsAfter: match$1,
                    completedBefore: guide_completedBefore,
                    completedAfter: guide_completedAfter
                  };
                  let current = best.contents;
                  if (current !== undefined && !(match$1 > current.barsAfter || match$1 === current.barsAfter && guide_after > current.after)) {
                    
                  } else {
                    best.contents = guide;
                  }
                }
              }
            }
          }
        }
      });
      return;
    }
  });
  let guide$2 = best.contents;
  if (guide$2 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$2
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "No replay-verified 1×3 bar commutator was found within the bounded setup search."
      }
    };
  }
}

function findCentreCommutator(state, initial) {
  let innerSlices = [
    "2R",
    "2R'",
    "2L",
    "2L'",
    "2U",
    "2U'",
    "2D",
    "2D'",
    "2F",
    "2F'",
    "2B",
    "2B'"
  ];
  let middleSlices = [
    "3R",
    "3R'",
    "3U",
    "3U'",
    "3F",
    "3F'"
  ];
  let faces = [
    "U",
    "U'",
    "D",
    "D'",
    "F",
    "F'",
    "B",
    "B'",
    "L",
    "L'",
    "R",
    "R'"
  ];
  let invertMove = m => {
    if (m.endsWith("'")) {
      return m.slice(0, m.length - 1 | 0);
    } else {
      return m + "'";
    }
  };
  let best = {
    contents: undefined
  };
  innerSlices.forEach(s1 => {
    faces.forEach(f => {
      innerSlices.forEach(s2 => {
        let s1Base = s1.replace("'", "");
        let s2Base = s2.replace("'", "");
        if (s1Base === s2Base) {
          return;
        }
        let invF = invertMove(f);
        let invS1 = invertMove(s1);
        let invS2 = invertMove(s2);
        let comm = s1 + ` ` + f + ` ` + s2 + ` ` + invF + ` ` + invS1 + ` ` + f + ` ` + invS2 + ` ` + invF;
        let alg = parse(comm);
        if (alg === undefined) {
          return;
        }
        let replay = MoveExecutor.applyAlg(state, alg);
        if (replay.TAG !== "Ok") {
          return;
        }
        let after = progressFor(replay._0);
        if (after === undefined) {
          return;
        }
        if (!(after.x > initial.x || after.faces > initial.faces || after.score > initial.score)) {
          return;
        }
        let completedBefore = initial.x + initial.plus | 0;
        let completedAfter = after.x + after.plus | 0;
        let guide_algorithm = MoveTransform.serialize(alg);
        let guide_before = initial.score;
        let guide_after = after.score;
        let guide = {
          alg: alg,
          algorithm: guide_algorithm,
          before: guide_before,
          after: guide_after,
          kind: "xCycle",
          barsBefore: 0,
          barsAfter: 0,
          completedBefore: completedBefore,
          completedAfter: completedAfter
        };
        let current = best.contents;
        if (current !== undefined && !(completedAfter > current.completedAfter || completedAfter === current.completedAfter && guide_after > current.after)) {
          return;
        } else {
          best.contents = guide;
          return;
        }
      });
    });
  });
  if (best.contents === undefined) {
    let allSlices = innerSlices.concat(middleSlices);
    allSlices.forEach(s1 => {
      faces.forEach(f => {
        allSlices.forEach(s2 => {
          let s1Base = s1.replace("'", "");
          let s2Base = s2.replace("'", "");
          if (!(s1Base !== s2Base && (s1.startsWith("3") || s2.startsWith("3")))) {
            return;
          }
          let invF = invertMove(f);
          let invS1 = invertMove(s1);
          let invS2 = invertMove(s2);
          let comm = s1 + ` ` + f + ` ` + s2 + ` ` + invF + ` ` + invS1 + ` ` + f + ` ` + invS2 + ` ` + invF;
          let alg = parse(comm);
          if (alg === undefined) {
            return;
          }
          let replay = MoveExecutor.applyAlg(state, alg);
          if (replay.TAG !== "Ok") {
            return;
          }
          let after = progressFor(replay._0);
          if (after === undefined) {
            return;
          }
          if (!((after.plus > initial.plus || after.faces > initial.faces || after.score > initial.score) && after.x >= initial.x)) {
            return;
          }
          let completedBefore = initial.x + initial.plus | 0;
          let completedAfter = after.x + after.plus | 0;
          let guide_algorithm = MoveTransform.serialize(alg);
          let guide_before = initial.score;
          let guide_after = after.score;
          let guide = {
            alg: alg,
            algorithm: guide_algorithm,
            before: guide_before,
            after: guide_after,
            kind: "plusCycle",
            barsBefore: 0,
            barsAfter: 0,
            completedBefore: completedBefore,
            completedAfter: completedAfter
          };
          let current = best.contents;
          if (current !== undefined && !(completedAfter > current.completedAfter || completedAfter === current.completedAfter && guide_after > current.after)) {
            return;
          } else {
            best.contents = guide;
            return;
          }
        });
      });
    });
  }
  return best.contents;
}

function solveXCentreCycle5x5(state) {
  let initial = progressFor(state);
  if (initial === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 centre-cycle solver requires a complete state."
      }
    };
  }
  let guide = findCentreCommutator(state, initial);
  if (guide !== undefined && guide.kind === "xCycle") {
    return {
      TAG: "Ok",
      _0: guide
    };
  }
  let compact = FaceletCodec.render(state);
  let output = {
    contents: []
  };
  [
    0,
    3,
    2,
    5,
    1,
    4
  ].forEach(faceIndex => {
    let face = faceAt(compact, faceIndex);
    [
      6,
      8,
      18,
      16
    ].forEach(index => {
      output.contents = output.contents.concat([charAt(face, index)]);
    });
  });
  let centres = output.contents.join("");
  let solution = ThreePhase4x4.solveCentreReduction(centres, 6, 6, 3);
  if (solution.TAG === "Ok") {
    let solution$1 = solution._0;
    let notation = solution$1.phase1Notations.concat(solution$1.phase2Notations).join(" ");
    let alg = parse(notation);
    if (alg === undefined) {
      return {
        TAG: "Error",
        _0: {
          message: "The X-centre solver generated invalid 5×5 notation."
        }
      };
    }
    let replay = MoveExecutor.applyAlg(state, alg);
    if (replay.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: {
          message: "The X-centre cycle could not be replayed on the 5×5 state."
        }
      };
    }
    let after = progressFor(replay._0);
    if (after !== undefined && after.x > initial.x) {
      return {
        TAG: "Ok",
        _0: {
          alg: alg,
          algorithm: MoveTransform.serialize(alg),
          before: initial.score,
          after: after.score,
          kind: "xCycle",
          barsBefore: 0,
          barsAfter: 0,
          completedBefore: initial.x + initial.plus | 0,
          completedAfter: after.x + after.plus | 0
        }
      };
    } else {
      return {
        TAG: "Error",
        _0: {
          message: "The mapped X-centre cycle did not improve the 5×5 X-centre orbit."
        }
      };
    }
  }
  let guide$1 = findCentreCommutator(state, initial);
  if (guide$1 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$1
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "No safe bounded X-centre cycle was found within the search budget. Find 1×3 bar commutator remains available for a separate bounded setup search."
      }
    };
  }
}

function solvePlusCentreCycle5x5(state) {
  let initial = progressFor(state);
  if (initial === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 centre-cycle solver requires a complete state."
      }
    };
  }
  let guide = findCentreCommutator(state, initial);
  if (guide !== undefined) {
    return {
      TAG: "Ok",
      _0: guide
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "+-centres do not share 4×4 geometry. Their guidance is provided by the replay-verified centre planner."
      }
    };
  }
}

function planNextCentreOrbit(state, initial) {
  let completedBefore = initial.x + initial.plus | 0;
  let best = {
    contents: undefined
  };
  let frontier = [{
      state: state,
      alg: [],
      lastFace: "",
      score: initial.score + (completedBefore * 100 | 0) | 0
    }];
  for (let _for = 0; _for <= 2; ++_for) {
    let next = {
      contents: []
    };
    frontier.forEach(candidate => {
      centreSearchMoves.forEach(notation => {
        let face = notation.slice(0, 1) === "2" ? notation.slice(1, 2) : notation.slice(0, 1);
        if (face === candidate.lastFace) {
          return;
        }
        let move = parse(notation);
        if (move === undefined) {
          return;
        }
        let nextState = MoveExecutor.applyAlg(candidate.state, move);
        if (nextState.TAG !== "Ok") {
          return;
        }
        let nextState$1 = nextState._0;
        let after = progressFor(nextState$1);
        if (after === undefined) {
          return;
        }
        let completedAfter = after.x + after.plus | 0;
        let quality = (after.score + (completedAfter * 100 | 0) | 0) + (after.faces * 1000 | 0) | 0;
        let expanded_alg = candidate.alg.concat(move);
        let expanded = {
          state: nextState$1,
          alg: expanded_alg,
          lastFace: face,
          score: quality
        };
        next.contents = Belt_Array.concatMany([
          [expanded],
          next.contents
        ]);
        if (completedAfter <= completedBefore) {
          return;
        }
        let guide_alg = expanded_alg;
        let guide_algorithm = MoveTransform.serialize(expanded_alg);
        let guide_before = initial.score;
        let guide_after = after.score;
        let guide = {
          alg: guide_alg,
          algorithm: guide_algorithm,
          before: guide_before,
          after: guide_after,
          kind: "orbit",
          barsBefore: 0,
          barsAfter: 0,
          completedBefore: completedBefore,
          completedAfter: completedAfter
        };
        let current = best.contents;
        if (current !== undefined && !(completedAfter > current.completedAfter || completedAfter === current.completedAfter && guide_after > current.after)) {
          return;
        } else {
          best.contents = guide;
          return;
        }
      });
    });
    let ranked = Belt_SortArray.stableSortBy(next.contents, (left, right) => right.score - left.score | 0);
    frontier = ranked.slice(0, Primitive_int.min(900, ranked.length));
  }
  return best.contents;
}

function planNextCentre5x5(state) {
  let initial = progressFor(state);
  if (initial === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 centre guide requires a complete state."
      }
    };
  }
  if (initial.faces === 6) {
    return {
      TAG: "Error",
      _0: {
        message: "All six 3×3 centre faces are complete."
      }
    };
  }
  let best = {
    contents: undefined
  };
  let value = centreBarScore(state);
  let initialBars = value !== undefined ? value : 0;
  let bestBar = {
    contents: undefined
  };
  let frontier = [{
      state: state,
      alg: [],
      lastFace: "",
      score: initial.score
    }];
  for (let _for = 0; _for <= 2; ++_for) {
    let next = {
      contents: []
    };
    frontier.forEach(candidate => {
      centreSearchMoves.forEach(notation => {
        let face = notation.slice(0, 1) === "2" ? notation.slice(1, 2) : notation.slice(0, 1);
        if (face === candidate.lastFace) {
          return;
        }
        let move = parse(notation);
        if (move === undefined) {
          return;
        }
        let nextState = MoveExecutor.applyAlg(candidate.state, move);
        if (nextState.TAG !== "Ok") {
          return;
        }
        let nextState$1 = nextState._0;
        let after = progressFor(nextState$1);
        if (after === undefined) {
          return;
        }
        let expanded_alg = candidate.alg.concat(move);
        let expanded_score = after.score;
        let expanded = {
          state: nextState$1,
          alg: expanded_alg,
          lastFace: face,
          score: expanded_score
        };
        next.contents = Belt_Array.concatMany([
          [expanded],
          next.contents
        ]);
        if (after.score > initial.score) {
          let guide_alg = expanded_alg;
          let guide_algorithm = MoveTransform.serialize(expanded_alg);
          let guide_before = initial.score;
          let guide_after = after.score;
          let guide_completedBefore = initial.x + initial.plus | 0;
          let guide_completedAfter = initial.x + initial.plus | 0;
          let guide = {
            alg: guide_alg,
            algorithm: guide_algorithm,
            before: guide_before,
            after: guide_after,
            kind: "improvement",
            barsBefore: initialBars,
            barsAfter: initialBars,
            completedBefore: guide_completedBefore,
            completedAfter: guide_completedAfter
          };
          let current = best.contents;
          if (current !== undefined && guide_after <= current.after) {
            return;
          } else {
            best.contents = guide;
            return;
          }
        }
        if (after.score < (initial.score - 3 | 0)) {
          return;
        }
        let barsAfter = centreBarScore(nextState$1);
        if (barsAfter === undefined) {
          return;
        }
        if (barsAfter <= initialBars) {
          return;
        }
        let guide_alg$1 = expanded_alg;
        let guide_algorithm$1 = MoveTransform.serialize(expanded_alg);
        let guide_before$1 = initial.score;
        let guide_after$1 = after.score;
        let guide_completedBefore$1 = initial.x + initial.plus | 0;
        let guide_completedAfter$1 = initial.x + initial.plus | 0;
        let guide$1 = {
          alg: guide_alg$1,
          algorithm: guide_algorithm$1,
          before: guide_before$1,
          after: guide_after$1,
          kind: "bar",
          barsBefore: initialBars,
          barsAfter: barsAfter,
          completedBefore: guide_completedBefore$1,
          completedAfter: guide_completedAfter$1
        };
        let current$1 = bestBar.contents;
        if (current$1 !== undefined && !(barsAfter > current$1.barsAfter || barsAfter === current$1.barsAfter && guide_after$1 > current$1.after)) {
          return;
        } else {
          bestBar.contents = guide$1;
          return;
        }
      });
    });
    let ranked = Belt_SortArray.stableSortBy(next.contents, (left, right) => right.score - left.score | 0);
    frontier = ranked.slice(0, Primitive_int.min(900, ranked.length));
  }
  let guide = best.contents;
  if (guide !== undefined) {
    return {
      TAG: "Ok",
      _0: guide
    };
  }
  let guide$1 = bestBar.contents;
  if (guide$1 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$1
    };
  }
  let guide$2 = findCentreCommutator(state, initial);
  if (guide$2 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$2
    };
  }
  let guide$3 = planOneByThreeBar(state, initial);
  if (guide$3 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$3
    };
  }
  let guide$4 = planNextCentreOrbit(state, initial);
  if (guide$4 !== undefined) {
    return {
      TAG: "Ok",
      _0: guide$4
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "No replay-verified 1×3 bar insertion or centre commutator is available for this state."
      }
    };
  }
}

function planNextWingPair5x5(state) {
  let initial = progressFor(state);
  if (initial === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 wing guide requires a complete state."
      }
    };
  }
  if (initial.faces !== 6) {
    return {
      TAG: "Error",
      _0: {
        message: "Complete all six 3×3 centres before requesting a wing guide."
      }
    };
  }
  if (initial.wings === 24) {
    return {
      TAG: "Error",
      _0: {
        message: "All 24 visible wing pairs are already matched."
      }
    };
  }
  let best = {
    contents: undefined
  };
  wingCycleNotations.forEach(notation => {
    let seed = parse(notation);
    if (seed === undefined) {
      return;
    }
    let variants = [];
    for (let xTurns = 0; xTurns <= 3; ++xTurns) {
      for (let yTurns = 0; yTurns <= 3; ++yTurns) {
        for (let zTurns = 0; zTurns <= 3; ++zTurns) {
          let rotated = MoveTransform.rotate(MoveTransform.rotate(MoveTransform.rotate(seed, "X", xTurns), "Y", yTurns), "Z", zTurns);
          variants = Belt_Array.concatMany([
            [
              rotated,
              MoveTransform.invert(rotated)
            ],
            variants
          ]);
        }
      }
    }
    variants.forEach(alg => {
      let replay = MoveExecutor.applyAlg(state, alg);
      if (replay.TAG !== "Ok") {
        return;
      }
      let after = progressFor(replay._0);
      if (after === undefined) {
        return;
      }
      if (!(after.faces === 6 && after.wings > initial.wings)) {
        return;
      }
      let candidate_algorithm = MoveTransform.serialize(alg);
      let candidate_before = initial.wings;
      let candidate_after = after.wings;
      let candidate = {
        alg: alg,
        algorithm: candidate_algorithm,
        before: candidate_before,
        after: candidate_after,
        kind: "wing",
        barsBefore: 0,
        barsAfter: 0,
        completedBefore: 0,
        completedAfter: 0
      };
      let current = best.contents;
      if (current !== undefined && candidate_after <= current.after) {
        return;
      } else {
        best.contents = candidate;
        return;
      }
    });
  });
  let guide = best.contents;
  if (guide !== undefined) {
    return {
      TAG: "Ok",
      _0: guide
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "No centre-preserving wing improvement is available. Make a pairing setup, then request the next guide."
      }
    };
  }
}

function reduce5x5(state) {
  let compact = compactFacelets(state);
  if (compact === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 reduction handoff requires a complete 5×5 state."
      }
    };
  }
  let progress = progressFor(state);
  if (progress === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 reduction handoff could not inspect this state."
      }
    };
  }
  if (progress.faces !== 6) {
    return {
      TAG: "Error",
      _0: {
        message: "Complete all six fixed-core 3×3 centres before the 3×3 handoff."
      }
    };
  }
  if (progress.wings !== 24) {
    return {
      TAG: "Error",
      _0: {
        message: `Pair all 24 wing rows before the 3×3 handoff (` + progress.wings.toString() + `/24 matched).`
      }
    };
  }
  let valid = true;
  for (let faceIndex = 0; faceIndex <= 5; ++faceIndex) {
    let face = faceAt(compact, faceIndex);
    let core = charAt(face, 12);
    if ((centreScore(face, xCentres, core) + centreScore(face, plusCentres, core) | 0) !== 8) {
      valid = false;
    }
    for (let edgeIndex = 0; edgeIndex <= 3; ++edgeIndex) {
      let match = wingPairs[edgeIndex];
      let middle = middleEdges[edgeIndex];
      if (charAt(face, match[0]) !== charAt(face, middle) || charAt(face, match[1]) !== charAt(face, middle)) {
        valid = false;
      }
    }
  }
  if (!valid) {
    return {
      TAG: "Error",
      _0: {
        message: "The wing rows are matched but do not yet agree with their fixed middle edges; continue pairing before handoff."
      }
    };
  }
  let reducedCompact = "";
  for (let faceIndex$1 = 0; faceIndex$1 <= 5; ++faceIndex$1) {
    let face$1 = faceAt(compact, faceIndex$1);
    reducedCompact = reducedCompact + reducedIndices.map(index => charAt(face$1, index)).join("");
  }
  let reduced = FaceletCodec.parse(3, reducedCompact);
  if (reduced.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The projected 3×3 does not have the required colour inventory."
      }
    };
  }
  let reduced$1 = reduced._0;
  let error = PieceReducer.reduce(reduced$1);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        state: reduced$1,
        compact: reducedCompact
      }
    };
  }
  let error$1 = error._0;
  let slots = edgeFlipSlots(error$1);
  if (slots !== undefined) {
    return {
      TAG: "Error",
      _0: {
        message: `5×5 OLL parity detected: ` + slots.length.toString() + ` reduced dedge orientation error. Apply the replay-verified OLL-parity repair.`
      }
    };
  } else if (hasPermutationParityMismatch(error$1)) {
    return {
      TAG: "Error",
      _0: {
        message: "5×5 PLL parity detected: a reduced dedge pair is swapped. Apply the replay-verified PLL-parity repair."
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: `5×5 reduced-state parity/solvability diagnostic: ` + PieceReducer.describeError(error$1)
      }
    };
  }
}

function planOLLParityRepair5x5(state) {
  let error = reduce5x5(state);
  if (error.TAG === "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "No 5×5 OLL parity repair is needed."
      }
    };
  }
  let error$1 = error._0;
  if (!error$1.message.startsWith("5×5 OLL parity detected:")) {
    return {
      TAG: "Error",
      _0: error$1
    };
  }
  let alg = parse(ollParityNotation);
  if (alg === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 OLL-parity repair could not be parsed."
      }
    };
  }
  let replay = MoveExecutor.applyAlg(state, alg);
  if (replay.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 OLL-parity repair could not be replayed."
      }
    };
  }
  let match = reduce5x5(replay._0);
  if (match.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        alg: alg,
        algorithm: MoveTransform.serialize(alg)
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 OLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
}

function planPLLParityRepair5x5(state) {
  let error = reduce5x5(state);
  if (error.TAG === "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "No 5×5 PLL parity repair is needed."
      }
    };
  }
  let error$1 = error._0;
  if (!error$1.message.startsWith("5×5 PLL parity detected:")) {
    return {
      TAG: "Error",
      _0: error$1
    };
  }
  let alg = parse(pllParityNotation);
  if (alg === undefined) {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 PLL-parity repair could not be parsed."
      }
    };
  }
  let replay = MoveExecutor.applyAlg(state, alg);
  if (replay.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 PLL-parity repair could not be replayed."
      }
    };
  }
  let match = reduce5x5(replay._0);
  if (match.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        alg: alg,
        algorithm: MoveTransform.serialize(alg)
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        message: "The 5×5 PLL-parity repair did not produce a legal reduced 3×3 state."
      }
    };
  }
}

export {
  xCentres,
  plusCentres,
  wingPairs,
  middleEdges,
  reducedIndices,
  centreMoves,
  centreSearchMoves,
  barCommutators,
  barSetupTurns,
  wingCycleNotations,
  ollParityNotation,
  pllParityNotation,
  charAt,
  faceAt,
  compactFacelets,
  centreScore,
  centreBarScore,
  progressFor,
  inspectReduction5x5,
  parse,
  edgeFlipSlots,
  hasPermutationParityMismatch,
  planOneByThreeBar,
  planBoundedBarSetup,
  findOneByThreeBar5x5,
  findCentreCommutator,
  solveXCentreCycle5x5,
  solvePlusCentreCycle5x5,
  planNextCentreOrbit,
  planNextCentre5x5,
  planNextWingPair5x5,
  reduce5x5,
  planOLLParityRepair5x5,
  planPLLParityRepair5x5,
}
/* centreSearchMoves Not a pure module */
