// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as FaceletCodec from "../State/FaceletCodec.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function encodeFacelets(state) {
  if (state.size !== 4) {
    return {
      TAG: "Error",
      _0: {
        TAG: "UnsupportedState",
        _0: "Three-phase 4×4 requires a complete 4×4 state."
      }
    };
  } else {
    return {
      TAG: "Ok",
      _0: StateTypes.serializationOrder.map(face => state.facelets[StateTypes.storageIndex(face)].map(StateTypes.faceToChar).join("")).join("")
    };
  }
}

function decodeFacelets(facelets) {
  let state = FaceletCodec.parse(4, facelets);
  if (state.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: state._0
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidFacelets",
        _0: "Three-phase 4×4 requires 96 legal URFDLB facelets."
      }
    };
  }
}

let centreFaceletIndices = [
  5,
  6,
  10,
  9,
  53,
  54,
  58,
  57,
  37,
  38,
  42,
  41,
  85,
  86,
  90,
  89,
  21,
  22,
  26,
  25,
  69,
  70,
  74,
  73
];

function extractCentres(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return "";
  }
  let facelets$1 = facelets._0;
  return centreFaceletIndices.map(index => String(facelets$1[index])).join("");
}

let wingFaceletIndices = [
  [
    13,
    33
  ],
  [
    4,
    65
  ],
  [
    2,
    81
  ],
  [
    11,
    17
  ],
  [
    61,
    94
  ],
  [
    52,
    78
  ],
  [
    50,
    46
  ],
  [
    59,
    30
  ],
  [
    75,
    40
  ],
  [
    68,
    87
  ],
  [
    27,
    88
  ],
  [
    20,
    39
  ],
  [
    34,
    14
  ],
  [
    66,
    8
  ],
  [
    82,
    1
  ],
  [
    18,
    7
  ],
  [
    93,
    62
  ],
  [
    77,
    56
  ],
  [
    45,
    49
  ],
  [
    29,
    55
  ],
  [
    36,
    71
  ],
  [
    91,
    72
  ],
  [
    84,
    23
  ],
  [
    43,
    24
  ]
];

function extractWings(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return [];
  }
  let facelets$1 = facelets._0;
  return wingFaceletIndices.map(param => String(facelets$1[param[0]]) + String(facelets$1[param[1]]));
}

let cornerFaceletIndices = [
  [
    15,
    16,
    35
  ],
  [
    12,
    32,
    67
  ],
  [
    0,
    64,
    83
  ],
  [
    3,
    80,
    19
  ],
  [
    51,
    47,
    28
  ],
  [
    48,
    79,
    44
  ],
  [
    60,
    95,
    76
  ],
  [
    63,
    31,
    92
  ]
];

function extractCorners(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return [];
  }
  let facelets$1 = facelets._0;
  return cornerFaceletIndices.map(indices => indices.map(index => String(facelets$1[index])).join(""));
}

function applyTransition(state, notation) {
  if (state.size !== 4) {
    return {
      TAG: "Error",
      _0: {
        TAG: "UnsupportedState",
        _0: "Three-phase transitions require a 4×4 state."
      }
    };
  }
  let alg = MoveParser.parseWithOptions(4, "Wide", "Modern", notation);
  if (alg.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "Invalid 4×4 transition notation."
      }
    };
  }
  let next = MoveExecutor.applyAlg(state, alg._0);
  if (next.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: next._0
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "4×4 transition could not be applied."
      }
    };
  }
}

function serialFace(index) {
  switch (index) {
    case 0 :
      return "U";
    case 1 :
      return "R";
    case 2 :
      return "F";
    case 3 :
      return "D";
    case 4 :
      return "L";
    default:
      return "B";
  }
}

function markerState() {
  return {
    size: 4,
    facelets: StateTypes.storageOrder.map(param => Stdlib_Array.make(16, "U"))
  };
}

function rawMarkerIndex(state) {
  let found = -1;
  for (let serialIndex = 0; serialIndex <= 5; ++serialIndex) {
    let stickers = state.facelets[StateTypes.storageIndex(serialFace(serialIndex))];
    for (let stickerIndex = 0; stickerIndex <= 15; ++stickerIndex) {
      if (stickers[stickerIndex] === "D") {
        found = (serialIndex << 4) + stickerIndex | 0;
      }
    }
  }
  return found;
}

function centreSlotForFacelet(rawIndex) {
  let found = -1;
  for (let slot = 0; slot <= 23; ++slot) {
    if (centreFaceletIndices[slot] === rawIndex) {
      found = slot;
    }
  }
  return found;
}

function centreTransition(notation) {
  let permutation = Stdlib_Array.make(24, 0);
  let failure;
  for (let sourceSlot = 0; sourceSlot <= 23; ++sourceSlot) {
    let marker = markerState();
    let sourceFacelet = centreFaceletIndices[sourceSlot];
    let face = serialFace(sourceFacelet / 16 | 0);
    marker.facelets[StateTypes.storageIndex(face)][sourceFacelet % 16] = "D";
    let error = applyTransition(marker, notation);
    if (error.TAG === "Ok") {
      let targetSlot = centreSlotForFacelet(rawMarkerIndex(error._0));
      if (targetSlot === -1) {
        failure = {
          TAG: "InvalidTransition",
          _0: "Transition moves a centre marker outside the centre coordinate."
        };
      } else {
        permutation[targetSlot] = sourceSlot;
      }
    } else {
      failure = error._0;
    }
  }
  let error$1 = failure;
  if (error$1 !== undefined) {
    return {
      TAG: "Error",
      _0: error$1
    };
  } else {
    return {
      TAG: "Ok",
      _0: permutation
    };
  }
}

function applyCentreTransition(centres, permutation) {
  return permutation.map(source => String(centres[source])).join("");
}

function choose(n, k) {
  if (k < 0 || k > n) {
    return 0;
  }
  let reduced = k > (n - k | 0) ? n - k | 0 : k;
  let value = 1;
  for (let offset = 1; offset <= reduced; ++offset) {
    value = Primitive_int.div(value * ((n - reduced | 0) + offset | 0) | 0, offset);
  }
  return value;
}

function rankUdCentres(centres) {
  if (centres.length !== 24) {
    return -1;
  }
  let selected = [];
  for (let slot = 0; slot <= 23; ++slot) {
    let colour = String(centres[slot]);
    if (colour === "U" || colour === "D") {
      selected = selected.concat([slot]);
    }
  }
  if (selected.length !== 8) {
    return -1;
  }
  let rank = 0;
  let previous = -1;
  for (let selectionIndex = 0; selectionIndex <= 7; ++selectionIndex) {
    let selectedSlot = selected[selectionIndex];
    for (let candidate = previous + 1 | 0; candidate < selectedSlot; ++candidate) {
      rank = rank + choose((24 - candidate | 0) - 1 | 0, (8 - selectionIndex | 0) - 1 | 0) | 0;
    }
    previous = selectedSlot;
  }
  return rank;
}

function rankUdSlots(selected) {
  if (selected.length !== 8) {
    return -1;
  }
  let rank = 0;
  let previous = -1;
  for (let selectionIndex = 0; selectionIndex <= 7; ++selectionIndex) {
    let selectedSlot = selected[selectionIndex];
    for (let candidate = previous + 1 | 0; candidate < selectedSlot; ++candidate) {
      rank = rank + choose((24 - candidate | 0) - 1 | 0, (8 - selectionIndex | 0) - 1 | 0) | 0;
    }
    previous = selectedSlot;
  }
  return rank;
}

function unrankUdCentres(rank) {
  if (rank < 0 || rank >= choose(24, 8)) {
    return [];
  }
  let remainingRank = rank;
  let selected = [];
  let candidate = 0;
  for (let selectionIndex = 0; selectionIndex <= 7; ++selectionIndex) {
    let finding = true;
    while (finding) {
      let count = choose((24 - candidate | 0) - 1 | 0, (8 - selectionIndex | 0) - 1 | 0);
      if (remainingRank < count) {
        selected = selected.concat([candidate]);
        candidate = candidate + 1 | 0;
        finding = false;
      } else {
        remainingRank = remainingRank - count | 0;
        candidate = candidate + 1 | 0;
      }
    };
  }
  return selected;
}

let centreCoordinateSize = choose(24, 8);

function createCentrePruning() {
  return Stdlib_Array.make((centreCoordinateSize + 1 | 0) / 2 | 0, 255);
}

function pruningDepth(table, index) {
  let packed = table[index / 2 | 0];
  if (index % 2 === 0) {
    return packed % 16;
  } else {
    return packed / 16 | 0;
  }
}

function setPruningDepth(table, index, depth) {
  let tableIndex = index / 2 | 0;
  let packed = table[tableIndex];
  let normalized = depth % 16;
  if (index % 2 === 0) {
    table[tableIndex] = ((packed / 16 | 0) << 4) + normalized | 0;
  } else {
    table[tableIndex] = packed % 16 + (normalized << 4) | 0;
  }
}

let centreMoveNotations = [
  "U",
  "U'",
  "U2",
  "R",
  "R'",
  "R2",
  "F",
  "F'",
  "F2",
  "D",
  "D'",
  "D2",
  "L",
  "L'",
  "L2",
  "B",
  "B'",
  "B2",
  "Uw",
  "Uw'",
  "Uw2",
  "Rw",
  "Rw'",
  "Rw2",
  "Fw",
  "Fw'",
  "Fw2",
  "Dw",
  "Dw'",
  "Dw2",
  "Lw",
  "Lw'",
  "Lw2",
  "Bw",
  "Bw'",
  "Bw2"
];

function transitionUdRank(rank, permutation) {
  let selected = unrankUdCentres(rank);
  let marked = Stdlib_Array.make(24, false);
  selected.forEach(slot => {
    marked[slot] = true;
  });
  let next = [];
  for (let targetSlot = 0; targetSlot <= 23; ++targetSlot) {
    if (marked[permutation[targetSlot]]) {
      next = next.concat([targetSlot]);
    }
  }
  return rankUdSlots(next);
}

function composeCentrePermutations(first, second) {
  return second.map(target => first[target]);
}

function centreSymmetryGenerators() {
  let generators = {
    contents: []
  };
  let failure = {
    contents: undefined
  };
  let notations = [
    "Uw2 Dw2",
    "Rw Lw'",
    "Uw Dw' Fw Bw'"
  ];
  notations.forEach(notation => {
    let permutation = centreTransition(notation);
    if (permutation.TAG === "Ok") {
      generators.contents = generators.contents.concat([permutation._0]);
    } else {
      failure.contents = permutation._0;
    }
  });
  let z2 = [
    1,
    0,
    3,
    2,
    5,
    4,
    7,
    6,
    9,
    8,
    11,
    10,
    13,
    12,
    15,
    14,
    21,
    20,
    23,
    22,
    17,
    16,
    19,
    18
  ];
  let reason = failure.contents;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  } else {
    return {
      TAG: "Ok",
      _0: [
        generators.contents[0],
        generators.contents[1],
        z2,
        generators.contents[2]
      ]
    };
  }
}

function centreSymmetryPermutations() {
  let reason = centreSymmetryGenerators();
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let generators = reason._0;
  let identity = Stdlib_Array.make(24, 0);
  for (let slot = 0; slot <= 23; ++slot) {
    identity[slot] = slot;
  }
  let permutations = [];
  let current = identity;
  for (let index = 0; index <= 47; ++index) {
    permutations = permutations.concat([current]);
    current = composeCentrePermutations(current, generators[0]);
    if (index % 2 === 1) {
      current = composeCentrePermutations(current, generators[1]);
    }
    if (index % 8 === 7) {
      current = composeCentrePermutations(current, generators[2]);
    }
    if (index % 16 === 15) {
      current = composeCentrePermutations(current, generators[3]);
    }
  }
  return {
    TAG: "Ok",
    _0: permutations
  };
}

function canonicalUdRank(rawRank) {
  if (rawRank < 0 || rawRank >= centreCoordinateSize) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "Invalid phase-one centre rank."
      }
    };
  }
  let reason = centreSymmetryPermutations();
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let bestRank = {
    contents: rawRank
  };
  let bestSymmetry = {
    contents: 0
  };
  reason._0.forEach((permutation, symmetry) => {
    let candidate = transitionUdRank(rawRank, permutation);
    if (candidate < bestRank.contents) {
      bestRank.contents = candidate;
      bestSymmetry.contents = symmetry;
      return;
    }
  });
  return {
    TAG: "Ok",
    _0: {
      rawRank: bestRank.contents,
      symmetry: bestSymmetry.contents
    }
  };
}

function inverseCentreSymmetryIndices(symmetries) {
  let inverses = Stdlib_Array.make(48, -1);
  for (let firstIndex = 0; firstIndex <= 47; ++firstIndex) {
    for (let secondIndex = 0; secondIndex <= 47; ++secondIndex) {
      let combined = composeCentrePermutations(symmetries[firstIndex], symmetries[secondIndex]);
      let identity = true;
      for (let slot = 0; slot <= 23; ++slot) {
        if (combined[slot] !== slot) {
          identity = false;
        }
      }
      if (identity) {
        inverses[firstIndex] = secondIndex;
      }
    }
  }
  return inverses;
}

function buildCentreSymmetryMap() {
  let reason = centreSymmetryPermutations();
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let symmetries = reason._0;
  let rawToSymmetry = Stdlib_Array.make(centreCoordinateSize, -1);
  let inverses = inverseCentreSymmetryIndices(symmetries);
  let representatives = [];
  for (let rawRank = 0; rawRank < centreCoordinateSize; ++rawRank) {
    if (rawToSymmetry[rawRank] === -1) {
      let compactRank = representatives.length;
      representatives = representatives.concat([rawRank]);
      symmetries.forEach((permutation, symmetry) => {
        let orbitRank = transitionUdRank(rawRank, permutation);
        if (rawToSymmetry[orbitRank] !== -1) {
          return;
        }
        let inverse = inverses[symmetry];
        rawToSymmetry[orbitRank] = (compactRank << 6) + inverse | 0;
      });
    }
  }
  return {
    TAG: "Ok",
    _0: {
      rawToSymmetry: rawToSymmetry,
      representatives: representatives
    }
  };
}

function createPackedPruning(size) {
  return Stdlib_Array.make((size + 1 | 0) / 2 | 0, 255);
}

function buildSymmetryCentrePruning(maximumDepth) {
  let reason = buildCentreSymmetryMap();
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let symmetryMap = reason._0;
  let transitions = {
    contents: []
  };
  let failure = {
    contents: undefined
  };
  centreMoveNotations.forEach(notation => {
    let permutation = centreTransition(notation);
    if (permutation.TAG === "Ok") {
      transitions.contents = transitions.contents.concat([permutation._0]);
    } else {
      failure.contents = permutation._0;
    }
  });
  let reason$1 = failure.contents;
  if (reason$1 !== undefined) {
    return {
      TAG: "Error",
      _0: reason$1
    };
  }
  let table = createPackedPruning(symmetryMap.representatives.length);
  let queue = Stdlib_Array.make(symmetryMap.representatives.length, 0);
  let head = 0;
  let tail = {
    contents: 1
  };
  setPruningDepth(table, 0, 0);
  queue[0] = 0;
  while (head < tail.contents) {
    let compactRank = queue[head];
    head = head + 1 | 0;
    let depth = pruningDepth(table, compactRank);
    if (depth < maximumDepth) {
      let rawRank = symmetryMap.representatives[compactRank];
      transitions.contents.forEach(permutation => {
        let successorRaw = transitionUdRank(rawRank, permutation);
        let successorCompact = symmetryMap.rawToSymmetry[successorRaw] / 64 | 0;
        if (pruningDepth(table, successorCompact) === 15) {
          setPruningDepth(table, successorCompact, depth + 1 | 0);
          queue[tail.contents] = successorCompact;
          tail.contents = tail.contents + 1 | 0;
          return;
        }
      });
    }
  };
  return {
    TAG: "Ok",
    _0: table
  };
}

let phase2Moves = [
  {
    notation: "U",
    faceId: 0
  },
  {
    notation: "U2",
    faceId: 0
  },
  {
    notation: "U'",
    faceId: 0
  },
  {
    notation: "R",
    faceId: 1
  },
  {
    notation: "R2",
    faceId: 1
  },
  {
    notation: "R'",
    faceId: 1
  },
  {
    notation: "F",
    faceId: 2
  },
  {
    notation: "F2",
    faceId: 2
  },
  {
    notation: "F'",
    faceId: 2
  },
  {
    notation: "D",
    faceId: 3
  },
  {
    notation: "D2",
    faceId: 3
  },
  {
    notation: "D'",
    faceId: 3
  },
  {
    notation: "L",
    faceId: 4
  },
  {
    notation: "L2",
    faceId: 4
  },
  {
    notation: "L'",
    faceId: 4
  },
  {
    notation: "B",
    faceId: 5
  },
  {
    notation: "B2",
    faceId: 5
  },
  {
    notation: "B'",
    faceId: 5
  },
  {
    notation: "Uw2",
    faceId: 6
  },
  {
    notation: "Rw",
    faceId: 7
  },
  {
    notation: "Rw2",
    faceId: 7
  },
  {
    notation: "Rw'",
    faceId: 7
  },
  {
    notation: "Fw2",
    faceId: 8
  },
  {
    notation: "Dw2",
    faceId: 9
  },
  {
    notation: "Lw",
    faceId: 10
  },
  {
    notation: "Lw2",
    faceId: 10
  },
  {
    notation: "Lw'",
    faceId: 10
  },
  {
    notation: "Bw2",
    faceId: 11
  }
];

let phase3Moves = [
  {
    notation: "U",
    faceId: 0
  },
  {
    notation: "U2",
    faceId: 0
  },
  {
    notation: "U'",
    faceId: 0
  },
  {
    notation: "R2",
    faceId: 1
  },
  {
    notation: "F",
    faceId: 2
  },
  {
    notation: "F2",
    faceId: 2
  },
  {
    notation: "F'",
    faceId: 2
  },
  {
    notation: "D",
    faceId: 3
  },
  {
    notation: "D2",
    faceId: 3
  },
  {
    notation: "D'",
    faceId: 3
  },
  {
    notation: "L2",
    faceId: 4
  },
  {
    notation: "B",
    faceId: 5
  },
  {
    notation: "B2",
    faceId: 5
  },
  {
    notation: "B'",
    faceId: 5
  },
  {
    notation: "Uw2",
    faceId: 6
  },
  {
    notation: "Rw2",
    faceId: 7
  },
  {
    notation: "Fw2",
    faceId: 8
  },
  {
    notation: "Dw2",
    faceId: 9
  },
  {
    notation: "Lw2",
    faceId: 10
  },
  {
    notation: "Bw2",
    faceId: 11
  }
];

function axisTransitionAllowed(lastFaceId, nextFaceId) {
  if (lastFaceId < 0) {
    return true;
  } else if (lastFaceId !== nextFaceId) {
    if (lastFaceId % 3 !== nextFaceId % 3) {
      return true;
    } else {
      return lastFaceId < nextFaceId;
    }
  } else {
    return false;
  }
}

function buildCentrePruning(maximumDepth) {
  let transitions = {
    contents: []
  };
  let error = {
    contents: undefined
  };
  centreMoveNotations.forEach(notation => {
    let permutation = centreTransition(notation);
    if (permutation.TAG === "Ok") {
      transitions.contents = transitions.contents.concat([permutation._0]);
    } else {
      error.contents = permutation._0;
    }
  });
  let reason = error.contents;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  }
  let table = createCentrePruning();
  let queue = Stdlib_Array.make(centreCoordinateSize, 0);
  let head = 0;
  let tail = {
    contents: 1
  };
  setPruningDepth(table, 0, 0);
  queue[0] = 0;
  while (head < tail.contents) {
    let current = queue[head];
    head = head + 1 | 0;
    let depth = pruningDepth(table, current);
    if (depth < maximumDepth) {
      transitions.contents.forEach(permutation => {
        let next = transitionUdRank(current, permutation);
        if (pruningDepth(table, next) === 15) {
          setPruningDepth(table, next, depth + 1 | 0);
          queue[tail.contents] = next;
          tail.contents = tail.contents + 1 | 0;
          return;
        }
      });
    }
  };
  return {
    TAG: "Ok",
    _0: table
  };
}

function rankFbCentres(centres) {
  if (centres.length !== 24) {
    return -1;
  }
  let selected = [];
  for (let slot = 0; slot <= 23; ++slot) {
    let colour = String(centres[slot]);
    if (colour === "F" || colour === "B") {
      selected = selected.concat([slot]);
    }
  }
  return rankUdSlots(selected);
}

let phase2TargetFbRank = rankUdSlots([
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15
]);

let phase2FbRotation = centreTransition("x");

let phase2FbRotationInverse = centreTransition("x'");

function phase2UdDistance(udRank, symmetryMap, symmetryTable) {
  if (udRank < 0 || udRank >= centreCoordinateSize) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "Invalid phase-two U/D rank."
      }
    };
  }
  let compactRank = symmetryMap.rawToSymmetry[udRank] / 64 | 0;
  return {
    TAG: "Ok",
    _0: pruningDepth(symmetryTable, compactRank)
  };
}

function phase2FbDistance(fbRank, symmetryMap, symmetryTable) {
  if (phase2FbRotationInverse.TAG === "Ok") {
    return phase2UdDistance(transitionUdRank(fbRank, phase2FbRotationInverse._0), symmetryMap, symmetryTable);
  } else {
    return {
      TAG: "Error",
      _0: phase2FbRotationInverse._0
    };
  }
}

function phase2CombinedDistance(udRank, fbRank, symmetryMap, symmetryTable) {
  let match = phase2UdDistance(udRank, symmetryMap, symmetryTable);
  let match$1 = phase2FbDistance(fbRank, symmetryMap, symmetryTable);
  if (match.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: match._0
    };
  }
  let udDistance = match._0;
  if (match$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: match$1._0
    };
  }
  let fbDistance = match$1._0;
  return {
    TAG: "Ok",
    _0: udDistance > fbDistance ? udDistance : fbDistance
  };
}

export {
  encodeFacelets,
  decodeFacelets,
  centreFaceletIndices,
  extractCentres,
  wingFaceletIndices,
  extractWings,
  cornerFaceletIndices,
  extractCorners,
  applyTransition,
  serialFace,
  markerState,
  rawMarkerIndex,
  centreSlotForFacelet,
  centreTransition,
  applyCentreTransition,
  choose,
  rankUdCentres,
  rankUdSlots,
  unrankUdCentres,
  centreCoordinateSize,
  createCentrePruning,
  pruningDepth,
  setPruningDepth,
  centreMoveNotations,
  transitionUdRank,
  composeCentrePermutations,
  centreSymmetryGenerators,
  centreSymmetryPermutations,
  canonicalUdRank,
  inverseCentreSymmetryIndices,
  buildCentreSymmetryMap,
  createPackedPruning,
  buildSymmetryCentrePruning,
  phase2Moves,
  phase3Moves,
  axisTransitionAllowed,
  buildCentrePruning,
  rankFbCentres,
  phase2TargetFbRank,
  phase2FbRotation,
  phase2FbRotationInverse,
  phase2UdDistance,
  phase2FbDistance,
  phase2CombinedDistance,
}
/* centreCoordinateSize Not a pure module */
