// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoveParser from "../Move/MoveParser.res.mjs";
import * as StateTypes from "../State/StateTypes.res.mjs";
import * as FaceletCodec from "../State/FaceletCodec.res.mjs";
import * as MoveExecutor from "../Move/MoveExecutor.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function encodeFacelets(state) {
  if (state.size !== 4) {
    return {
      TAG: "Error",
      _0: {
        TAG: "UnsupportedState",
        _0: "Three-phase 4×4 requires a complete 4×4 state."
      }
    };
  } else {
    return {
      TAG: "Ok",
      _0: StateTypes.serializationOrder.map(face => state.facelets[StateTypes.storageIndex(face)].map(StateTypes.faceToChar).join("")).join("")
    };
  }
}

function decodeFacelets(facelets) {
  let state = FaceletCodec.parse(4, facelets);
  if (state.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: state._0
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidFacelets",
        _0: "Three-phase 4×4 requires 96 legal URFDLB facelets."
      }
    };
  }
}

let centreFaceletIndices = [
  5,
  6,
  10,
  9,
  53,
  54,
  58,
  57,
  37,
  38,
  42,
  41,
  85,
  86,
  90,
  89,
  21,
  22,
  26,
  25,
  69,
  70,
  74,
  73
];

function extractCentres(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return "";
  }
  let facelets$1 = facelets._0;
  return centreFaceletIndices.map(index => String(facelets$1[index])).join("");
}

let wingFaceletIndices = [
  [
    13,
    33
  ],
  [
    4,
    65
  ],
  [
    2,
    81
  ],
  [
    11,
    17
  ],
  [
    61,
    94
  ],
  [
    52,
    78
  ],
  [
    50,
    46
  ],
  [
    59,
    30
  ],
  [
    75,
    40
  ],
  [
    68,
    87
  ],
  [
    27,
    88
  ],
  [
    20,
    39
  ],
  [
    34,
    14
  ],
  [
    66,
    8
  ],
  [
    82,
    1
  ],
  [
    18,
    7
  ],
  [
    93,
    62
  ],
  [
    77,
    56
  ],
  [
    45,
    49
  ],
  [
    29,
    55
  ],
  [
    36,
    71
  ],
  [
    91,
    72
  ],
  [
    84,
    23
  ],
  [
    43,
    24
  ]
];

function extractWings(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return [];
  }
  let facelets$1 = facelets._0;
  return wingFaceletIndices.map(param => String(facelets$1[param[0]]) + String(facelets$1[param[1]]));
}

let cornerFaceletIndices = [
  [
    15,
    16,
    35
  ],
  [
    12,
    32,
    67
  ],
  [
    0,
    64,
    83
  ],
  [
    3,
    80,
    19
  ],
  [
    51,
    47,
    28
  ],
  [
    48,
    79,
    44
  ],
  [
    60,
    95,
    76
  ],
  [
    63,
    31,
    92
  ]
];

function extractCorners(state) {
  let facelets = encodeFacelets(state);
  if (facelets.TAG !== "Ok") {
    return [];
  }
  let facelets$1 = facelets._0;
  return cornerFaceletIndices.map(indices => indices.map(index => String(facelets$1[index])).join(""));
}

function applyTransition(state, notation) {
  if (state.size !== 4) {
    return {
      TAG: "Error",
      _0: {
        TAG: "UnsupportedState",
        _0: "Three-phase transitions require a 4×4 state."
      }
    };
  }
  let alg = MoveParser.parseWithOptions(4, "Wide", "Modern", notation);
  if (alg.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "Invalid 4×4 transition notation."
      }
    };
  }
  let next = MoveExecutor.applyAlg(state, alg._0);
  if (next.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: next._0
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidTransition",
        _0: "4×4 transition could not be applied."
      }
    };
  }
}

function serialFace(index) {
  switch (index) {
    case 0 :
      return "U";
    case 1 :
      return "R";
    case 2 :
      return "F";
    case 3 :
      return "D";
    case 4 :
      return "L";
    default:
      return "B";
  }
}

function markerState() {
  return {
    size: 4,
    facelets: StateTypes.storageOrder.map(param => Stdlib_Array.make(16, "U"))
  };
}

function rawMarkerIndex(state) {
  let found = -1;
  for (let serialIndex = 0; serialIndex <= 5; ++serialIndex) {
    let stickers = state.facelets[StateTypes.storageIndex(serialFace(serialIndex))];
    for (let stickerIndex = 0; stickerIndex <= 15; ++stickerIndex) {
      if (stickers[stickerIndex] === "D") {
        found = (serialIndex << 4) + stickerIndex | 0;
      }
    }
  }
  return found;
}

function centreSlotForFacelet(rawIndex) {
  let found = -1;
  for (let slot = 0; slot <= 23; ++slot) {
    if (centreFaceletIndices[slot] === rawIndex) {
      found = slot;
    }
  }
  return found;
}

function centreTransition(notation) {
  let permutation = Stdlib_Array.make(24, 0);
  let failure;
  for (let sourceSlot = 0; sourceSlot <= 23; ++sourceSlot) {
    let marker = markerState();
    let sourceFacelet = centreFaceletIndices[sourceSlot];
    let face = serialFace(sourceFacelet / 16 | 0);
    marker.facelets[StateTypes.storageIndex(face)][sourceFacelet % 16] = "D";
    let error = applyTransition(marker, notation);
    if (error.TAG === "Ok") {
      let targetSlot = centreSlotForFacelet(rawMarkerIndex(error._0));
      if (targetSlot === -1) {
        failure = {
          TAG: "InvalidTransition",
          _0: "Transition moves a centre marker outside the centre coordinate."
        };
      } else {
        permutation[targetSlot] = sourceSlot;
      }
    } else {
      failure = error._0;
    }
  }
  let error$1 = failure;
  if (error$1 !== undefined) {
    return {
      TAG: "Error",
      _0: error$1
    };
  } else {
    return {
      TAG: "Ok",
      _0: permutation
    };
  }
}

function applyCentreTransition(centres, permutation) {
  return permutation.map(source => String(centres[source])).join("");
}

export {
  encodeFacelets,
  decodeFacelets,
  centreFaceletIndices,
  extractCentres,
  wingFaceletIndices,
  extractWings,
  cornerFaceletIndices,
  extractCorners,
  applyTransition,
  serialFace,
  markerState,
  rawMarkerIndex,
  centreSlotForFacelet,
  centreTransition,
  applyCentreTransition,
}
/* No side effect */
