// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PieceReducer from "../State/PieceReducer.res.mjs";

function isIdentity(permutation) {
  return permutation.every((piece, slot) => piece === slot);
}

function allZero(values) {
  return values.every(value => value === 0);
}

function middleSliceIsPlaced(edgePermutation) {
  let placed = true;
  for (let slot = 8; slot <= 11; ++slot) {
    if (edgePermutation[slot] < 8) {
      placed = false;
    }
  }
  return placed;
}

function isPhase1Solved(state) {
  let pieces = PieceReducer.reduce(state);
  if (pieces.TAG !== "Ok") {
    return false;
  }
  let pieces$1 = pieces._0;
  if (pieces$1.size === 3 && allZero(pieces$1.co) && allZero(pieces$1.eo)) {
    return middleSliceIsPlaced(pieces$1.ep);
  } else {
    return false;
  }
}

function solve(state) {
  if (state.size !== 3) {
    return {
      TAG: "Error",
      _0: {
        TAG: "UnsupportedSize",
        _0: state.size
      }
    };
  }
  let error = PieceReducer.reduce(state);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidState",
        _0: error._0
      }
    };
  }
  let pieces = error._0;
  if (isIdentity(pieces.cp) && allZero(pieces.co) && isIdentity(pieces.ep) && allZero(pieces.eo)) {
    return {
      TAG: "Ok",
      _0: {
        alg: [],
        moveCount: 0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: "SearchFailed"
    };
  }
}

export {
  isIdentity,
  allZero,
  middleSliceIsPlaced,
  isPhase1Solved,
  solve,
}
/* No side effect */
