// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NetCodec from "./NetCodec.res.mjs";
import * as StateTypes from "./StateTypes.res.mjs";
import * as FaceletCodec from "./FaceletCodec.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let faceOrder = [
  "U",
  "L",
  "F",
  "R",
  "B",
  "D"
];

function mapping(scheme) {
  if (typeof scheme !== "object") {
    if (scheme === "Western") {
      return "WOGRBY";
    } else {
      return "WOBRGY";
    }
  } else {
    return scheme._0;
  }
}

function validateScheme(scheme) {
  let value = mapping(scheme);
  if (value.length !== 6) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidColourScheme",
        _0: "A custom colour scheme must contain exactly six letters."
      }
    };
  }
  let seen = "";
  let error;
  for (let index = 0; index <= 5; ++index) {
    let character = String(value[index]);
    let code = character.charCodeAt(0);
    if (code < 65 || code > 90) {
      error = {
        TAG: "InvalidColourScheme",
        _0: "Colour symbols must be uppercase ASCII letters."
      };
    } else if (seen.includes(character)) {
      error = {
        TAG: "InvalidColourScheme",
        _0: "A colour scheme must contain six distinct letters."
      };
    } else {
      seen = seen + character;
    }
  }
  let reason = error;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  } else {
    return {
      TAG: "Ok",
      _0: value
    };
  }
}

function faceToColour(mapping, face) {
  let index;
  switch (face) {
    case "U" :
      index = 0;
      break;
    case "L" :
      index = 1;
      break;
    case "F" :
      index = 2;
      break;
    case "R" :
      index = 3;
      break;
    case "B" :
      index = 4;
      break;
    case "D" :
      index = 5;
      break;
  }
  return String(mapping[index]);
}

function colourToFace(mapping, colour) {
  let found;
  for (let index = 0; index <= 5; ++index) {
    let candidate = String(mapping[index]);
    if (candidate === colour) {
      found = faceOrder[index];
    }
  }
  return found;
}

function translateFromFaces(mapping, input) {
  let output = Stdlib_Array.make(input.length, "");
  for (let index = 0, index_finish = input.length; index < index_finish; ++index) {
    let character = String(input[index]);
    let face = StateTypes.charToFace(character);
    output[index] = face !== undefined ? faceToColour(mapping, face) : character;
  }
  return output.join("");
}

function translateToFaces(mapping, input) {
  let output = Stdlib_Array.make(input.length, "");
  let error;
  for (let index = 0, index_finish = input.length; index < index_finish; ++index) {
    let character = String(input[index]);
    if (character === " " || character === "\t" || character === "\n" || character === "\r") {
      output[index] = character;
    } else {
      let face = colourToFace(mapping, character);
      if (face !== undefined) {
        output[index] = StateTypes.faceToChar(face);
      } else {
        error = {
          TAG: "InvalidColour",
          index: index,
          character: character
        };
      }
    }
  }
  let reason = error;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  } else {
    return {
      TAG: "Ok",
      _0: output.join("")
    };
  }
}

function renderCompact(scheme, state) {
  let reason = validateScheme(scheme);
  if (reason.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: translateFromFaces(reason._0, FaceletCodec.render(state))
    };
  } else {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
}

function parseCompact(scheme, size, input) {
  let reason = validateScheme(scheme);
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let reason$1 = translateToFaces(reason._0, input);
  if (reason$1.TAG === "Ok") {
    return FaceletCodec.parse(size, reason$1._0);
  } else {
    return {
      TAG: "Error",
      _0: reason$1._0
    };
  }
}

function renderNet(scheme, state) {
  let reason = validateScheme(scheme);
  if (reason.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: translateFromFaces(reason._0, NetCodec.render(state))
    };
  } else {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
}

function parseNet(scheme, size, input) {
  let reason = validateScheme(scheme);
  if (reason.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: reason._0
    };
  }
  let reason$1 = translateToFaces(reason._0, input);
  if (reason$1.TAG === "Ok") {
    return NetCodec.parse(size, reason$1._0);
  } else {
    return {
      TAG: "Error",
      _0: reason$1._0
    };
  }
}

export {
  faceOrder,
  mapping,
  validateScheme,
  faceToColour,
  colourToFace,
  translateFromFaces,
  translateToFaces,
  renderCompact,
  parseCompact,
  renderNet,
  parseNet,
}
/* No side effect */
