// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateTypes from "./StateTypes.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function render(state) {
  return StateTypes.serializationOrder.map(face => {
    let stickers = state.facelets[StateTypes.storageIndex(face)];
    return stickers.map(StateTypes.faceToChar).join("");
  }).join("");
}

function parse(size, input) {
  if (!StateTypes.isSupportedSize(size)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidSize",
        _0: "Cube size must be between 2 and 5."
      }
    };
  }
  let compact = input.trim();
  let expected = (6 * size | 0) * size | 0;
  if (compact.length !== expected) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidLength",
        expected: expected,
        actual: compact.length
      }
    };
  }
  let counts = Stdlib_Array.make(6, 0);
  let parsed = Stdlib_Array.make(expected, "U");
  let error;
  for (let index = 0; index < expected; ++index) {
    let character = String(compact[index]);
    let face = StateTypes.charToFace(character);
    if (face !== undefined) {
      parsed[index] = face;
      let countIndex = StateTypes.storageIndex(face);
      counts[countIndex] = counts[countIndex] + 1 | 0;
    } else {
      error = {
        TAG: "InvalidFacelet",
        index: index,
        character: character
      };
    }
  }
  let reason = error;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  }
  let stickersPerFace = size * size | 0;
  let countError;
  for (let index$1 = 0; index$1 <= 5; ++index$1) {
    if (counts[index$1] !== stickersPerFace) {
      countError = {
        TAG: "InvalidColourCount",
        face: StateTypes.storageOrder[index$1],
        expected: stickersPerFace,
        actual: counts[index$1]
      };
    }
  }
  let reason$1 = countError;
  if (reason$1 !== undefined) {
    return {
      TAG: "Error",
      _0: reason$1
    };
  }
  let facelets = StateTypes.storageOrder.map(param => Stdlib_Array.make(stickersPerFace, "U"));
  for (let serialFaceIndex = 0; serialFaceIndex <= 5; ++serialFaceIndex) {
    let targetFace = StateTypes.serializationOrder[serialFaceIndex];
    let target = facelets[StateTypes.storageIndex(targetFace)];
    for (let stickerIndex = 0; stickerIndex < stickersPerFace; ++stickerIndex) {
      target[stickerIndex] = parsed[(serialFaceIndex * stickersPerFace | 0) + stickerIndex | 0];
    }
  }
  return {
    TAG: "Ok",
    _0: {
      size: size,
      facelets: facelets
    }
  };
}

export {
  render,
  parse,
}
/* No side effect */
