// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StateTypes from "./StateTypes.res.mjs";
import * as FaceletCodec from "./FaceletCodec.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function row(stickers, start, size) {
  let values = Stdlib_Array.make(size, "");
  for (let index = 0; index < size; ++index) {
    values[index] = StateTypes.faceToChar(stickers[start + index | 0]);
  }
  return values.join(" ");
}

function render(state) {
  let size = state.size;
  let indent = Stdlib_Array.make((size << 1), " ").join("");
  let u = state.facelets[StateTypes.storageIndex("U")];
  let l = state.facelets[StateTypes.storageIndex("L")];
  let f = state.facelets[StateTypes.storageIndex("F")];
  let r = state.facelets[StateTypes.storageIndex("R")];
  let b = state.facelets[StateTypes.storageIndex("B")];
  let d = state.facelets[StateTypes.storageIndex("D")];
  let lines = Stdlib_Array.make(size * 3 | 0, "");
  for (let line = 0; line < size; ++line) {
    lines[line] = indent + row(u, line * size | 0, size);
    lines[size + line | 0] = [
      row(l, line * size | 0, size),
      row(f, line * size | 0, size),
      row(r, line * size | 0, size),
      row(b, line * size | 0, size)
    ].join(" ");
    lines[(size << 1) + line | 0] = indent + row(d, line * size | 0, size);
  }
  return lines.join("\n");
}

function parseRow(line, offset, size) {
  let expectedLength = (size << 1) - 1 | 0;
  if (line.length < (offset + expectedLength | 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidNet",
        _0: "A net row is shorter than required."
      }
    };
  }
  let output = Stdlib_Array.make(size, "");
  let error;
  for (let index = 0; index < expectedLength; ++index) {
    let character = String(line[offset + index | 0]);
    if (index % 2 === 0) {
      let match = StateTypes.charToFace(character);
      if (match !== undefined) {
        output[index / 2 | 0] = character;
      } else {
        error = {
          TAG: "InvalidNet",
          _0: "Net rows may contain only URFDLB stickers."
        };
      }
    } else if (character !== " ") {
      error = {
        TAG: "InvalidNet",
        _0: "Net stickers must be separated by one ASCII space."
      };
    }
  }
  let reason = error;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  } else {
    return {
      TAG: "Ok",
      _0: output.join("")
    };
  }
}

function parse(size, input) {
  if (!StateTypes.isSupportedSize(size)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidSize",
        _0: "Cube size must be between 2 and 5."
      }
    };
  }
  let lines = input.split("\n");
  if (lines.length !== (size * 3 | 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidNet",
        _0: "A net must contain exactly 3 × size lines."
      }
    };
  }
  let indent = (size << 1);
  let upper = Stdlib_Array.make(size, "");
  let middle = Stdlib_Array.make(size, "");
  let lower = Stdlib_Array.make(size, "");
  let error;
  for (let lineIndex = 0; lineIndex < size; ++lineIndex) {
    let topLine = lines[lineIndex];
    let bottomLine = lines[(size << 1) + lineIndex | 0];
    if (topLine.length !== ((indent + (size << 1) | 0) - 1 | 0) || bottomLine.length !== ((indent + (size << 1) | 0) - 1 | 0)) {
      error = {
        TAG: "InvalidNet",
        _0: "Top and bottom rows must use the canonical indentation."
      };
    } else {
      for (let prefixIndex = 0; prefixIndex < indent; ++prefixIndex) {
        if (String(topLine[prefixIndex]) !== " " || String(bottomLine[prefixIndex]) !== " ") {
          error = {
            TAG: "InvalidNet",
            _0: "Top and bottom rows must use ASCII-space indentation."
          };
        }
      }
      let value = parseRow(topLine, indent, size);
      if (value.TAG === "Ok") {
        upper[lineIndex] = value._0;
      } else {
        error = value._0;
      }
      let value$1 = parseRow(bottomLine, indent, size);
      if (value$1.TAG === "Ok") {
        lower[lineIndex] = value$1._0;
      } else {
        error = value$1._0;
      }
    }
    let middleLine = lines[size + lineIndex | 0];
    if (middleLine.length !== ((size << 3) - 1 | 0)) {
      error = {
        TAG: "InvalidNet",
        _0: "Middle rows must contain four adjacent face rows."
      };
    } else {
      let values = Stdlib_Array.make(4, "");
      for (let faceIndex = 0; faceIndex <= 3; ++faceIndex) {
        let value$2 = parseRow(middleLine, ((faceIndex * size | 0) << 1), size);
        if (value$2.TAG === "Ok") {
          values[faceIndex] = value$2._0;
        } else {
          error = value$2._0;
        }
      }
      middle[lineIndex] = values.join("");
    }
  }
  let reason = error;
  if (reason !== undefined) {
    return {
      TAG: "Error",
      _0: reason
    };
  }
  let serial = [
    upper.join(""),
    middle.map(line => line.slice((size << 1), 3 * size | 0)).join(""),
    middle.map(line => line.slice(size, (size << 1))).join(""),
    lower.join(""),
    middle.map(line => line.slice(0, size)).join(""),
    middle.map(line => line.slice(3 * size | 0, (size << 2))).join("")
  ].join("");
  return FaceletCodec.parse(size, serial);
}

export {
  row,
  render,
  parseRow,
  parse,
}
/* No side effect */
