// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Math from "@rescript/runtime/lib/es6/Stdlib_Math.js";
import * as FaceletCodec from "./FaceletCodec.res.mjs";
import * as PieceReducer from "./PieceReducer.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

let last = 3;

let faces = [
  "U",
  "R",
  "F",
  "D",
  "L",
  "B"
];

function faceIndex(face) {
  switch (face) {
    case "B" :
      return 5;
    case "D" :
      return 3;
    case "F" :
      return 2;
    case "L" :
      return 4;
    case "R" :
      return 1;
    case "U" :
      return 0;
    default:
      return -1;
  }
}

let centreIndices = [
  5,
  6,
  9,
  10
];

let cornerLocalIndices = [
  0,
  3,
  12,
  15
];

function serialIndex(face, row, column) {
  return ((faceIndex(face) << 4) + (row << 2) | 0) + column | 0;
}

function stickerFor(face, row, column) {
  switch (face) {
    case "B" :
      return {
        position: {
          x: last - column | 0,
          y: last - row | 0,
          z: 0
        },
        normal: {
          x: 0,
          y: 0,
          z: -1
        }
      };
    case "D" :
      return {
        position: {
          x: column,
          y: 0,
          z: last - row | 0
        },
        normal: {
          x: 0,
          y: -1,
          z: 0
        }
      };
    case "F" :
      return {
        position: {
          x: column,
          y: last - row | 0,
          z: last
        },
        normal: {
          x: 0,
          y: 0,
          z: 1
        }
      };
    case "R" :
      return {
        position: {
          x: last,
          y: last - row | 0,
          z: last - column | 0
        },
        normal: {
          x: 1,
          y: 0,
          z: 0
        }
      };
    case "U" :
      return {
        position: {
          x: column,
          y: last,
          z: row
        },
        normal: {
          x: 0,
          y: 1,
          z: 0
        }
      };
    default:
      return {
        position: {
          x: 0,
          y: last - row | 0,
          z: column
        },
        normal: {
          x: -1,
          y: 0,
          z: 0
        }
      };
  }
}

function faceletFor(sticker) {
  let match = sticker.position;
  let z = match.z;
  let y = match.y;
  let x = match.x;
  let normal = sticker.normal;
  if (normal.y === 1) {
    return [
      "U",
      z,
      x
    ];
  } else if (normal.y === -1) {
    return [
      "D",
      last - z | 0,
      x
    ];
  } else if (normal.z === 1) {
    return [
      "F",
      last - y | 0,
      x
    ];
  } else if (normal.z === -1) {
    return [
      "B",
      last - y | 0,
      last - x | 0
    ];
  } else if (normal.x === 1) {
    return [
      "R",
      last - y | 0,
      last - z | 0
    ];
  } else {
    return [
      "L",
      last - y | 0,
      z
    ];
  }
}

function indexFor(sticker) {
  let match = faceletFor(sticker);
  return serialIndex(match[0], match[1], match[2]);
}

function positionKey(param) {
  return param.x.toString() + `/` + param.y.toString() + `/` + param.z.toString();
}

function rotate(vector, axis, direction, coordinate) {
  let invert = value => {
    if (coordinate) {
      return last - value | 0;
    } else {
      return -value | 0;
    }
  };
  switch (axis) {
    case "X" :
      if (direction === 1) {
        return {
          x: vector.x,
          y: invert(vector.z),
          z: vector.y
        };
      } else {
        return {
          x: vector.x,
          y: vector.z,
          z: invert(vector.y)
        };
      }
    case "Y" :
      if (direction === 1) {
        return {
          x: vector.z,
          y: vector.y,
          z: invert(vector.x)
        };
      } else {
        return {
          x: invert(vector.z),
          y: vector.y,
          z: vector.x
        };
      }
    case "Z" :
      if (direction === 1) {
        return {
          x: invert(vector.y),
          y: vector.x,
          z: vector.z
        };
      } else {
        return {
          x: vector.y,
          y: invert(vector.x),
          z: vector.z
        };
      }
  }
}

function applyGenerator(sticker, generator) {
  if (generator.affected(sticker.position)) {
    return {
      position: rotate(sticker.position, generator.axis, generator.direction, true),
      normal: rotate(sticker.normal, generator.axis, generator.direction, false)
    };
  } else {
    return sticker;
  }
}

let generators = [
  {
    axis: "X",
    direction: -1,
    affected: param => param.x === last
  },
  {
    axis: "X",
    direction: 1,
    affected: param => param.x === 0
  },
  {
    axis: "Y",
    direction: -1,
    affected: param => param.y === last
  },
  {
    axis: "Y",
    direction: 1,
    affected: param => param.y === 0
  },
  {
    axis: "Z",
    direction: -1,
    affected: param => param.z === last
  },
  {
    axis: "Z",
    direction: 1,
    affected: param => param.z === 0
  },
  {
    axis: "X",
    direction: -1,
    affected: param => param.x === (last - 1 | 0)
  },
  {
    axis: "X",
    direction: 1,
    affected: param => param.x === 1
  },
  {
    axis: "Y",
    direction: -1,
    affected: param => param.y === (last - 1 | 0)
  },
  {
    axis: "Y",
    direction: 1,
    affected: param => param.y === 1
  },
  {
    axis: "Z",
    direction: -1,
    affected: param => param.z === (last - 1 | 0)
  },
  {
    axis: "Z",
    direction: 1,
    affected: param => param.z === 1
  }
];

function wingSlots() {
  let grouped = {};
  faces.forEach(face => {
    for (let row = 0; row <= 3; ++row) {
      for (let column = 0; column <= 3; ++column) {
        let outer = row === 0 || row === last || column === 0 || column === last;
        let corner = (row === 0 || row === last) && (column === 0 || column === last);
        if (outer && !corner) {
          let index = serialIndex(face, row, column);
          let key = positionKey(stickerFor(face, row, column).position);
          let arr = grouped[key];
          let existing = arr !== undefined ? arr : [];
          existing.push(index);
          grouped[key] = existing;
        }
      }
    }
  });
  let slots = Object.values(grouped).map(indices => {
    let sorted = indices.slice();
    sorted.sort(Primitive_int.compare);
    return sorted;
  });
  slots.sort((a, b) => {
    let a0 = a[0];
    let b0 = b[0];
    return Primitive_int.compare(a0, b0);
  });
  return slots.map(indices => ({
    indices: [
      indices[0],
      indices[1]
    ]
  }));
}

let allWingSlots = wingSlots();

function wingDestinations(source) {
  let match = source.indices;
  let toSticker = index => {
    let face = faces[Stdlib_Math.Int.floor(index / 16.0)];
    let local = index % 16;
    return stickerFor(face, Stdlib_Math.Int.floor(local / 4), local % 4);
  };
  let initial_0 = toSticker(match[0]);
  let initial_1 = toSticker(match[1]);
  let initial = [
    initial_0,
    initial_1
  ];
  let queue = [initial];
  let seen = new Set();
  let destinations = [];
  while (queue.length !== 0) {
    let match$1 = queue.shift();
    let right = match$1[1];
    let left = match$1[0];
    let leftIndex = indexFor(left);
    let rightIndex = indexFor(right);
    let key = leftIndex.toString() + `/` + rightIndex.toString();
    if (!seen.has(key)) {
      seen.add(key);
      destinations.push([
        leftIndex,
        rightIndex
      ]);
      generators.forEach(generator => {
        queue.push([
          applyGenerator(left, generator),
          applyGenerator(right, generator)
        ]);
      });
    }
  };
  return destinations;
}

let allWingDestinations = allWingSlots.map(wingDestinations);

let staticWingSourceColours = allWingSlots.map(param => {
  let match = param.indices;
  return [
    faces[Stdlib_Math.Int.floor(match[0] / 16.0)],
    faces[Stdlib_Math.Int.floor(match[1] / 16.0)]
  ];
});

let staticWingDestinations = allWingDestinations.map(destinations => {
  let result = [];
  destinations.forEach(param => {
    let second = param[1];
    let first = param[0];
    let slot = allWingSlots.findIndex(param => {
      let match = param.indices;
      let idx1 = match[1];
      let idx0 = match[0];
      if (idx0 === first || idx1 === first) {
        if (idx0 === second) {
          return true;
        } else {
          return idx1 === second;
        }
      } else {
        return false;
      }
    });
    if (slot >= 0) {
      result.push({
        first: first,
        second: second,
        slot: slot
      });
      return;
    }
  });
  return result;
});

function canComplete4x4Wings(compact) {
  if (compact.length !== 96) {
    return false;
  }
  let edgeMasks = Stdlib_Array.make(24, 0);
  let possible = true;
  let source = 0;
  while (possible && source < 24) {
    let s = source;
    let match = staticWingSourceColours[s];
    let secondColour = match[1];
    let firstColour = match[0];
    let destinations = staticWingDestinations[s];
    let mask = 0;
    for (let d = 0, d_finish = destinations.length; d < d_finish; ++d) {
      let dest = destinations[d];
      let firstVal = compact[dest.first];
      let secondVal = compact[dest.second];
      let matchFirst = (firstVal == null) ? true : firstVal === firstColour;
      let matchSecond = (secondVal == null) ? true : secondVal === secondColour;
      if (matchFirst && matchSecond) {
        mask = mask | (1 << dest.slot);
      }
    }
    if (mask === 0) {
      possible = false;
    } else {
      edgeMasks[s] = mask;
    }
    source = source + 1 | 0;
  };
  if (!possible) {
    return false;
  }
  let matchedSourceForSlot = Stdlib_Array.make(24, -1);
  let visitedMask = {
    contents: 0
  };
  let assign = source => {
    let mask = edgeMasks[source];
    let found = false;
    let slot = 0;
    while (!found && slot < 24) {
      let sl = slot;
      let bit = (1 << sl);
      if ((mask & bit) !== 0 && (visitedMask.contents & bit) === 0) {
        visitedMask.contents = visitedMask.contents | bit;
        let prevSource = matchedSourceForSlot[sl];
        if (prevSource === -1 || assign(prevSource)) {
          matchedSourceForSlot[sl] = source;
          found = true;
        }
      }
      slot = slot + 1 | 0;
    };
    return found;
  };
  let allAssigned = true;
  let src = 0;
  while (allAssigned && src < 24) {
    visitedMask.contents = 0;
    if (!assign(src)) {
      allAssigned = false;
    }
    src = src + 1 | 0;
  };
  return allAssigned;
}

function cornerState(compact) {
  let reduced = {
    contents: ""
  };
  faces.forEach(face => {
    cornerLocalIndices.forEach(index => {
      let row = Stdlib_Math.Int.floor(index / 4.0);
      let col = index % 4;
      let idx = serialIndex(face, row, col);
      reduced.contents = reduced.contents + compact.slice(idx, idx + 1 | 0);
    });
  });
  let parsed = FaceletCodec.parse(2, reduced.contents);
  if (parsed.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: "Invalid 2×2 corner facelets."
    };
  }
  let err = PieceReducer.reduce(parsed._0);
  if (err.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: PieceReducer.describeError(err._0)
    };
  }
}

function validate4x4(state) {
  if (state.size !== 4) {
    return "The 4×4 validator received a non-4×4 state.";
  }
  let compact = FaceletCodec.render(state);
  if (compact.length !== 96) {
    return "A 4×4 state must contain 96 facelets.";
  }
  let err = cornerState(compact);
  if (err.TAG !== "Ok") {
    return `Invalid 4×4 corners: ` + err._0 + `.`;
  }
  let centreCounts = {};
  faces.forEach(face => {
    centreIndices.forEach(index => {
      let row = Stdlib_Math.Int.floor(index / 4.0);
      let col = index % 4;
      let idx = serialIndex(face, row, col);
      let colour = compact.slice(idx, idx + 1 | 0);
      let n = centreCounts[colour];
      let count = n !== undefined ? n : 0;
      centreCounts[colour] = count + 1 | 0;
    });
  });
  let invalidCentres = faces.some(face => {
    let match = centreCounts[face];
    if (match !== undefined) {
      return match !== 4;
    } else {
      return true;
    }
  });
  if (invalidCentres) {
    return "Invalid 4×4 centres: each centre colour must occur exactly four times.";
  }
  let stickers = compact.split("").map(prim => prim);
  if (canComplete4x4Wings(stickers)) {
    return null;
  } else {
    return "Invalid 4×4 wings: the stickers cannot form a legal permutation and orientation of the 24 wing pieces.";
  }
}

let size = 4;

export {
  size,
  last,
  faces,
  faceIndex,
  centreIndices,
  cornerLocalIndices,
  serialIndex,
  stickerFor,
  faceletFor,
  indexFor,
  positionKey,
  rotate,
  applyGenerator,
  generators,
  wingSlots,
  allWingSlots,
  wingDestinations,
  allWingDestinations,
  staticWingSourceColours,
  staticWingDestinations,
  canComplete4x4Wings,
  cornerState,
  validate4x4,
}
/* allWingSlots Not a pure module */
