// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let storageOrder = [
  "U",
  "L",
  "F",
  "R",
  "B",
  "D"
];

let serializationOrder = [
  "U",
  "R",
  "F",
  "D",
  "L",
  "B"
];

function faceToChar(face) {
  switch (face) {
    case "U" :
      return "U";
    case "L" :
      return "L";
    case "F" :
      return "F";
    case "R" :
      return "R";
    case "B" :
      return "B";
    case "D" :
      return "D";
  }
}

function charToFace(character) {
  switch (character) {
    case "B" :
      return "B";
    case "D" :
      return "D";
    case "F" :
      return "F";
    case "L" :
      return "L";
    case "R" :
      return "R";
    case "U" :
      return "U";
    default:
      return;
  }
}

function storageIndex(face) {
  switch (face) {
    case "U" :
      return 0;
    case "L" :
      return 1;
    case "F" :
      return 2;
    case "R" :
      return 3;
    case "B" :
      return 4;
    case "D" :
      return 5;
  }
}

function isSupportedSize(size) {
  if (size >= 2) {
    return size <= 5;
  } else {
    return false;
  }
}

function solved(size) {
  if (!isSupportedSize(size)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidSize",
        _0: "Cube size must be between 2 and 5."
      }
    };
  }
  let stickersPerFace = size * size | 0;
  return {
    TAG: "Ok",
    _0: {
      size: size,
      facelets: storageOrder.map(face => Stdlib_Array.make(stickersPerFace, face))
    }
  };
}

export {
  storageOrder,
  serializationOrder,
  faceToChar,
  charToFace,
  storageIndex,
  isSupportedSize,
  solved,
}
/* No side effect */
