// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let cornerNames = [
  "UFR",
  "UFL",
  "ULB",
  "UBR",
  "DFR",
  "DLF",
  "DBL",
  "DRB"
];

let edgeNames = [
  "UR",
  "UF",
  "UL",
  "UB",
  "DR",
  "DF",
  "DL",
  "DB",
  "FR",
  "FL",
  "BL",
  "BR"
];

function permutationParity(permutation) {
  let inversions = 0;
  for (let left = 0, left_finish = permutation.length - 2 | 0; left <= left_finish; ++left) {
    for (let right = left + 1 | 0, right_finish = permutation.length; right < right_finish; ++right) {
      if (Primitive_object.greaterthan(permutation[left], permutation[right])) {
        inversions = inversions + 1 | 0;
      }
    }
  }
  return inversions % 2;
}

function affectedSlots(orientations) {
  return orientations.map((orientation, index) => [
    orientation,
    index
  ]).filter(param => param[0] !== 0).map(param => param[1]);
}

function describeSlots(names, slots) {
  return slots.map(slot => names[slot]).join(", ");
}

function describe(violation) {
  if (typeof violation !== "object") {
    return "Impossible state: one pair of pieces is swapped (corner and edge permutation parity differs).";
  }
  if (violation.TAG === "CornerTwist") {
    let locations = describeSlots(cornerNames, violation.affectedSlots);
    if (locations === "") {
      return "Impossible state: corner orientations do not add up to a whole-cube turn.";
    } else {
      return `Impossible state: a corner twist makes this cube unreachable (affected slots: ` + locations + `).`;
    }
  }
  let locations$1 = describeSlots(edgeNames, violation.affectedSlots);
  if (locations$1 === "") {
    return "Impossible state: edge orientations do not add up to a whole-cube turn.";
  } else {
    return `Impossible state: an edge flip makes this cube unreachable (affected slots: ` + locations$1 + `).`;
  }
}

function validate(state) {
  let cornerSum = Stdlib_Array.reduce(state.co, 0, (sum, value) => sum + value | 0);
  if (cornerSum % 3 !== 0) {
    return {
      TAG: "Error",
      _0: {
        TAG: "CornerTwist",
        sum: cornerSum,
        affectedSlots: affectedSlots(state.co)
      }
    };
  }
  if (state.size !== 3) {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  let edgeSum = Stdlib_Array.reduce(state.eo, 0, (sum, value) => sum + value | 0);
  if (edgeSum % 2 !== 0) {
    return {
      TAG: "Error",
      _0: {
        TAG: "EdgeFlip",
        sum: edgeSum,
        affectedSlots: affectedSlots(state.eo)
      }
    };
  } else if (permutationParity(state.cp) !== permutationParity(state.ep)) {
    return {
      TAG: "Error",
      _0: "PermutationParityMismatch"
    };
  } else {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
}

export {
  cornerNames,
  edgeNames,
  permutationParity,
  affectedSlots,
  describeSlots,
  describe,
  validate,
}
/* No side effect */
