// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NetCodec from "./State/NetCodec.res.mjs";
import * as StateTypes from "./State/StateTypes.res.mjs";
import * as FaceletCodec from "./State/FaceletCodec.res.mjs";

let state = StateTypes.solved(3);

if (state.TAG === "Ok") {
  let facelets = FaceletCodec.render(state._0);
  console.log(facelets);
  let parsed = FaceletCodec.parse(3, facelets);
  if (parsed.TAG === "Ok") {
    let parsed$1 = parsed._0;
    console.log(FaceletCodec.render(parsed$1));
    let net = NetCodec.render(parsed$1);
    console.log(net);
    let fromNet = NetCodec.parse(3, net);
    if (fromNet.TAG === "Ok") {
      console.log(FaceletCodec.render(fromNet._0));
    } else {
      console.error("Net round-trip failed.");
    }
  } else {
    console.error("Facelet round-trip failed.");
  }
} else {
  console.error("Unable to create solved cube.");
}

/* state Not a pure module */
