// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util555 from "./Util555.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function makeSolved() {
  let tCenter = Stdlib_Array.make(24, 0);
  let xCenter = Stdlib_Array.make(24, 0);
  let mEdge = Stdlib_Array.make(12, 0);
  let wEdge = Stdlib_Array.make(24, 0);
  let cp = Stdlib_Array.make(8, 0);
  let co = Stdlib_Array.make(8, 0);
  for (let i = 0; i <= 23; ++i) {
    Util555.setU(tCenter, i, i / 4 | 0);
    Util555.setU(xCenter, i, i / 4 | 0);
    Util555.setU(wEdge, i, i);
  }
  for (let i$1 = 0; i$1 <= 11; ++i$1) {
    Util555.setU(mEdge, i$1, Util555.shl(i$1, 1));
  }
  for (let i$2 = 0; i$2 <= 7; ++i$2) {
    Util555.setU(cp, i$2, i$2);
    Util555.setU(co, i$2, 0);
  }
  return {
    tCenter: tCenter,
    xCenter: xCenter,
    mEdge: mEdge,
    wEdge: wEdge,
    cp: cp,
    co: co
  };
}

function clone(c) {
  return {
    tCenter: c.tCenter.slice(),
    xCenter: c.xCenter.slice(),
    mEdge: c.mEdge.slice(),
    wEdge: c.wEdge.slice(),
    cp: c.cp.slice(),
    co: c.co.slice()
  };
}

function copyInto(src, dst) {
  for (let i = 0; i <= 23; ++i) {
    Util555.setU(dst.tCenter, i, Util555.getU(src.tCenter, i));
    Util555.setU(dst.xCenter, i, Util555.getU(src.xCenter, i));
    Util555.setU(dst.wEdge, i, Util555.getU(src.wEdge, i));
  }
  for (let i$1 = 0; i$1 <= 11; ++i$1) {
    Util555.setU(dst.mEdge, i$1, Util555.getU(src.mEdge, i$1));
  }
  for (let i$2 = 0; i$2 <= 7; ++i$2) {
    Util555.setU(dst.cp, i$2, Util555.getU(src.cp, i$2));
    Util555.setU(dst.co, i$2, Util555.getU(src.co, i$2));
  }
}

function doMove(c, move) {
  let pow = move % 3;
  let exit = 0;
  switch (move) {
    case 0 :
    case 1 :
    case 2 :
      exit = 2;
      break;
    case 3 :
    case 4 :
    case 5 :
      exit = 4;
      break;
    case 6 :
    case 7 :
    case 8 :
      exit = 6;
      break;
    case 9 :
    case 10 :
    case 11 :
      exit = 8;
      break;
    case 12 :
    case 13 :
    case 14 :
      exit = 10;
      break;
    case 15 :
    case 16 :
    case 17 :
      exit = 12;
      break;
    case 18 :
    case 19 :
    case 20 :
      exit = 1;
      break;
    case 21 :
    case 22 :
    case 23 :
      exit = 3;
      break;
    case 24 :
    case 25 :
    case 26 :
      exit = 5;
      break;
    case 27 :
    case 28 :
    case 29 :
      exit = 7;
      break;
    case 30 :
    case 31 :
    case 32 :
      exit = 9;
      break;
    case 33 :
    case 34 :
    case 35 :
      exit = 11;
      break;
    default:
      return;
  }
  switch (exit) {
    case 1 :
      Util555.swap4NoFlip(c.xCenter, 8, 20, 12, 16, pow);
      Util555.swap4NoFlip(c.xCenter, 9, 21, 13, 17, pow);
      Util555.swap4NoFlip(c.tCenter, 8, 20, 12, 16, pow);
      Util555.swap4NoFlip(c.wEdge, 9, 22, 11, 20, pow);
      Util555.swap4NoFlip(c.xCenter, 0, 1, 2, 3, pow);
      Util555.swap4NoFlip(c.tCenter, 0, 1, 2, 3, pow);
      Util555.swap4(c.mEdge, 0, 4, 1, 5, pow, false);
      Util555.swap4NoFlip(c.wEdge, 0, 4, 1, 5, pow);
      return Util555.swap4NoFlip(c.wEdge, 12, 16, 13, 17, pow);
    case 2 :
      Util555.swap4NoFlip(c.xCenter, 0, 1, 2, 3, pow);
      Util555.swap4NoFlip(c.tCenter, 0, 1, 2, 3, pow);
      Util555.swap4(c.mEdge, 0, 4, 1, 5, pow, false);
      Util555.swap4NoFlip(c.wEdge, 0, 4, 1, 5, pow);
      return Util555.swap4NoFlip(c.wEdge, 12, 16, 13, 17, pow);
    case 3 :
      Util555.swap4NoFlip(c.xCenter, 1, 15, 5, 9, pow);
      Util555.swap4NoFlip(c.xCenter, 2, 12, 6, 10, pow);
      Util555.swap4NoFlip(c.tCenter, 1, 15, 5, 9, pow);
      Util555.swap4NoFlip(c.wEdge, 1, 14, 3, 12, pow);
      Util555.swap4NoFlip(c.xCenter, 16, 17, 18, 19, pow);
      Util555.swap4NoFlip(c.tCenter, 16, 17, 18, 19, pow);
      Util555.swap4(c.mEdge, 5, 10, 6, 11, pow, true);
      Util555.swap4NoFlip(c.wEdge, 5, 22, 6, 23, pow);
      return Util555.swap4NoFlip(c.wEdge, 17, 10, 18, 11, pow);
    case 4 :
      Util555.swap4NoFlip(c.xCenter, 16, 17, 18, 19, pow);
      Util555.swap4NoFlip(c.tCenter, 16, 17, 18, 19, pow);
      Util555.swap4(c.mEdge, 5, 10, 6, 11, pow, true);
      Util555.swap4NoFlip(c.wEdge, 5, 22, 6, 23, pow);
      return Util555.swap4NoFlip(c.wEdge, 17, 10, 18, 11, pow);
    case 5 :
      Util555.swap4NoFlip(c.xCenter, 2, 19, 4, 21, pow);
      Util555.swap4NoFlip(c.xCenter, 3, 16, 5, 22, pow);
      Util555.swap4NoFlip(c.tCenter, 2, 19, 4, 21, pow);
      Util555.swap4NoFlip(c.wEdge, 5, 18, 7, 16, pow);
      Util555.swap4NoFlip(c.xCenter, 8, 9, 10, 11, pow);
      Util555.swap4NoFlip(c.tCenter, 8, 9, 10, 11, pow);
      Util555.swap4(c.mEdge, 0, 11, 3, 8, pow, false);
      Util555.swap4NoFlip(c.wEdge, 0, 11, 3, 8, pow);
      return Util555.swap4NoFlip(c.wEdge, 12, 23, 15, 20, pow);
    case 6 :
      Util555.swap4NoFlip(c.xCenter, 8, 9, 10, 11, pow);
      Util555.swap4NoFlip(c.tCenter, 8, 9, 10, 11, pow);
      Util555.swap4(c.mEdge, 0, 11, 3, 8, pow, false);
      Util555.swap4NoFlip(c.wEdge, 0, 11, 3, 8, pow);
      return Util555.swap4NoFlip(c.wEdge, 12, 23, 15, 20, pow);
    case 7 :
      Util555.swap4NoFlip(c.xCenter, 10, 18, 14, 22, pow);
      Util555.swap4NoFlip(c.xCenter, 11, 19, 15, 23, pow);
      Util555.swap4NoFlip(c.tCenter, 10, 18, 14, 22, pow);
      Util555.swap4NoFlip(c.wEdge, 8, 23, 10, 21, pow);
      Util555.swap4NoFlip(c.xCenter, 4, 5, 6, 7, pow);
      Util555.swap4NoFlip(c.tCenter, 4, 5, 6, 7, pow);
      Util555.swap4(c.mEdge, 2, 7, 3, 6, pow, false);
      Util555.swap4NoFlip(c.wEdge, 2, 7, 3, 6, pow);
      return Util555.swap4NoFlip(c.wEdge, 14, 19, 15, 18, pow);
    case 8 :
      Util555.swap4NoFlip(c.xCenter, 4, 5, 6, 7, pow);
      Util555.swap4NoFlip(c.tCenter, 4, 5, 6, 7, pow);
      Util555.swap4(c.mEdge, 2, 7, 3, 6, pow, false);
      Util555.swap4NoFlip(c.wEdge, 2, 7, 3, 6, pow);
      return Util555.swap4NoFlip(c.wEdge, 14, 19, 15, 18, pow);
    case 9 :
      Util555.swap4NoFlip(c.xCenter, 0, 8, 4, 14, pow);
      Util555.swap4NoFlip(c.xCenter, 3, 11, 7, 13, pow);
      Util555.swap4NoFlip(c.tCenter, 3, 11, 7, 13, pow);
      Util555.swap4NoFlip(c.wEdge, 0, 15, 2, 13, pow);
      Util555.swap4NoFlip(c.xCenter, 20, 21, 22, 23, pow);
      Util555.swap4NoFlip(c.tCenter, 20, 21, 22, 23, pow);
      Util555.swap4(c.mEdge, 4, 8, 7, 9, pow, true);
      Util555.swap4NoFlip(c.wEdge, 4, 20, 7, 21, pow);
      return Util555.swap4NoFlip(c.wEdge, 16, 8, 19, 9, pow);
    case 10 :
      Util555.swap4NoFlip(c.xCenter, 20, 21, 22, 23, pow);
      Util555.swap4NoFlip(c.tCenter, 20, 21, 22, 23, pow);
      Util555.swap4(c.mEdge, 4, 8, 7, 9, pow, true);
      Util555.swap4NoFlip(c.wEdge, 4, 20, 7, 21, pow);
      return Util555.swap4NoFlip(c.wEdge, 16, 8, 19, 9, pow);
    case 11 :
      Util555.swap4NoFlip(c.xCenter, 1, 20, 7, 18, pow);
      Util555.swap4NoFlip(c.xCenter, 0, 23, 6, 17, pow);
      Util555.swap4NoFlip(c.tCenter, 0, 23, 6, 17, pow);
      Util555.swap4NoFlip(c.wEdge, 4, 19, 6, 17, pow);
      Util555.swap4NoFlip(c.xCenter, 12, 13, 14, 15, pow);
      Util555.swap4NoFlip(c.tCenter, 12, 13, 14, 15, pow);
      Util555.swap4(c.mEdge, 1, 9, 2, 10, pow, false);
      Util555.swap4NoFlip(c.wEdge, 1, 9, 2, 10, pow);
      return Util555.swap4NoFlip(c.wEdge, 13, 21, 14, 22, pow);
    case 12 :
      Util555.swap4NoFlip(c.xCenter, 12, 13, 14, 15, pow);
      Util555.swap4NoFlip(c.tCenter, 12, 13, 14, 15, pow);
      Util555.swap4(c.mEdge, 1, 9, 2, 10, pow, false);
      Util555.swap4NoFlip(c.wEdge, 1, 9, 2, 10, pow);
      return Util555.swap4NoFlip(c.wEdge, 13, 21, 14, 22, pow);
  }
}

export {
  makeSolved,
  clone,
  copyInto,
  doMove,
}
/* Util555 Not a pure module */
