// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util555 from "./Util555.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let validMoves = [
  0,
  1,
  2,
  4,
  7,
  9,
  10,
  11,
  13,
  16,
  19,
  22,
  25,
  28,
  31,
  34
];

function make() {
  let udtCenter = Stdlib_Array.make(8, 0);
  let udxCenter = Stdlib_Array.make(8, 0);
  let rltCenter = Stdlib_Array.make(8, 0);
  let rlxCenter = Stdlib_Array.make(8, 0);
  Util555.setComb(udxCenter, 0, 4, 8);
  Util555.setComb(udtCenter, 0, 4, 8);
  Util555.setComb(rlxCenter, 0, 4, 8);
  Util555.setComb(rltCenter, 0, 4, 8);
  return {
    udtCenter: udtCenter,
    udxCenter: udxCenter,
    rltCenter: rltCenter,
    rlxCenter: rlxCenter
  };
}

function setUDCenter(c, idx) {
  Util555.setComb(c.udxCenter, idx / 70 | 0, 4, 8);
  Util555.setComb(c.udtCenter, idx % 70, 4, 8);
}

function getUDCenter(c) {
  return (Util555.getComb(c.udxCenter, 4, 8) * 70 | 0) + Util555.getComb(c.udtCenter, 4, 8) | 0;
}

function setRLCenter(c, idx) {
  Util555.setComb(c.rlxCenter, idx / 70 | 0, 4, 8);
  Util555.setComb(c.rltCenter, idx % 70, 4, 8);
}

function getRLCenter(c) {
  if (Util555.getU(c.rlxCenter, 7) !== -1) {
    for (let i = 0; i <= 7; ++i) {
      Util555.setU(c.rlxCenter, i, -1 - Util555.getU(c.rlxCenter, i) | 0);
    }
    for (let i$1 = 0; i$1 <= 3; ++i$1) {
      let k = Util555.bitOr(Util555.shl(i$1, 1), 1);
      Util555.setU(c.rltCenter, k, -1 - Util555.getU(c.rltCenter, k) | 0);
    }
  }
  return (Util555.getComb(c.rlxCenter, 4, 8) * 70 | 0) + Util555.getComb(c.rltCenter, 4, 8) | 0;
}

function doMove(c, moveIdx) {
  let move = Util555.getU(validMoves, moveIdx);
  let pow = move % 3;
  let exit = 0;
  switch (move) {
    case 0 :
    case 1 :
    case 2 :
      exit = 1;
      break;
    case 4 :
      Util555.swap4NoFlip(c.rltCenter, 0, 1, 2, 3, pow);
      return Util555.swap4NoFlip(c.rlxCenter, 0, 1, 2, 3, pow);
    case 9 :
    case 10 :
    case 11 :
      exit = 2;
      break;
    case 13 :
      Util555.swap4NoFlip(c.rltCenter, 4, 5, 6, 7, pow);
      return Util555.swap4NoFlip(c.rlxCenter, 4, 5, 6, 7, pow);
    case 19 :
      Util555.swap2(c.rltCenter, 3, 7);
      Util555.swap2(c.rlxCenter, 3, 7);
      Util555.swap2(c.rlxCenter, 0, 4);
      Util555.swap4NoFlip(c.udtCenter, 0, 1, 2, 3, pow);
      return Util555.swap4NoFlip(c.udxCenter, 0, 1, 2, 3, pow);
    case 22 :
      Util555.swap2(c.udtCenter, 1, 5);
      Util555.swap2(c.udxCenter, 1, 5);
      return Util555.swap2(c.udxCenter, 2, 6);
    case 25 :
      Util555.swap2(c.udtCenter, 2, 4);
      Util555.swap2(c.udxCenter, 2, 4);
      Util555.swap2(c.udxCenter, 3, 5);
      Util555.swap2(c.rltCenter, 2, 4);
      Util555.swap2(c.rlxCenter, 2, 4);
      return Util555.swap2(c.rlxCenter, 3, 5);
    case 28 :
      Util555.swap2(c.rltCenter, 1, 5);
      Util555.swap2(c.rlxCenter, 1, 5);
      Util555.swap2(c.rlxCenter, 2, 6);
      Util555.swap4NoFlip(c.udtCenter, 4, 5, 6, 7, pow);
      return Util555.swap4NoFlip(c.udxCenter, 4, 5, 6, 7, pow);
    case 31 :
      Util555.swap2(c.udtCenter, 3, 7);
      Util555.swap2(c.udxCenter, 3, 7);
      return Util555.swap2(c.udxCenter, 0, 4);
    case 34 :
      Util555.swap2(c.udtCenter, 0, 6);
      Util555.swap2(c.udxCenter, 0, 6);
      Util555.swap2(c.udxCenter, 1, 7);
      Util555.swap2(c.rltCenter, 0, 6);
      Util555.swap2(c.rlxCenter, 0, 6);
      return Util555.swap2(c.rlxCenter, 1, 7);
    default:
      return;
  }
  switch (exit) {
    case 1 :
      Util555.swap4NoFlip(c.udtCenter, 0, 1, 2, 3, pow);
      return Util555.swap4NoFlip(c.udxCenter, 0, 1, 2, 3, pow);
    case 2 :
      Util555.swap4NoFlip(c.udtCenter, 4, 5, 6, 7, pow);
      return Util555.swap4NoFlip(c.udxCenter, 4, 5, 6, 7, pow);
  }
}

export {
  validMoves,
  make,
  setUDCenter,
  getUDCenter,
  setRLCenter,
  getRLCenter,
  doMove,
}
/* Util555 Not a pure module */
