// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util555 from "./Util555.res.mjs";

let makeNibbleTable = (function(nState) {
  const byteLen = (nState + 1) >> 1;
  const arr = new Uint8Array(byteLen);
  arr.fill(0xff);
  return arr;
});

let getDistance = (function(table, idx) {
  const byte = table[idx >>> 1];
  return (byte >>> ((idx & 1) << 2)) & 0x0f;
});

let setDistance = (function(table, idx, val) {
  const byteIdx = idx >>> 1;
  const shift = (idx & 1) << 2;
  table[byteIdx] = (table[byteIdx] & ~(0x0f << shift)) | ((val & 0x0f) << shift);
});

function buildBfsPruningTable(nState, moveTable, solvedStates, maxDepth) {
  let table = makeNibbleTable(nState);
  let nMoves = moveTable.length !== 0 ? Util555.getU(moveTable, 0).length : 0;
  for (let i = 0, i_finish = solvedStates.length; i < i_finish; ++i) {
    let s = Util555.getU(solvedStates, i);
    setDistance(table, s, 0);
  }
  let depth = 0;
  let done = solvedStates.length;
  while (done > 0 && depth < maxDepth) {
    let targetDist = depth;
    let nextDist = targetDist + 1 | 0;
    let newlyReached = 0;
    for (let state = 0; state < nState; ++state) {
      if (getDistance(table, state) === targetDist) {
        for (let m = 0; m < nMoves; ++m) {
          let nextState = Util555.getU2(moveTable, state, m);
          if (nextState >= 0 && nextState < nState && getDistance(table, nextState) === 15) {
            setDistance(table, nextState, nextDist);
            newlyReached = newlyReached + 1 | 0;
          }
        }
      }
    }
    done = newlyReached;
    depth = depth + 1 | 0;
  };
  return table;
}

export {
  makeNibbleTable,
  getDistance,
  setDistance,
  buildBfsPruningTable,
}
/* Util555 Not a pure module */
