// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let bitAnd = ((a, b) => (a & b));

let bitOr = ((a, b) => (a | b));

let bitXor = ((a, b) => (a ^ b));

let bitNot = (a => (~a));

let shl = ((a, b) => (a << b));

let shr = ((a, b) => (a >> b));

let shru = ((a, b) => (a >>> b));

let bitCount = (function(n) {
  n = n - ((n >>> 1) & 0x55555555);
  n = (n & 0x33333333) + ((n >>> 2) & 0x33333333);
  return (((n + (n >>> 4)) & 0x0F0F0F0F) * 0x01010101) >>> 24;
});

let getU = ((arr, idx) => arr[idx]);

let setU = ((arr, idx, val) => { arr[idx] = val; });

let getU2 = ((arr, i, j) => arr[i][j]);

let setU2 = ((arr, i, j, val) => { arr[i][j] = val; });

let move2str = [
  "U",
  "U2",
  "U'",
  "R",
  "R2",
  "R'",
  "F",
  "F2",
  "F'",
  "D",
  "D2",
  "D'",
  "L",
  "L2",
  "L'",
  "B",
  "B2",
  "B'",
  "2U",
  "2U2",
  "2U'",
  "2R",
  "2R2",
  "2R'",
  "2F",
  "2F2",
  "2F'",
  "2D",
  "2D2",
  "2D'",
  "2L",
  "2L2",
  "2L'",
  "2B",
  "2B2",
  "2B'"
];

let table = (Array.from({ length: 25 }, () => new Int32Array(25)));

for (let i = 0; i <= 24; ++i) {
  setU2(table, i, i, 1);
  setU2(table, i, 0, 1);
}

for (let i$1 = 1; i$1 <= 24; ++i$1) {
  for (let j = 1; j <= i$1; ++j) {
    setU2(table, i$1, j, getU2(table, i$1 - 1 | 0, j) + getU2(table, i$1 - 1 | 0, j - 1 | 0) | 0);
  }
}

let table$1 = Stdlib_Array.make(13, 1);

for (let i$2 = 1; i$2 <= 12; ++i$2) {
  setU(table$1, i$2, getU(table$1, i$2 - 1 | 0) * i$2 | 0);
}

function swap2(arr, a, b) {
  let temp = getU(arr, a);
  setU(arr, a, getU(arr, b));
  setU(arr, b, temp);
}

function swap4(arr, a, b, c, d, pow, flip) {
  let xorVal = flip ? 1 : 0;
  if (pow !== 0) {
    if (pow !== 1) {
      let temp = bitXor(getU(arr, a), xorVal);
      setU(arr, a, bitXor(getU(arr, b), xorVal));
      setU(arr, b, bitXor(getU(arr, c), xorVal));
      setU(arr, c, bitXor(getU(arr, d), xorVal));
      return setU(arr, d, temp);
    }
    let temp$1 = getU(arr, a);
    setU(arr, a, getU(arr, c));
    setU(arr, c, temp$1);
    let temp2 = getU(arr, b);
    setU(arr, b, getU(arr, d));
    return setU(arr, d, temp2);
  }
  let temp$2 = bitXor(getU(arr, d), xorVal);
  setU(arr, d, bitXor(getU(arr, c), xorVal));
  setU(arr, c, bitXor(getU(arr, b), xorVal));
  setU(arr, b, bitXor(getU(arr, a), xorVal));
  setU(arr, a, temp$2);
}

function swap4NoFlip(arr, a, b, c, d, pow) {
  swap4(arr, a, b, c, d, pow, false);
}

function getComb(arr, r0, n) {
  let idx = 0;
  let r = r0;
  for (let i = n - 1 | 0; i >= 0; --i) {
    if (getU(arr, i) !== -1) {
      idx = idx + getU2(table, i, r) | 0;
      r = r - 1 | 0;
    }
  }
  return idx;
}

function getSComb(arr, n) {
  let idx = 0;
  let r = n / 2 | 0;
  let lastVal = getU(arr, n - 1 | 0);
  for (let i = n - 1 | 0; i >= 0; --i) {
    if (getU(arr, i) !== lastVal) {
      idx = idx + getU2(table, i, r) | 0;
      r = r - 1 | 0;
    }
  }
  return idx;
}

function setComb(arr, idx0, r0, n) {
  let idx = idx0;
  let r = r0;
  for (let i = n - 1 | 0; i >= 0; --i) {
    let c = getU2(table, i, r);
    if (idx >= c) {
      idx = idx - c | 0;
      r = r - 1 | 0;
      setU(arr, i, 0);
    } else {
      setU(arr, i, -1);
    }
  }
  return arr;
}

function getParity(arr) {
  let parity = 0;
  let len = arr.length;
  for (let i = 0, i_finish = len - 2 | 0; i <= i_finish; ++i) {
    for (let j = i + 1 | 0; j < len; ++j) {
      if (getU(arr, i) > getU(arr, j)) {
        parity = bitXor(parity, 1);
      }
    }
  }
  return parity;
}

function genSkipMoves(validMoves) {
  let len = validMoves.length;
  let ret = Stdlib_Array.make(len + 1 | 0, 0);
  for (let last = 0; last < len; ++last) {
    let mask = 0;
    let la = getU(validMoves, last) / 3 | 0;
    for (let move = 0; move < len; ++move) {
      let axis = getU(validMoves, move) / 3 | 0;
      if (axis === la || axis % 3 === la % 3 && axis >= la) {
        mask = bitOr(mask, shl(1, move));
      }
    }
    setU(ret, last, mask);
  }
  return ret;
}

function genNextAxis(validMoves) {
  let ret = 0;
  for (let i = 0, i_finish = validMoves.length; i < i_finish; ++i) {
    if (getU(validMoves, i) % 3 === 0) {
      ret = bitOr(ret, shl(1, i + 1 | 0));
    }
  }
  return ret;
}

function getPrunNibble(table, idx) {
  let intIdx = shr(idx, 3);
  let shift = shl(bitAnd(idx, 7), 2);
  return bitAnd(shr(getU(table, intIdx), shift), 15);
}

function setPrunNibble(table, idx, value) {
  let intIdx = shr(idx, 3);
  let shift = shl(bitAnd(idx, 7), 2);
  let mask = bitNot(shl(15, shift));
  setU(table, intIdx, bitOr(bitAnd(getU(table, intIdx), mask), shl(bitAnd(value, 15), shift)));
}

let ux1 = 0;

let ux2 = 1;

let ux3 = 2;

let rx1 = 3;

let rx2 = 4;

let rx3 = 5;

let fx1 = 6;

let fx2 = 7;

let fx3 = 8;

let dx1 = 9;

let dx2 = 10;

let dx3 = 11;

let lx1 = 12;

let lx2 = 13;

let lx3 = 14;

let bx1 = 15;

let bx2 = 16;

let bx3 = 17;

let sliceUx1 = 18;

let sliceUx2 = 19;

let sliceUx3 = 20;

let sliceRx1 = 21;

let sliceRx2 = 22;

let sliceRx3 = 23;

let sliceFx1 = 24;

let sliceFx2 = 25;

let sliceFx3 = 26;

let sliceDx1 = 27;

let sliceDx2 = 28;

let sliceDx3 = 29;

let sliceLx1 = 30;

let sliceLx2 = 31;

let sliceLx3 = 32;

let sliceBx1 = 33;

let sliceBx2 = 34;

let sliceBx3 = 35;

let cnk = table;

let fact = table$1;

export {
  bitAnd,
  bitOr,
  bitXor,
  bitNot,
  shl,
  shr,
  shru,
  bitCount,
  getU,
  setU,
  getU2,
  setU2,
  ux1,
  ux2,
  ux3,
  rx1,
  rx2,
  rx3,
  fx1,
  fx2,
  fx3,
  dx1,
  dx2,
  dx3,
  lx1,
  lx2,
  lx3,
  bx1,
  bx2,
  bx3,
  sliceUx1,
  sliceUx2,
  sliceUx3,
  sliceRx1,
  sliceRx2,
  sliceRx3,
  sliceFx1,
  sliceFx2,
  sliceFx3,
  sliceDx1,
  sliceDx2,
  sliceDx3,
  sliceLx1,
  sliceLx2,
  sliceLx3,
  sliceBx1,
  sliceBx2,
  sliceBx3,
  move2str,
  cnk,
  fact,
  swap2,
  swap4,
  swap4NoFlip,
  getComb,
  getSComb,
  setComb,
  getParity,
  genSkipMoves,
  genNextAxis,
  getPrunNibble,
  setPrunNibble,
}
/* table Not a pure module */
